<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Primers | Environmental Systems Data Science</title>
  <meta name="description" content="Tutorial and exercises for Environmental System Data Science, ETH Zürich." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Primers | Environmental Systems Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Tutorial and exercises for Environmental System Data Science, ETH Zürich." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Primers | Environmental Systems Data Science" />
  
  <meta name="twitter:description" content="Tutorial and exercises for Environmental System Data Science, ETH Zürich." />
  

<meta name="author" content="Loïc Pellissier, Joshua Payne, Benjamin Stocker" />


<meta name="date" content="2021-12-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="ch-02.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prerequisites</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course Description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-objectives"><i class="fa fa-check"></i>Course Objectives</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#content"><i class="fa fa-check"></i>Content</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#useful-prerequisites"><i class="fa fa-check"></i>Useful Prerequisites</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch-01.html"><a href="ch-01.html"><i class="fa fa-check"></i><b>1</b> Primers</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch-01.html"><a href="ch-01.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ch-01.html"><a href="ch-01.html#key-points-from-the-lecture"><i class="fa fa-check"></i><b>1.1.1</b> Key Points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch-01.html"><a href="ch-01.html#tutorial"><i class="fa fa-check"></i><b>1.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ch-01.html"><a href="ch-01.html#working-with-rstudio-on-renku"><i class="fa fa-check"></i><b>1.2.1</b> Working with RStudio on Renku</a></li>
<li class="chapter" data-level="1.2.2" data-path="ch-01.html"><a href="ch-01.html#git"><i class="fa fa-check"></i><b>1.2.2</b> Git</a></li>
<li class="chapter" data-level="1.2.3" data-path="ch-01.html"><a href="ch-01.html#libraries"><i class="fa fa-check"></i><b>1.2.3</b> Libraries</a></li>
<li class="chapter" data-level="1.2.4" data-path="ch-01.html"><a href="ch-01.html#r-scripts"><i class="fa fa-check"></i><b>1.2.4</b> R scripts</a></li>
<li class="chapter" data-level="1.2.5" data-path="ch-01.html"><a href="ch-01.html#rmarkdown"><i class="fa fa-check"></i><b>1.2.5</b> RMarkdown</a></li>
<li class="chapter" data-level="1.2.6" data-path="ch-01.html"><a href="ch-01.html#functions"><i class="fa fa-check"></i><b>1.2.6</b> Functions</a></li>
<li class="chapter" data-level="1.2.7" data-path="ch-01.html"><a href="ch-01.html#tidy-data"><i class="fa fa-check"></i><b>1.2.7</b> Tidy data</a></li>
<li class="chapter" data-level="1.2.8" data-path="ch-01.html"><a href="ch-01.html#r-projects"><i class="fa fa-check"></i><b>1.2.8</b> R projects</a></li>
<li class="chapter" data-level="1.2.9" data-path="ch-01.html"><a href="ch-01.html#working-with-data-frames"><i class="fa fa-check"></i><b>1.2.9</b> Working with data frames</a></li>
<li class="chapter" data-level="1.2.10" data-path="ch-01.html"><a href="ch-01.html#r-objects"><i class="fa fa-check"></i><b>1.2.10</b> R objects</a></li>
<li class="chapter" data-level="1.2.11" data-path="ch-01.html"><a href="ch-01.html#data-visualisation"><i class="fa fa-check"></i><b>1.2.11</b> Data visualisation</a></li>
<li class="chapter" data-level="1.2.12" data-path="ch-01.html"><a href="ch-01.html#conditionals"><i class="fa fa-check"></i><b>1.2.12</b> Conditionals</a></li>
<li class="chapter" data-level="1.2.13" data-path="ch-01.html"><a href="ch-01.html#loops"><i class="fa fa-check"></i><b>1.2.13</b> Loops</a></li>
<li class="chapter" data-level="1.2.14" data-path="ch-01.html"><a href="ch-01.html#where-to-find-help"><i class="fa fa-check"></i><b>1.2.14</b> Where to find help</a></li>
<li class="chapter" data-level="1.2.15" data-path="ch-01.html"><a href="ch-01.html#key-points-from-the-tutorial"><i class="fa fa-check"></i><b>1.2.15</b> Key points from the tutorial</a></li>
<li class="chapter" data-level="1.2.16" data-path="ch-01.html"><a href="ch-01.html#further-reading"><i class="fa fa-check"></i><b>1.2.16</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="ch-01.html"><a href="ch-01.html#exercise"><i class="fa fa-check"></i><b>1.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch-02.html"><a href="ch-02.html"><i class="fa fa-check"></i><b>2</b> Data wrangling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch-02.html"><a href="ch-02.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ch-02.html"><a href="ch-02.html#learning-objectives"><i class="fa fa-check"></i><b>2.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="ch-02.html"><a href="ch-02.html#key-points-from-the-lecture-1"><i class="fa fa-check"></i><b>2.1.2</b> Key points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ch-02.html"><a href="ch-02.html#tutorial-1"><i class="fa fa-check"></i><b>2.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ch-02.html"><a href="ch-02.html#libraries-1"><i class="fa fa-check"></i><b>2.2.1</b> Libraries</a></li>
<li class="chapter" data-level="2.2.2" data-path="ch-02.html"><a href="ch-02.html#variables-in-a-data-frame"><i class="fa fa-check"></i><b>2.2.2</b> Variables in a data frame</a></li>
<li class="chapter" data-level="2.2.3" data-path="ch-02.html"><a href="ch-02.html#time-objects"><i class="fa fa-check"></i><b>2.2.3</b> Time objects</a></li>
<li class="chapter" data-level="2.2.4" data-path="ch-02.html"><a href="ch-02.html#variable-re--definition"><i class="fa fa-check"></i><b>2.2.4</b> Variable (re-) definition</a></li>
<li class="chapter" data-level="2.2.5" data-path="ch-02.html"><a href="ch-02.html#selecting-cleaning-and-gap-filling"><i class="fa fa-check"></i><b>2.2.5</b> Selecting, cleaning and gap-filling</a></li>
<li class="chapter" data-level="2.2.6" data-path="ch-02.html"><a href="ch-02.html#functions-1"><i class="fa fa-check"></i><b>2.2.6</b> Functions</a></li>
<li class="chapter" data-level="2.2.7" data-path="ch-02.html"><a href="ch-02.html#data-overview"><i class="fa fa-check"></i><b>2.2.7</b> Data overview</a></li>
<li class="chapter" data-level="2.2.8" data-path="ch-02.html"><a href="ch-02.html#data-visualisation-i"><i class="fa fa-check"></i><b>2.2.8</b> Data visualisation I</a></li>
<li class="chapter" data-level="2.2.9" data-path="ch-02.html"><a href="ch-02.html#aggregating"><i class="fa fa-check"></i><b>2.2.9</b> Aggregating</a></li>
<li class="chapter" data-level="2.2.10" data-path="ch-02.html"><a href="ch-02.html#data-visualisation-ii"><i class="fa fa-check"></i><b>2.2.10</b> Data visualisation II</a></li>
<li class="chapter" data-level="2.2.11" data-path="ch-02.html"><a href="ch-02.html#functional-programming-i"><i class="fa fa-check"></i><b>2.2.11</b> Functional programming I</a></li>
<li class="chapter" data-level="2.2.12" data-path="ch-02.html"><a href="ch-02.html#strings"><i class="fa fa-check"></i><b>2.2.12</b> Strings</a></li>
<li class="chapter" data-level="2.2.13" data-path="ch-02.html"><a href="ch-02.html#combining-relational-data"><i class="fa fa-check"></i><b>2.2.13</b> Combining relational data</a></li>
<li class="chapter" data-level="2.2.14" data-path="ch-02.html"><a href="ch-02.html#key-points-from-the-tutorial-1"><i class="fa fa-check"></i><b>2.2.14</b> Key points from the tutorial</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ch-02.html"><a href="ch-02.html#exercise-1"><i class="fa fa-check"></i><b>2.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch-03.html"><a href="ch-03.html"><i class="fa fa-check"></i><b>3</b> Data variety</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch-03.html"><a href="ch-03.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="ch-03.html"><a href="ch-03.html#overview"><i class="fa fa-check"></i><b>3.1.1</b> Overview</a></li>
<li class="chapter" data-level="3.1.2" data-path="ch-03.html"><a href="ch-03.html#learning-objectives-1"><i class="fa fa-check"></i><b>3.1.2</b> Learning objectives</a></li>
<li class="chapter" data-level="3.1.3" data-path="ch-03.html"><a href="ch-03.html#key-points-from-the-lecture-2"><i class="fa fa-check"></i><b>3.1.3</b> Key points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ch-03.html"><a href="ch-03.html#tutorial-2"><i class="fa fa-check"></i><b>3.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="ch-03.html"><a href="ch-03.html#overview-1"><i class="fa fa-check"></i><b>3.2.1</b> Overview</a></li>
<li class="chapter" data-level="3.2.2" data-path="ch-03.html"><a href="ch-03.html#modis-remote-download"><i class="fa fa-check"></i><b>3.2.2</b> MODIS remote download</a></li>
<li class="chapter" data-level="3.2.3" data-path="ch-03.html"><a href="ch-03.html#points-on-the-globe"><i class="fa fa-check"></i><b>3.2.3</b> Points on the globe</a></li>
<li class="chapter" data-level="3.2.4" data-path="ch-03.html"><a href="ch-03.html#shapefiles"><i class="fa fa-check"></i><b>3.2.4</b> Shapefiles</a></li>
<li class="chapter" data-level="3.2.5" data-path="ch-03.html"><a href="ch-03.html#rasters"><i class="fa fa-check"></i><b>3.2.5</b> Rasters</a></li>
<li class="chapter" data-level="3.2.6" data-path="ch-03.html"><a href="ch-03.html#key-points-from-the-tutorial-2"><i class="fa fa-check"></i><b>3.2.6</b> Key points from the tutorial</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ch-03.html"><a href="ch-03.html#exercise-2"><i class="fa fa-check"></i><b>3.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch-04.html"><a href="ch-04.html"><i class="fa fa-check"></i><b>4</b> Data Scraping</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch-04.html"><a href="ch-04.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="ch-04.html"><a href="ch-04.html#key-points-from-the-lecture-3"><i class="fa fa-check"></i><b>4.1.1</b> Key points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="ch-04.html"><a href="ch-04.html#tutorial-3"><i class="fa fa-check"></i><b>4.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="ch-04.html"><a href="ch-04.html#r-packages-and-functions"><i class="fa fa-check"></i><b>4.2.1</b> R-Packages and Functions</a></li>
<li class="chapter" data-level="4.2.2" data-path="ch-04.html"><a href="ch-04.html#the-fishbase-website"><i class="fa fa-check"></i><b>4.2.2</b> The FishBase website</a></li>
<li class="chapter" data-level="4.2.3" data-path="ch-04.html"><a href="ch-04.html#accessing-fishbase"><i class="fa fa-check"></i><b>4.2.3</b> Accessing FishBase</a></li>
<li class="chapter" data-level="4.2.4" data-path="ch-04.html"><a href="ch-04.html#scraping-numbers"><i class="fa fa-check"></i><b>4.2.4</b> Scraping Numbers</a></li>
<li class="chapter" data-level="4.2.5" data-path="ch-04.html"><a href="ch-04.html#scraping-text-snippetrs"><i class="fa fa-check"></i><b>4.2.5</b> Scraping Text Snippetrs</a></li>
<li class="chapter" data-level="4.2.6" data-path="ch-04.html"><a href="ch-04.html#scraping-tables"><i class="fa fa-check"></i><b>4.2.6</b> Scraping Tables</a></li>
<li class="chapter" data-level="4.2.7" data-path="ch-04.html"><a href="ch-04.html#the-fishbase-package"><i class="fa fa-check"></i><b>4.2.7</b> The Fishbase Package</a></li>
<li class="chapter" data-level="4.2.8" data-path="ch-04.html"><a href="ch-04.html#summary"><i class="fa fa-check"></i><b>4.2.8</b> Summary</a></li>
<li class="chapter" data-level="4.2.9" data-path="ch-04.html"><a href="ch-04.html#case-study"><i class="fa fa-check"></i><b>4.2.9</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ch-04.html"><a href="ch-04.html#exercise-3"><i class="fa fa-check"></i><b>4.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch-05.html"><a href="ch-05.html"><i class="fa fa-check"></i><b>5</b> Catch-up</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch-05.html"><a href="ch-05.html#loops-in-r"><i class="fa fa-check"></i><b>5.1</b> Loops in R</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="ch-05.html"><a href="ch-05.html#some-simple-examples"><i class="fa fa-check"></i><b>5.1.1</b> Some simple examples</a></li>
<li class="chapter" data-level="5.1.2" data-path="ch-05.html"><a href="ch-05.html#nested-loops"><i class="fa fa-check"></i><b>5.1.2</b> Nested loops</a></li>
<li class="chapter" data-level="5.1.3" data-path="ch-05.html"><a href="ch-05.html#exercise-4"><i class="fa fa-check"></i><b>5.1.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="ch-05.html"><a href="ch-05.html#functional-programming-using-purr"><i class="fa fa-check"></i><b>5.2</b> Functional programming using purr</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="ch-05.html"><a href="ch-05.html#shortcuts-in-a-purrr-function"><i class="fa fa-check"></i><b>5.2.1</b> Shortcuts in a <code>purrr</code> function</a></li>
<li class="chapter" data-level="5.2.2" data-path="ch-05.html"><a href="ch-05.html#workflow-nested-data-map-and-mutate"><i class="fa fa-check"></i><b>5.2.2</b> Workflow: nested data, map and mutate</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ch-05.html"><a href="ch-05.html#string-manipulations"><i class="fa fa-check"></i><b>5.3</b> String Manipulations</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="ch-05.html"><a href="ch-05.html#introduction-to-strings"><i class="fa fa-check"></i><b>5.3.1</b> Introduction to strings</a></li>
<li class="chapter" data-level="5.3.2" data-path="ch-05.html"><a href="ch-05.html#matching-and-extracting-patterns"><i class="fa fa-check"></i><b>5.3.2</b> Matching and extracting patterns</a></li>
<li class="chapter" data-level="5.3.3" data-path="ch-05.html"><a href="ch-05.html#advanced-example"><i class="fa fa-check"></i><b>5.3.3</b> Advanced example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="ch-05.html"><a href="ch-05.html#web-scraping-in-a-nut-shell"><i class="fa fa-check"></i><b>5.4</b> Web-scraping in a nut-shell</a></li>
<li class="chapter" data-level="5.5" data-path="ch-05.html"><a href="ch-05.html#tidyverses-filter-and-select"><i class="fa fa-check"></i><b>5.5</b> Tidyverse’s filter and select</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="ch-05.html"><a href="ch-05.html#introduction-4"><i class="fa fa-check"></i><b>5.5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.5.2" data-path="ch-05.html"><a href="ch-05.html#select"><i class="fa fa-check"></i><b>5.5.2</b> Select()</a></li>
<li class="chapter" data-level="5.5.3" data-path="ch-05.html"><a href="ch-05.html#filter"><i class="fa fa-check"></i><b>5.5.3</b> Filter()</a></li>
<li class="chapter" data-level="5.5.4" data-path="ch-05.html"><a href="ch-05.html#exercises"><i class="fa fa-check"></i><b>5.5.4</b> Exercises</a></li>
<li class="chapter" data-level="5.5.5" data-path="ch-05.html"><a href="ch-05.html#solutions"><i class="fa fa-check"></i><b>5.5.5</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="ch-05.html"><a href="ch-05.html#preparing-data-for-ggplot"><i class="fa fa-check"></i><b>5.6</b> Preparing data for ggplot()</a></li>
<li class="chapter" data-level="5.7" data-path="ch-05.html"><a href="ch-05.html#base-r-functions"><i class="fa fa-check"></i><b>5.7</b> Base R functions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch-06.html"><a href="ch-06.html"><i class="fa fa-check"></i><b>6</b> Supervised Machine Learning I</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch-06.html"><a href="ch-06.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="ch-06.html"><a href="ch-06.html#learning-objectives-2"><i class="fa fa-check"></i><b>6.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="6.1.2" data-path="ch-06.html"><a href="ch-06.html#important-points-from-the-lecture"><i class="fa fa-check"></i><b>6.1.2</b> Important points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ch-06.html"><a href="ch-06.html#tutorial-4"><i class="fa fa-check"></i><b>6.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ch-06.html"><a href="ch-06.html#overfitting"><i class="fa fa-check"></i><b>6.2.1</b> Overfitting</a></li>
<li class="chapter" data-level="6.2.2" data-path="ch-06.html"><a href="ch-06.html#motivation"><i class="fa fa-check"></i><b>6.2.2</b> Modelling challenge</a></li>
<li class="chapter" data-level="6.2.3" data-path="ch-06.html"><a href="ch-06.html#a-selection-of-model-types"><i class="fa fa-check"></i><b>6.2.3</b> A selection of model types</a></li>
<li class="chapter" data-level="6.2.4" data-path="ch-06.html"><a href="ch-06.html#data-splitting"><i class="fa fa-check"></i><b>6.2.4</b> Data splitting</a></li>
<li class="chapter" data-level="6.2.5" data-path="ch-06.html"><a href="ch-06.html#preprocessing"><i class="fa fa-check"></i><b>6.2.5</b> Pre-processing</a></li>
<li class="chapter" data-level="6.2.6" data-path="ch-06.html"><a href="ch-06.html#model-formulation"><i class="fa fa-check"></i><b>6.2.6</b> Model formulation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ch-06.html"><a href="ch-06.html#exercise-5"><i class="fa fa-check"></i><b>6.3</b> Exercise</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ch-06.html"><a href="ch-06.html#reading-and-cleaning"><i class="fa fa-check"></i><b>6.3.1</b> Reading and cleaning</a></li>
<li class="chapter" data-level="6.3.2" data-path="ch-06.html"><a href="ch-06.html#data-splitting-1"><i class="fa fa-check"></i><b>6.3.2</b> Data splitting</a></li>
<li class="chapter" data-level="6.3.3" data-path="ch-06.html"><a href="ch-06.html#linear-model"><i class="fa fa-check"></i><b>6.3.3</b> Linear model</a></li>
<li class="chapter" data-level="6.3.4" data-path="ch-06.html"><a href="ch-06.html#pre-processing"><i class="fa fa-check"></i><b>6.3.4</b> Pre-processing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch-07.html"><a href="ch-07.html"><i class="fa fa-check"></i><b>7</b> Supervised Machine Learning II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch-07.html"><a href="ch-07.html#introduction-6"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="ch-07.html"><a href="ch-07.html#learning-objectives-3"><i class="fa fa-check"></i><b>7.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="7.1.2" data-path="ch-07.html"><a href="ch-07.html#key-points-from-the-lecture-4"><i class="fa fa-check"></i><b>7.1.2</b> Key points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ch-07.html"><a href="ch-07.html#tutorial-5"><i class="fa fa-check"></i><b>7.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ch-07.html"><a href="ch-07.html#model-formulation-using-train"><i class="fa fa-check"></i><b>7.2.1</b> Model formulation using <code>train()</code></a></li>
<li class="chapter" data-level="7.2.2" data-path="ch-07.html"><a href="ch-07.html#model-training"><i class="fa fa-check"></i><b>7.2.2</b> Model training</a></li>
<li class="chapter" data-level="7.2.3" data-path="ch-07.html"><a href="ch-07.html#model-evaluation"><i class="fa fa-check"></i><b>7.2.3</b> Model evaluation</a></li>
<li class="chapter" data-level="7.2.4" data-path="ch-07.html"><a href="ch-07.html#bonus-model-interpretation"><i class="fa fa-check"></i><b>7.2.4</b> Bonus: Model interpretation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ch-07.html"><a href="ch-07.html#exercise-6"><i class="fa fa-check"></i><b>7.3</b> Exercise</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch-07.html"><a href="ch-07.html#setup"><i class="fa fa-check"></i><b>7.3.1</b> Setup</a></li>
<li class="chapter" data-level="7.3.2" data-path="ch-07.html"><a href="ch-07.html#linear-model-1"><i class="fa fa-check"></i><b>7.3.2</b> Linear Model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch-07.html"><a href="ch-07.html#knn"><i class="fa fa-check"></i><b>7.4</b> KNN</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ch-07.html"><a href="ch-07.html#check-data"><i class="fa fa-check"></i><b>7.4.1</b> Check data</a></li>
<li class="chapter" data-level="7.4.2" data-path="ch-07.html"><a href="ch-07.html#training-1"><i class="fa fa-check"></i><b>7.4.2</b> Training</a></li>
<li class="chapter" data-level="7.4.3" data-path="ch-07.html"><a href="ch-07.html#prediction-1"><i class="fa fa-check"></i><b>7.4.3</b> Prediction</a></li>
<li class="chapter" data-level="7.4.4" data-path="ch-07.html"><a href="ch-07.html#sample-hyperparameters"><i class="fa fa-check"></i><b>7.4.4</b> Sample hyperparameters</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="ch-07.html"><a href="ch-07.html#random-forest-1"><i class="fa fa-check"></i><b>7.5</b> Random forest</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="ch-07.html"><a href="ch-07.html#training-2"><i class="fa fa-check"></i><b>7.5.1</b> Training</a></li>
<li class="chapter" data-level="7.5.2" data-path="ch-07.html"><a href="ch-07.html#prediction-2"><i class="fa fa-check"></i><b>7.5.2</b> Prediction</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ch-08.html"><a href="ch-08.html"><i class="fa fa-check"></i><b>8</b> Application 1: Variable selection</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch-08.html"><a href="ch-08.html#introduction-7"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="ch-08.html"><a href="ch-08.html#application"><i class="fa fa-check"></i><b>8.2</b> Application</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ch-08.html"><a href="ch-08.html#warm-up-1-nested-for-loop"><i class="fa fa-check"></i><b>8.2.1</b> Warm-up 1: Nested for-loop</a></li>
<li class="chapter" data-level="8.2.2" data-path="ch-08.html"><a href="ch-08.html#warm-up-2-find-the-best-single-predictor"><i class="fa fa-check"></i><b>8.2.2</b> Warm-up 2: Find the best single predictor</a></li>
<li class="chapter" data-level="8.2.3" data-path="ch-08.html"><a href="ch-08.html#full-stepwise-regression"><i class="fa fa-check"></i><b>8.2.3</b> Full stepwise regression</a></li>
<li class="chapter" data-level="8.2.4" data-path="ch-08.html"><a href="ch-08.html#bonus-stepwise-regression-out-of-the-box"><i class="fa fa-check"></i><b>8.2.4</b> Bonus: Stepwise regression out-of-the-box</a></li>
<li class="chapter" data-level="8.2.5" data-path="ch-08.html"><a href="ch-08.html#bonus-best-subset-selection---not-included-in-application-for-students-too-long"><i class="fa fa-check"></i><b>8.2.5</b> Bonus: Best Subset Selection - Not included in application for students (too long…)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch-09.html"><a href="ch-09.html"><i class="fa fa-check"></i><b>9</b> Supervised Neural Networks I</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch-09.html"><a href="ch-09.html#introduction-8"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="ch-09.html"><a href="ch-09.html#learning-objectives-4"><i class="fa fa-check"></i><b>9.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="9.1.2" data-path="ch-09.html"><a href="ch-09.html#important-points-from-the-lecture-1"><i class="fa fa-check"></i><b>9.1.2</b> Important points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ch-09.html"><a href="ch-09.html#tutorial-6"><i class="fa fa-check"></i><b>9.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ch-09.html"><a href="ch-09.html#set-up"><i class="fa fa-check"></i><b>9.2.1</b> Set-up</a></li>
<li class="chapter" data-level="9.2.2" data-path="ch-09.html"><a href="ch-09.html#keras-for-linear-models"><i class="fa fa-check"></i><b>9.2.2</b> Keras for linear models</a></li>
<li class="chapter" data-level="9.2.3" data-path="ch-09.html"><a href="ch-09.html#tuning-learning-rate"><i class="fa fa-check"></i><b>9.2.3</b> Tuning learning rate</a></li>
<li class="chapter" data-level="9.2.4" data-path="ch-09.html"><a href="ch-09.html#logistic-regression"><i class="fa fa-check"></i><b>9.2.4</b> Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ch-09.html"><a href="ch-09.html#exercise-7"><i class="fa fa-check"></i><b>9.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch-10.html"><a href="ch-10.html"><i class="fa fa-check"></i><b>10</b> Supervised Neural Networks II</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch-10.html"><a href="ch-10.html#introduction-9"><i class="fa fa-check"></i><b>10.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="ch-10.html"><a href="ch-10.html#learning-objectives-5"><i class="fa fa-check"></i><b>10.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="10.1.2" data-path="ch-10.html"><a href="ch-10.html#important-points-from-the-lecture-2"><i class="fa fa-check"></i><b>10.1.2</b> Important points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="ch-10.html"><a href="ch-10.html#tutorial-7"><i class="fa fa-check"></i><b>10.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ch-10.html"><a href="ch-10.html#import-libraries-1"><i class="fa fa-check"></i><b>10.2.1</b> Import libraries</a></li>
<li class="chapter" data-level="10.2.2" data-path="ch-10.html"><a href="ch-10.html#construct-a-toy-dataset"><i class="fa fa-check"></i><b>10.2.2</b> Construct a toy dataset</a></li>
<li class="chapter" data-level="10.2.3" data-path="ch-10.html"><a href="ch-10.html#build-and-train-nn"><i class="fa fa-check"></i><b>10.2.3</b> Build and train NN</a></li>
<li class="chapter" data-level="10.2.4" data-path="ch-10.html"><a href="ch-10.html#model-performance"><i class="fa fa-check"></i><b>10.2.4</b> Model performance</a></li>
<li class="chapter" data-level="10.2.5" data-path="ch-10.html"><a href="ch-10.html#influence-of-nn-architecture"><i class="fa fa-check"></i><b>10.2.5</b> Influence of NN architecture</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ch-10.html"><a href="ch-10.html#exercise-8"><i class="fa fa-check"></i><b>10.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch-11.html"><a href="ch-11.html"><i class="fa fa-check"></i><b>11</b> Application 2: Neural Networks and Hyperparameter Tuning</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch-11.html"><a href="ch-11.html#introduction-10"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="ch-11.html"><a href="ch-11.html#learning-goals"><i class="fa fa-check"></i><b>11.1.1</b> Learning Goals</a></li>
<li class="chapter" data-level="11.1.2" data-path="ch-11.html"><a href="ch-11.html#key-points-from-previous-lectures"><i class="fa fa-check"></i><b>11.1.2</b> Key Points from Previous Lectures</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="ch-11.html"><a href="ch-11.html#application-1"><i class="fa fa-check"></i><b>11.2</b> Application</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="ch-11.html"><a href="ch-11.html#problem-statement"><i class="fa fa-check"></i><b>11.2.1</b> Problem Statement</a></li>
<li class="chapter" data-level="11.2.2" data-path="ch-11.html"><a href="ch-11.html#data-preparation"><i class="fa fa-check"></i><b>11.2.2</b> Data preparation</a></li>
<li class="chapter" data-level="11.2.3" data-path="ch-11.html"><a href="ch-11.html#center-and-scale"><i class="fa fa-check"></i><b>11.2.3</b> Center and scale</a></li>
<li class="chapter" data-level="11.2.4" data-path="ch-11.html"><a href="ch-11.html#building-a-simple-model-with-keras-subtask-1"><i class="fa fa-check"></i><b>11.2.4</b> Building a simple model with keras ( SubTask 1)</a></li>
<li class="chapter" data-level="11.2.5" data-path="ch-11.html"><a href="ch-11.html#cross-validation"><i class="fa fa-check"></i><b>11.2.5</b> Cross validation</a></li>
<li class="chapter" data-level="11.2.6" data-path="ch-11.html"><a href="ch-11.html#parameter-tuning"><i class="fa fa-check"></i><b>11.2.6</b> Parameter Tuning</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch-12.html"><a href="ch-12.html"><i class="fa fa-check"></i><b>12</b> Supervised Deep Learning I</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch-12.html"><a href="ch-12.html#introduction-11"><i class="fa fa-check"></i><b>12.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="ch-12.html"><a href="ch-12.html#learning-objectives-6"><i class="fa fa-check"></i><b>12.1.1</b> Learning objectives</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ch-12.html"><a href="ch-12.html#tutorial-8"><i class="fa fa-check"></i><b>12.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ch-12.html"><a href="ch-12.html#building-blocks-of-cnns"><i class="fa fa-check"></i><b>12.2.1</b> Building Blocks of CNNs</a></li>
<li class="chapter" data-level="12.2.2" data-path="ch-12.html"><a href="ch-12.html#build-the-model"><i class="fa fa-check"></i><b>12.2.2</b> Build the model</a></li>
<li class="chapter" data-level="12.2.3" data-path="ch-12.html"><a href="ch-12.html#compile-and-train-the-model"><i class="fa fa-check"></i><b>12.2.3</b> Compile and train the model</a></li>
<li class="chapter" data-level="12.2.4" data-path="ch-12.html"><a href="ch-12.html#reduce-overfitting"><i class="fa fa-check"></i><b>12.2.4</b> Reduce Overfitting</a></li>
<li class="chapter" data-level="12.2.5" data-path="ch-12.html"><a href="ch-12.html#visualizing-a-cnn"><i class="fa fa-check"></i><b>12.2.5</b> Visualizing a CNN</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ch-12.html"><a href="ch-12.html#exercise-9"><i class="fa fa-check"></i><b>12.3</b> Exercise</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="ch-12.html"><a href="ch-12.html#import-libraries-and-data"><i class="fa fa-check"></i><b>12.3.1</b> Import libraries and data</a></li>
<li class="chapter" data-level="12.3.2" data-path="ch-12.html"><a href="ch-12.html#tasks"><i class="fa fa-check"></i><b>12.3.2</b> Tasks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ch-13.html"><a href="ch-13.html"><i class="fa fa-check"></i><b>13</b> Supervised Deep Learning II - <em>A Scenario of Environmental Systems</em></a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch-13.html"><a href="ch-13.html#introduction-12"><i class="fa fa-check"></i><b>13.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="ch-13.html"><a href="ch-13.html#learning-objectives-7"><i class="fa fa-check"></i><b>13.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="13.1.2" data-path="ch-13.html"><a href="ch-13.html#content-operations"><i class="fa fa-check"></i><b>13.1.2</b> Content &amp; Operations</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="ch-13.html"><a href="ch-13.html#tutorial-9"><i class="fa fa-check"></i><b>13.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ch-13.html"><a href="ch-13.html#description-of-the-modelling-task"><i class="fa fa-check"></i><b>13.2.1</b> Description of the modelling task</a></li>
<li class="chapter" data-level="13.2.2" data-path="ch-13.html"><a href="ch-13.html#goal-of-the-tutorial"><i class="fa fa-check"></i><b>13.2.2</b> Goal of the tutorial</a></li>
<li class="chapter" data-level="13.2.3" data-path="ch-13.html"><a href="ch-13.html#dataset"><i class="fa fa-check"></i><b>13.2.3</b> Dataset</a></li>
<li class="chapter" data-level="13.2.4" data-path="ch-13.html"><a href="ch-13.html#lets-dive-into-the-code"><i class="fa fa-check"></i><b>13.2.4</b> Let’s dive into the code</a></li>
<li class="chapter" data-level="13.2.5" data-path="ch-13.html"><a href="ch-13.html#read-in-the-data"><i class="fa fa-check"></i><b>13.2.5</b> Read in the Data</a></li>
<li class="chapter" data-level="13.2.6" data-path="ch-13.html"><a href="ch-13.html#naive-models-old-world-linear-models"><i class="fa fa-check"></i><b>13.2.6</b> Naive models (Old World): Linear Models</a></li>
<li class="chapter" data-level="13.2.7" data-path="ch-13.html"><a href="ch-13.html#neural-networks-new-world"><i class="fa fa-check"></i><b>13.2.7</b> Neural Networks (New World)</a></li>
<li class="chapter" data-level="13.2.8" data-path="ch-13.html"><a href="ch-13.html#convolutional-neural-network"><i class="fa fa-check"></i><b>13.2.8</b> Convolutional Neural Network</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ch-13.html"><a href="ch-13.html#exercise-10"><i class="fa fa-check"></i><b>13.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Environmental Systems Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch-01" class="section level1" number="1">
<h1><span class="header-section-number">Chapter 1</span> Primers</h1>
<div id="introduction" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Introduction</h2>
<p>This tutorial gets you started to working with <em>R</em> and <em>Git</em> for a data science project. This chapter also includes some basics for programming in R (reading and writing data, types of objects, simple vizualisations). If you’ve had previous experience with R, you may skip this part.</p>
<p>After you’ve gone through the lecture and solved the exercises, you should be able to:</p>
<ul>
<li>Understand the definition of data science.</li>
<li>Identify the different steps of a data science workflow.</li>
<li>Recall a few typical examples of data science applications toward environmental problems.</li>
<li>Explain what a system is and why system understanding is needed in environmental sciences.</li>
<li>Define data, understand the structure of data, and list examples of environmental data.</li>
<li>List sources of environmental data and explain the methodological difference in their collection.</li>
<li>Execute R and load a dataset for data analyses.</li>
<li>Apply basic Git commands for version control.</li>
<li>Plot data analysis outputs and write them on the disk.</li>
</ul>
<div id="key-points-from-the-lecture" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Key Points from the lecture</h3>
<p>The four ‘Vs’ of <em>Big Data</em>:</p>
<ul>
<li>Volume: Data volume is simply the amount of data in a file or database.</li>
<li>Velocity: Data velocity is the lag between time of observation and data ingest for analysis.</li>
<li>Variety: Data variety is the diversity of data in a data collection or problem space.</li>
<li>Veracity: Data veracity is the degree to which data is accurate and precise in comparison with a measured phenomenon</li>
</ul>
<p><em>Open Science</em> is enabled by the <em>FAIR</em> criteria for data use and sharing:</p>
<ul>
<li><strong>F</strong>indable: Easy to find and well documented.</li>
<li><strong>A</strong>ccessible: Long term storage and accessible with standard protocols.</li>
<li><strong>I</strong>nteroperatable: Exchangeable and correctly cited.</li>
<li><strong>R</strong>eusable: Sufficiently documented and clear legal terms.</li>
</ul>
<p>Environmental data is collected from a diversity of methods, including remote sensing, continuous site-scale measurements (e.g., meteorological variables, hydrological variables, ecosystem-atmosphere exchange fluxes of water vapour and CO<sub>2</sub>), episodic observations (e.g., forest inventories, biodiversity assessments), field campaigns, or experiments in the field or under laboratory conditions. Data from these sources come in different shapes and formats. In this course, we will learn to handle this diversity efficiently to answer research questions that you will likely encounter in the future. In many of the exercises, we will focus on data from continuous site scale observations, where meteorological variables are measured in parallel with ecosystem-atmosphere exchange fluxes of water vapour and CO<sub>2</sub>, collected by the eddy covariance technique. In addition, you will learn to tap into large environmental data repositories to complement your site-scale data.</p>
<p>At the end of each chapter, you will find an exercise that you can complete using the <a href="https://datascience.ch/renku/">Renku</a> cloud computing environment and the <a href="https://www.rstudio.com/">RStudio</a> integrated development environment.</p>
</div>
</div>
<div id="tutorial" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Tutorial</h2>
<div id="working-with-rstudio-on-renku" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Working with RStudio on Renku</h3>
<p>Cloud computing is becoming increasingly popular as it allows users to connect to the cloud system at any time from almost anywhere. This allows the bulk of features and files to be stored on a cloud-hosted server rather than on the users own computer.
<a href="https://datascience.ch/renku/">Renku</a> is an open cloud computing platform that aims to make ‘Multidisciplinary Data Science Collaborations’ easier to navigate. It stores the data and code allowing multiple people to work on the same projects and keeps track of the various steps and versions of a project. By keeping track of the changes, there is a history and timeline of each persons contributions and results. Through Renku, its developers hope to make data science more reproducible, reusable and repeatable and hope to encourages and simplify collaborations.</p>
<p>RStudio on Renku is similar to using Rstudio on any laptop or computer, except it is hosted by the platform.
Start by selecting the correct project in Renku.</p>
<p>Then press <em>‘fork’</em> to create a copy of the project, which serves as your personal project that you can modify.</p>
<p><img src="figures/Renku_RStudio_1_Fork1.jpeg" /></p>
<p>Enter the title and namespace of the project and press <em>‘fork’</em> again.</p>
<p><img src="figures/Renku_RStudio_1_Fork2.jpeg" /></p>
<p>This starts forking the project.</p>
<p><img src="figures/Renku_RStudio_1_Fork3.jpeg" /></p>
<p>After the forking you are ready to start working on the project.</p>
<p><img src="figures/Renku_RStudio_1_Fork4.jpeg" /></p>
<p>In the following will work with a fork simply called <em>‘01_primers’</em>.</p>
<p>Once you forked the project, select the tab <em>‘Environments’</em> and click <em>‘New’</em> to start a new interactive environment.
<img src="figures/Renku_RStudio_1_New_Environment.jpg" /></p>
<p>Make sure to set the <em>Default Environment</em> to <code>/rstudio</code>. The other options can be left on the default settings. The box commit will show you when the latest commit was pushed and who authored it.
Press <em>Start environment</em>.
<img src="figures/Renku_RStudio_2_New_Environment.jpg" />
This starts loading the environment and can take a while. Once it is ready (signalised by a green tick within a white circle), click <em>Connect</em>.
<img src="figures/Renku_RStudio_3_New_Environment.jpg" />
An online RStudio interface will open in a new browser tab.
Once RStudio is running, it works as on a laptop or computer. Saving the files will differs when using RStudio on Renku, this will be explained in the section below called <em>Git</em>.</p>
<p>Once your progress has been saved an active environment can be closed by clicking on the <em>three dots</em> next to the connect button back on the Renku page and then selecting <em>Stop</em>. Do this before logging out of and closing Renku.
<img src="figures/Renku_RStudio_4_New_Environment.jpg" /></p>
<!---
Right now your browser should look something like this:
![](./figures/jupyter.png)
As you can see we've highlighted a few functionalities with colors. Jupyter notebooks are made up of a collection of cells. Each cell can be selected individually. In fact, if you click once on this text, a blue ribbon should show up on the left side. This means you've selected the cell where we wrote this text in. If you click twice you can start editing this cell. That's right, you have all the same options we had when putting this document together! Maybe this is a good thing for you as it allows you to add annotations directly in the script, maybe it isn't because you are afraid you might break something. To prevent the latter from happening you best keep your annotations to cells that look like text and do not contain any code. If you've clicked twice on this cell you might wonder how you can get back to the nice layout there was before you've double-clicked: Make sure this cell is selected (blue ribbon) and click on the small arrow we highlighted <span style="color:green">green</span> in the image above. If you hover long enough over that button it should say "run the selected cells and advance". Go on and click this button. Generally, you will want to hit run on every cell that looks like code.

Sometimes when you double-click a cell that looks like text, it will reveal a mix of text and code. This code is usually layout options. Leave it as it is and you should be fine. For now, you've got to know text cells. In jupyter they're called Markdown. There are two more cell formats: Code and Raw. You can switch between them using the panel we've highlighted <span style="color:orange">orange</span>. Usually, there is no need for you to do so. Code we usually use to introduce you to a few new commands. Most cells marked as Code you actually have to run. Raw we tend to use for you to answer small exercises. Most of the time we provide solutions to these exercises that are hidden. You can reveal them by clicking on the three dots indicating that a section is collapsed. You can collapse a section yourself by clicking on the blue ribbon on the left side. Go ahead and do so. Afterward, make this section reappear by clicking the three dots that just appeared.

If you need to add an additional cell you can do so by clicking the +, highlighted black in the image above. On the left we've encircled an entire section <span style="color:red">red</span>. Here you have an overview of all your files. Additionally, you can change the panel to something else. For instance, if you click on the option down left that we've highlighted <span style="color:blue">blue</span> you will be presented with a table of contents. This is very useful if you want to navigate in this file, as it is linked with titles and allows you to jump directly to a section (e.g. look up something from a previous section and go back to where you were).

If at some point in this tutorial you get an error it is likely because you've introduced a mistake further up in this script. Look through the sections you've adapted and find the mistake. Once you've corrected it, go back to where you were, select the cell, navigate to the tab <span style="color:turquoise">"Run"</span> (not the arrow, the word "Run" up left) and chose the option "Run All Above Selected Cell".

The last thing we've marked in the image is <span style="color:purple">*Git*</span>. This is essential to save your work permanently. Most of you have never worked with *Git*. In the beginning, it is a bit fiddly but it is an essential skill in data science, the basics of which you are going to master soon. Pay close attention to the next subchapter!
-->
</div>
<div id="git" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Git</h3>
<p><em>Git</em> is a program for code version control and managing collaborative code development. The basic unit of a Git project is a <em>repository</em>, which usually contains multiple source code files that may be organised in (sub) directories. Git keeps track of the entire history of a repository in steps of <em>commits</em>. A commit is a “bundle” of multiple edits and additions of new files and is specified by the user. Since Git knows the entire history of all the files that have ever been added or removed to and from a repository, it allows you to recover previous versions of files (previous commits) and track changes between them. Git also allows you to have multiple versions of your repository (<em>branches</em>) for parallel developments on the same code base, but we will not use this feature. Since Git stores the entire history, the content of a Git repository should always be kept light. For example, it is advisable to only add code and other (small, &lt;10 MB) plain text files to a repository, but not data, and no other outputs that is created by the code of the repository.</p>
<p>A Git repository exists locally, that is, on your computer. But the power of Git plays out when your local repository has a counterpart in the cloud, for example on <a href="https://github.com">GitHub</a>, or on ETH’s <a href="https://gitlab.ethz.ch">GitLab</a>. Git lets you <em>push</em> (upload) your commits to your repository’s <em>remote</em> copy, and <em>pull</em> (download) changes that have been uploaded by your collaborator(s) or yourself from a different <em>clone</em> (local copy) of your repository.</p>
<div id="git-commands-in-rstudio" class="section level4" number="1.2.2.1">
<h4><span class="header-section-number">1.2.2.1</span> Git commands in RStudio</h4>
<p>Unless Git has been installed on a laptop and connected to RStudio, the Git features in Renkus RStudio will not be visible to a user. We will now introduce you to the main commands you will need to make use of Git.</p>
<p>To save your work you will want to commit it. A <em>commit</em> saves the current version of the file or project you are working on. By continually adding commits you will get a timeline of your project as it develops. All commits are saved to the <em>local</em> repository or environment.</p>
<p>To commit, click one of the two commit button or press <code>Ctr + Alt + M</code>.
<img src="figures/Renku_Git.jpg" /></p>
<p>RStudio will open up a new window, showing changes to the selected file, the history and a box where you can add a commit message. The commit message is a way to explain what has been changed in the file since the last commit.
Under the section <em>Status</em> each file with either have a yellow box with a <code>?</code> for ‘unkown’ files , a blue box containing an <code>M</code> for ‘modified’ or a green box containing an <code>A</code> for ‘added’. Added mean the file is ready to be commited.
The box in the column <em>Staged</em> must be ticked for the file to be committed. Then click <em>Commit</em>.</p>
<p><img src="figures/Renku_Git_Commit_Message.jpg" /></p>
<p>If it worked, a message such as the following will appear:</p>
<p><img src="figures/Renku_Git_Commit_successful.jpg" /></p>
<p>Remember, this file is still only saved to the <em>local</em> repository or environment. RStudio shows the user this with a little message:
<img src="figures/Renku_Git_pre_Push.jpg" /></p>
<p>To upload it to the <em>remote</em> repository, we will need to <em>push</em> it. To do this click either <em>Push Branch</em> or <em>Push</em> to the right of the green arrows facing up. With this command, we upload our changes to the remote Git repository, e.g. on GitHub or GitLab.
<img src="figures/Renku_Git_Push.jpg" /></p>
<p>If the <em>push</em> is successful, the little information saying the branch is ahead will have disappeared and a message such as the following appears.
<img src="figures/Renku_Git_Push_Message.jpg" /></p>
<p><strong>It is good practice to commit and push any changes before you interrupt your work or finish a session.</strong> Else those changes will be lost. Renku has an autosave function in case you forget but it can lead to conflicts when picking up your work again.</p>
<p>Once you start your work again, either stop the environment in which you are working within Renku and open a new one or start the next session the blue arrow in the Git tab that says <code>Pull</code>. As its name suggests, with it we can pull changes in our document from the Git repository. This might seem like an unnecessary step, when you are working alone on the document. However, in projects where you might be working together with a peer and need to make sure you integrate her/his changes as well. If you are working together, make sure, that you do not work on the same document at the same time, which could lead to merge conflicts. If at some point you encounter a merge conflict that Git cannot resolve automatically you will have to do so manually. At the <a href="#Git-denies-pushing-what-can-I-do?">end of this tutorial</a> we show how this is done. However, it is unlikely that you will encounter such a problem in this course, which is why we do not explain it here.</p>
<!---
#### Supplementary: Git denies pushing what can I do?

Most of the time when Git denies you to push changes, it is because of merge conflicts. If you read the error message Git will probably tell you to enter `git pull`. Go ahead and do so. 

 If Git cannot resolve a merge conflict automatically, you will have to do it manually. Here, we show you how it is done.
![](./figures/merge1.png)

Once you have reached this point you will notice that if you close your file and want to reopen it, it will not work. Jupyter will prompt this warning:
![](./figures/merge2.png)

To resolve the problem you have to open the terminal and open your file with an editor:


```r
nano notebooks/01_primers.ipynb
```

This will open your file in an editor. Scroll through the file until you reach a section that is highlighted as a merge conflict (we've marked it <span style="color:red">red</span> for you). Merge conflicts are highlighted with <<<<<<<, ======= and >>>>>>>.

![](./figures/merge3.png)

In the next step, you will have to manually remove the lines you want to remove and keep those you want to maintain. You can also add try to add a new line with the original content.
![](./figures/merge4.png)

Once you have fixed the merge conflict within the editor, type `ctrl O`. It should prompt something like this at the bottom of the editor:

![](./figures/merge6.png)

If the file name is correct, hit `ctrl x`.

Back in the terminal, type `git status`, `git add notebooks/01_primers.ipyn` (or the name of the document where your merge conflict appeared), type again `git status`, make a commit `git commit -m "resolved merge conflict"` and finally `git push`.

![](./figures/merge5.png)

Open your document and see if the conflict has been resolved.  Avoid this if you have not managed to resolve the conflict by yourself or feel intimidated or unsure about resolving a conflict, you can ask a teaching assistant for help.
-->
</div>
</div>
<div id="libraries" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Libraries</h3>
<p>This tutorial uses a set of libraries. Libraries provide a set of functions and/or other objects targeted for specific applications and are not available through <em>base R</em>. To run commands of this tutorial, make sure to install and load all packages on your computer. This can be done by:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="ch-01.html#cb1-1" aria-hidden="true" tabindex="-1"></a>list_pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;tidyverse&quot;</span>)</span>
<span id="cb1-2"><a href="ch-01.html#cb1-2" aria-hidden="true" tabindex="-1"></a>new_pkgs <span class="ot">&lt;-</span> list_pkgs[<span class="sc">!</span>(list_pkgs <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">&quot;Package&quot;</span>])]</span>
<span id="cb1-3"><a href="ch-01.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(new_pkgs) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">install.packages</span>(new_pkgs)</span>
<span id="cb1-4"><a href="ch-01.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>In each chapter of this tutorial, you’ll find a similar statement to specify which package the respective chapter’s tutorial will use and to install them if not available.</p>
</div>
<div id="r-scripts" class="section level3" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> R scripts</h3>
<p>A single statement can be entered in the R console. For example, to calculate the mean of 1, 2, and 3, we enter:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="ch-01.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>))</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>The output of a statement can be saved as a new <em>object</em>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="ch-01.html#cb4-1" aria-hidden="true" tabindex="-1"></a>my_new_object <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>))</span></code></pre></div>
<p>The value of an object can be accessed or printed by referring to its name:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="ch-01.html#cb5-1" aria-hidden="true" tabindex="-1"></a>my_new_object</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>You will learn more about different types of objects in R further below. The set of objects defined during an R session are referred to as the <em>environment</em>.</p>
<p>Usually, multiple statements are needed to get, e.g., from reading data into R to final numbers and figures that make up a further analysis. Together, these multiple statments constitute a <em>workflow</em>. It is essential that all workflows that underlie results of publications are <em>reproducible</em>.</p>
<p>After closing an existing R session (e.g. after quitting RStudio), the environment defined by the user during that session, will not be saved automatically and will be lost. To make a workflow reproducible, the sequence of statements that you needed to carry out your analysis and produce outputs can be saved as an R <em>script</em>. Instead of saving the environment, we should save the steps (i.e. the script) to reproduce the same environment - starting from reading in the (raw) data. This will be the objective of an exercise at the end of this session.</p>
<p>An R script is basically a text file, named with the suffix <code>.R</code> to indicate that it is executable by R. Executing the script is running each statement, line-by-line, starting from the top, and can be done in R by:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="ch-01.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;my_r_script.R&quot;</span>)</span></code></pre></div>
<p>You can find more useful information about scripts and workflows in <a href="https://r4ds.had.co.nz/workflow-scripts.html">R for Data Science</a> <span class="citation">(<a href="#ref-Wickham2017R" role="doc-biblioref">Hadley Wickham and Grolemund 2017</a>)</span>.</p>
<p>We should always strive to write nice scripts and good code. Good code is clean, readable, consistent, and extensible (easily modified or adapted). To achieve this, here are a few points to consider - inspired by <a href="https://www.r-bloggers.com/r-code-best-practices/">best practices for coding</a> and by the <a href="https://style.tidyverse.org/">Tidyverse style guide</a> <span class="citation">(<a href="#ref-wickham_welcome_nodate" role="doc-biblioref">Hadley Wickham, n.d.</a>)</span>.</p>
<div id="variable-naming" class="section level4" number="1.2.4.1">
<h4><span class="header-section-number">1.2.4.1</span> Variable naming</h4>
<p>It is preferable to use concise and descriptive variable names. Different variable naming styles are being used. In this course, we use lowercase letters, and underscores (<code>_</code>) to separate words within a name (<code>_</code>). Avoid (<code>.</code>) as they are reserved for S3 objects (base R). Also, you should avoid naming your objects with names of common functions and variables since your re-definition will mask already defined object names.</p>
<p>For example, <code>df_daily</code> is a data frame with data at a daily resolution. Or <code>clean_daily</code> is a function that cleans daily data. Note that a verb is used as a name for a function and an underscore (<code>_</code>) is used to separate words.</p>
<p>It is also recommendable, to avoid variable names consisting of only one character. This makes it practically impossible to search for that variable.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="ch-01.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Good</span></span>
<span id="cb8-2"><a href="ch-01.html#cb8-2" aria-hidden="true" tabindex="-1"></a>day_01</span>
<span id="cb8-3"><a href="ch-01.html#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="ch-01.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Bad</span></span>
<span id="cb8-5"><a href="ch-01.html#cb8-5" aria-hidden="true" tabindex="-1"></a>DayOne</span>
<span id="cb8-6"><a href="ch-01.html#cb8-6" aria-hidden="true" tabindex="-1"></a>day.one</span>
<span id="cb8-7"><a href="ch-01.html#cb8-7" aria-hidden="true" tabindex="-1"></a>first_day_of_the_month</span>
<span id="cb8-8"><a href="ch-01.html#cb8-8" aria-hidden="true" tabindex="-1"></a>djm1</span>
<span id="cb8-9"><a href="ch-01.html#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="ch-01.html#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Very bad</span></span>
<span id="cb8-11"><a href="ch-01.html#cb8-11" aria-hidden="true" tabindex="-1"></a>mean <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sum</span>(x)<span class="sc">/</span><span class="fu">length</span>(x) <span class="co"># mean() itself is already a function</span></span>
<span id="cb8-12"><a href="ch-01.html#cb8-12" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="cn">FALSE</span> <span class="co"># T is an abbreviation of TRUE</span></span>
<span id="cb8-13"><a href="ch-01.html#cb8-13" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># c() is used to create a vector (example &lt;- c(1, 2, 3))</span></span></code></pre></div>
</div>
<div id="comments" class="section level4" number="1.2.4.2">
<h4><span class="header-section-number">1.2.4.2</span> Comments</h4>
<p>Adding comments in the code helps to explain exactly what the code is doing and why. This makes it easy to understand and modify the code, and can be key when debugging. In R source files, comments are prefixed with a <code>#</code>, which means that all what is right of the <code>#</code> is not interpreted by R. Avoid obsolete comments like</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="ch-01.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## take the mean </span></span>
<span id="cb9-2"><a href="ch-01.html#cb9-2" aria-hidden="true" tabindex="-1"></a>myvar_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(myvar)</span></code></pre></div>
</div>
<div id="add-spaces-and-breaks" class="section level4" number="1.2.4.3">
<h4><span class="header-section-number">1.2.4.3</span> Add spaces and breaks</h4>
<p>Adding enough white spaces and line breakes in the right locations greatly helps the legibility of any code. Cramping it up too much leads to an unintelligible sequence of characters and it will not be clear what parts go together (operators, variable names, brackets). Therefore, consider the following points:</p>
<ul>
<li>Use spaces around operators (<code>=</code>, <code>+</code>, <code>-</code>, <code>&lt;-</code>, <code>&gt;</code>, etc.).</li>
<li>Use <code>&lt;-</code>, not <code>=</code>, for allocating a value to a variable.</li>
<li>An opening curly bracket (<code>{</code>) should be followed by a line break and never stand alone on a line. A closing curly bracket (<code>}</code>) should stand alone on a line unless followed by <code>else</code>.</li>
<li>Code inside curly brackets should be <em>indented</em> (recommended: two white spaces at the beginning of each line for each indentation level - don’t use tabs).</li>
</ul>
<p>For example, well written code looks like this:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="ch-01.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (temp <span class="sc">&gt;</span> <span class="fl">5.0</span>){</span>
<span id="cb10-2"><a href="ch-01.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  growth_temp <span class="ot">&lt;-</span> growth_temp <span class="sc">+</span> temp  </span>
<span id="cb10-3"><a href="ch-01.html#cb10-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="structure-your-script" class="section level4" number="1.2.4.4">
<h4><span class="header-section-number">1.2.4.4</span> Structure your script</h4>
<p>At the beginning of each file add a <strong>header</strong> as a fully commented text section, describing what the code contains, and how it fits into the larger analysis framework.</p>
<p>Note that Git stores all meta information about the file, including who created it, who modified it and when. This information should not be added to the header. Then, load all libraries needed within the script. Then, source any scripts and load data, and only then, start with the sequence of statements. To visually separate parts, break up your code using, commented lines.</p>
<p>For example, a script could look like this:</p>
<!-- For this chapter, we will mostly work with functions already integrated into R directly, also known as *base R*. Additionally, you will work with functions from the [*tidyverse*](https://www.tidyverse.org/). *tidyverse* is a collection of packages specifically designed for writing efficient data science workflows. Code written for the tidyverse follows its own "dialect" within the R langague. It will be introduced in \@ref(ch-02). -->
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="ch-01.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">##////////////////////////////////////////</span></span>
<span id="cb11-2"><a href="ch-01.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Demonstrating script structure</span></span>
<span id="cb11-3"><a href="ch-01.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="do">##---------------------------------------</span></span>
<span id="cb11-4"><a href="ch-01.html#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb11-5"><a href="ch-01.html#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/my_functions.R&quot;</span>)</span>
<span id="cb11-6"><a href="ch-01.html#cb11-6" aria-hidden="true" tabindex="-1"></a>my_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/my_df.csv&quot;</span>)</span>
<span id="cb11-7"><a href="ch-01.html#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="ch-01.html#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="do">##---------------------------------------</span></span>
<span id="cb11-9"><a href="ch-01.html#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Main part</span></span>
<span id="cb11-10"><a href="ch-01.html#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="do">##---------------------------------------</span></span>
<span id="cb11-11"><a href="ch-01.html#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="do">## convert units</span></span>
<span id="cb11-12"><a href="ch-01.html#cb11-12" aria-hidden="true" tabindex="-1"></a>my_df<span class="sc">$</span>temp <span class="ot">&lt;-</span> my_df<span class="sc">$</span>temp <span class="sc">+</span> <span class="fl">273.15</span>  <span class="co"># deg C -&gt; K</span></span>
<span id="cb11-13"><a href="ch-01.html#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="ch-01.html#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="do">##---------------------------------------</span></span>
<span id="cb11-15"><a href="ch-01.html#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Writing output</span></span>
<span id="cb11-16"><a href="ch-01.html#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="do">##---------------------------------------</span></span>
<span id="cb11-17"><a href="ch-01.html#cb11-17" aria-hidden="true" tabindex="-1"></a>filn <span class="ot">&lt;-</span> <span class="st">&quot;data/my_df_kelvin.csv&quot;</span></span>
<span id="cb11-18"><a href="ch-01.html#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Writing file&quot;</span>, filn, <span class="st">&quot;...&quot;</span>))</span>
<span id="cb11-19"><a href="ch-01.html#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(my_df, filn)</span></code></pre></div>
</div>
</div>
<div id="rmarkdown" class="section level3" number="1.2.5">
<h3><span class="header-section-number">1.2.5</span> RMarkdown</h3>
<p><a href="https://rmarkdown.rstudio.com/">RMarkdown</a> files are an enhanced version of scripts. They combine formatted text and executable code chunks. They can either be compiled (<em>knitted</em>) into an HTML or PDF output, where code chunks are executed upon compilation and visualization outputs are directly placed into the output, or they can be run like a script entirely or each code chunk separately. When run (not knitted), objects defined by the executed code are available in the environment.</p>
<p>Text can be formatted using the <a href="https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html">Markdown syntax</a>. For example, a top-level section title is specified by <code>#</code> and a title of a section one level lower by <code>##</code>.</p>
<p>RMarkdown documents are also the basis of this book, with each chapter written in a separate RMarkdown file. This lets you use the book in an interactive fashion.</p>
<p>When opened in RStudio, you can knit an RMarkdown document by clicking the “Knit” button:</p>
<p><img src="figures/knit.png" /></p>
<p>You can run all chunks by selecting clicking “Run All” from the drop-down menu available under “Run”:</p>
<p><img src="figures/run_rmarkdown.png" /></p>
<p>Individual chunks can be executed by clicking the green right-pointing triangle in the upper right corner of the chunk:</p>
<p><img src="figures/rmarkdown_chunk.png" /></p>
</div>
<div id="functions" class="section level3" number="1.2.6">
<h3><span class="header-section-number">1.2.6</span> Functions</h3>
<p>Often, analyses require many steps and your scripts may get excessively long. Over 2000 lines of code in one file are hard to digest. An important aspect of good programming is to avoid duplicating code. If the same sequence of multiple statements or functions are to be applied repeatedly to different objects, then it is usually advisable to bundle them into a new <em>function</em> and apply this single function to each object. This also has the advantage that if some requirement or variable name changes, it has to be edited only in one place. A further advantage of writing functions is that you can give the function an intuitively understandable name, so that your code reads like a sequence of orders given to a human,</p>
<p>For example, the following code, converting temperature values provided in Fahrenheit to degrees Celsius, could be made into a function.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="ch-01.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">## NOT ADVISABLE</span></span>
<span id="cb12-2"><a href="ch-01.html#cb12-2" aria-hidden="true" tabindex="-1"></a>temp_soil <span class="ot">&lt;-</span> (temp_soil <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">9</span></span>
<span id="cb12-3"><a href="ch-01.html#cb12-3" aria-hidden="true" tabindex="-1"></a>temp_air  <span class="ot">&lt;-</span> (temp_air  <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">9</span></span>
<span id="cb12-4"><a href="ch-01.html#cb12-4" aria-hidden="true" tabindex="-1"></a>temp_leaf <span class="ot">&lt;-</span> (temp_leaf <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">9</span></span></code></pre></div>
<p>The same, but using our own function <code>convert_fahrenheit_to_celsius()</code>:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="ch-01.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ADVISABLE</span></span>
<span id="cb13-2"><a href="ch-01.html#cb13-2" aria-hidden="true" tabindex="-1"></a>convert_fahrenheit_to_celsius <span class="ot">&lt;-</span> <span class="cf">function</span>(temp_f){</span>
<span id="cb13-3"><a href="ch-01.html#cb13-3" aria-hidden="true" tabindex="-1"></a>  temp_c <span class="ot">&lt;-</span> (temp_f <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">9</span></span>
<span id="cb13-4"><a href="ch-01.html#cb13-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-5"><a href="ch-01.html#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="ch-01.html#cb13-6" aria-hidden="true" tabindex="-1"></a>temp_soil <span class="ot">&lt;-</span> <span class="fu">convert_fahrenheit_to_celsius</span>(temp_soil)</span>
<span id="cb13-7"><a href="ch-01.html#cb13-7" aria-hidden="true" tabindex="-1"></a>temp_air  <span class="ot">&lt;-</span> <span class="fu">convert_fahrenheit_to_celsius</span>(temp_air)</span>
<span id="cb13-8"><a href="ch-01.html#cb13-8" aria-hidden="true" tabindex="-1"></a>temp_leaf <span class="ot">&lt;-</span> <span class="fu">convert_fahrenheit_to_celsius</span>(temp_leaf)</span></code></pre></div>
<p>Functions (particularly long ones) can be written to separate source file (text files containing executable code).</p>
</div>
<div id="tidy-data" class="section level3" number="1.2.7">
<h3><span class="header-section-number">1.2.7</span> Tidy data</h3>
<p>Similarly as code, data can be tidy or not. Even if a data file (for example an Excel spreadsheet) may look visually appealing, its structure determines how easy it is to perform further processing steps and calculations on it. The concept of <a href="https://r4ds.had.co.nz/tidy-data.html"><strong>tidy data</strong></a> <span class="citation">(<a href="#ref-Wickham2017R" role="doc-biblioref">Hadley Wickham and Grolemund 2017</a>)</span> can be defined by the following rules <span class="citation">(<a href="#ref-Wickham2014" role="doc-biblioref">Hadley Wickham 2014</a>)</span> (<a href="http://www.jstatsoft.org/v59/i10/paper" class="uri">http://www.jstatsoft.org/v59/i10/paper</a>):</p>
<ol style="list-style-type: decimal">
<li>Each column is a variable.</li>
<li>Each row is an observation.</li>
<li>Each value has its own cell.</li>
</ol>
<p><embed src="https://r4ds.had.co.nz/tidy-data.html" /> <span class="citation">(<a href="#ref-Wickham2017R" role="doc-biblioref">Hadley Wickham and Grolemund 2017</a>)</span>
<img src="figures/tidy_data.png" /></p>
<p>Having data in a tidy format greatly facilitates all steps of data wrangling. When creating a spreadsheet, remember to design it in a tidy structure from the beginning. For example, put variable names in the first row, avoid merged cells, create separate tabs for each table, and make it <em>machine readable</em>. For example, avoid entries like “&gt;10 g m-2 s-1”. A cell should only contain one value. Here, this is “10”. Create a separate column for units, and enter the information there as a character string (“g m-2 s-1”). The information conveyed by the greater-than (“&gt;”) symbol should be encoded in a machine readable manner. This may not be straight forward. A possibility could be to add a column “is_minimum” and add the entry “TRUE” in the respective cell.</p>
<p>The concept of tidy data can even be taken further by understanding a “value” as any object type, e.g. a list. This leads to a list “nested” within a data frame. You will learn more about this in Chapter <a href="ch-02.html#ch-02">2</a>.</p>
<p>In the exercises at the end of this chapter, you will transform a visually appealing but poorly formatted data file into tidy and machine readable data.</p>
</div>
<div id="r-projects" class="section level3" number="1.2.8">
<h3><span class="header-section-number">1.2.8</span> R projects</h3>
<p>Using R <em>projects</em> in combination with Git is the essence of efficient workspace management in R. All files that belong together are organised within one directory. This can be regarded as the <em>project directory</em> and is typically congruent with what belongs to the respective Git repository. When working in RStudio, you can create a new R project or switch to an existing project by navigating the drop-down menu in the top right corner of RStudio.</p>
<p><img src="figures/new_project.png" /></p>
<p>When starting a new project, a file <code>&lt;project_name.Rproj&gt;</code> is created. It sits in the project directory and stores information about your last session (settings, open files, etc.) and optionally (not recommended) the <em>environment</em> of that session. The use of R projects also automatically enables useful features in RStudio for easy package, website, or book building and lets you manage Git for the repository corresponding to the project.</p>
<p>It’s advisable to write files, created by the code of your project, to sub-directories within the project directory. For example, keep source files where R functions are defined in <code>./R</code> (where <code>.</code> refers to the project directory), data files in <code>./data</code> and visualizations in <code>./fig</code>. To read and write from/to files should be done using relative paths:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="ch-01.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;./R/my_r_script.R&quot;</span>)</span></code></pre></div>
<p>or equivalently:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="ch-01.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/my_r_script.R&quot;</span>)</span></code></pre></div>
<p>A project directory should only contain code and outputs that belong to this one project. Stuff that may belong to multiple projects should be kept somewhere else. For example, keep original data (e.g., the raw data files that you created when collecting the data in the field, or data files you downloaded from the web) outside the project directory.</p>
<p>It is advisable to create a separate data directory outside (e.g., <code>~/data/</code>) that holds all the original data you ever downloaded, or obtained from peers, or gathered yourself. Within such a data directory, you can put files from different sources into separate sub-directories and add a description file (e.g., <code>~/data/some_data_source/README</code>) defining who, from where and when the data was obtained and defining data use policy.</p>
</div>
<div id="working-with-data-frames" class="section level3" number="1.2.9">
<h3><span class="header-section-number">1.2.9</span> Working with data frames</h3>
<p>Now, let’s get our hands on actual data for demonstrating how data is read and written. As most of the code displayed in this book, the code chunks below are executable. You can try it out by opening the the book’s R project in RStudio.</p>
<p>We are going to work with data from ecosystem flux measurements, taken by the eddy covariance technique, and provided as part of the FLUXNET2015 dataset <span class="citation">(<a href="#ref-Pastorello2020" role="doc-biblioref">Pastorello et al. 2020</a>)</span> <a href="https://www.nature.com/articles/s41597-020-0534-3">see</a>. The data we’re using below comes from a flux tower near Zürich (<a href="https://gl.ethz.ch/research/bage/fluxnet-ch.html">CH-Lae</a>, located on the Laegern mountain between Regensberg and Baden and run by our colleagues here at ETH).</p>
<p>The data is stored as a Comma Separated Values file (<code>.csv</code>). This is a plain-text, and therefore a non-proprietary format. To follow the FAIR data principles, distribute your data in a format that is non-proprietary and readable across platforms and applications. For example, avoid distributing your data as an <em>Excel</em> spreadsheat (<code>.xlsx</code>), or a <em>Matlab</em> data object (<code>.mat</code>), or an R data object (<code>.RData</code>, or <code>.rds</code>).</p>
<div id="reading-data" class="section level4" number="1.2.9.1">
<h4><span class="header-section-number">1.2.9.1</span> Reading data</h4>
<p>To import the data into the R workspace (environment), we use the function <code>read_csv()</code> from the tidyverse package. In other R code, you will also encounter the base R <code>read.csv()</code> function. However, <code>read_csv()</code> is much faster and reads data into a tidyverse-data frame (a <em>tibble</em>) which has some useful additional characteristics, on top of a common R data frame. To tell the function where the data is located, pass the data’s path as an argument. You can either use an <em>absolute path</em>, starting from <code>C:/</code> on a Windows computer or <code>~/</code> on a Mac or Linux. Or, alternatively, you can provide a <em>relative path</em>, where <code>./</code> points to the present working directory and <code>../</code> is one level up, or <code>../../</code> is two levels up, etc.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="ch-01.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use a relative path to read the data</span></span>
<span id="cb16-2"><a href="ch-01.html#cb16-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;./data/FLX_CH-Lae_FLUXNET2015_FULLSET_DD_2004-2014_1-3.csv&quot;</span>)</span>
<span id="cb16-3"><a href="ch-01.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df) <span class="co"># to print an overview of the data frame</span></span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 334
##    TIMESTAMP TA_F_MDS TA_F_MDS_QC TA_F_MDS_NIGHT TA_F_MDS_NIGHT_SD
##        &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;             &lt;dbl&gt;
##  1  20040101    -9999       -9999          -9999             -9999
##  2  20040102    -9999       -9999          -9999             -9999
##  3  20040103    -9999       -9999          -9999             -9999
##  4  20040104    -9999       -9999          -9999             -9999
##  5  20040105    -9999       -9999          -9999             -9999
##  6  20040106    -9999       -9999          -9999             -9999
##  7  20040107    -9999       -9999          -9999             -9999
##  8  20040108    -9999       -9999          -9999             -9999
##  9  20040109    -9999       -9999          -9999             -9999
## 10  20040110    -9999       -9999          -9999             -9999
## # … with 4,008 more rows, and 329 more variables: TA_F_MDS_NIGHT_QC &lt;dbl&gt;,
## #   TA_F_MDS_DAY &lt;dbl&gt;, TA_F_MDS_DAY_SD &lt;dbl&gt;, TA_F_MDS_DAY_QC &lt;dbl&gt;,
## #   TA_ERA &lt;dbl&gt;, TA_ERA_NIGHT &lt;dbl&gt;, TA_ERA_NIGHT_SD &lt;dbl&gt;, TA_ERA_DAY &lt;dbl&gt;,
## #   TA_ERA_DAY_SD &lt;dbl&gt;, TA_F &lt;dbl&gt;, TA_F_QC &lt;dbl&gt;, TA_F_NIGHT &lt;dbl&gt;,
## #   TA_F_NIGHT_SD &lt;dbl&gt;, TA_F_NIGHT_QC &lt;dbl&gt;, TA_F_DAY &lt;dbl&gt;,
## #   TA_F_DAY_SD &lt;dbl&gt;, TA_F_DAY_QC &lt;dbl&gt;, SW_IN_POT &lt;dbl&gt;, SW_IN_F_MDS &lt;dbl&gt;,
## #   SW_IN_F_MDS_QC &lt;dbl&gt;, SW_IN_ERA &lt;dbl&gt;, SW_IN_F &lt;dbl&gt;, SW_IN_F_QC &lt;dbl&gt;, …</code></pre>
<p>The file is automatically machine-readable because we have:</p>
<ul>
<li>Only one header row, containing the column (variable) names.</li>
<li>Variables organised by columns, and observations by rows.</li>
<li>Each column consists of a single data type (e.g., character, numeric, logical; see below for more info) - Here, all columns are interpreted as numeric (`<dbl>’).</li>
<li>One value per cell.</li>
<li>No merged cells.</li>
</ul>
<p>In short, the data frame is tidy.</p>
<p>To understand the sort of object we work with, i.e. the <em>class</em>, we can do:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="ch-01.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span></code></pre></div>
<pre><code>## [1] &quot;spec_tbl_df&quot; &quot;tbl_df&quot;      &quot;tbl&quot;         &quot;data.frame&quot;</code></pre>
<p>Fundamentally, <code>df</code> is a <code>data.frame</code>. In addition, it is also of some other classes (<code>spec_tbl_df","tbl_df", "tbl"</code>) which gives it additional features.</p>
</div>
<div id="understanding-the-data-structure" class="section level4" number="1.2.9.2">
<h4><span class="header-section-number">1.2.9.2</span> Understanding the data structure</h4>
<p>There are several base R functions to help you understand the structure of a data frame. Here is a non-exhaustive list of of them:</p>
<ul>
<li>Size
<ul>
<li><code>dim()</code> - Returns the size of the dimensions of an object (here: number of rows and columns).</li>
<li><code>nrow()</code> - Returns the number of rows of an object.</li>
<li><code>ncol()</code> - Returns the number of columns of an object.</li>
</ul></li>
<li>Content
<ul>
<li><code>head()</code> - Returns the first 6 rows.</li>
<li><code>tail()</code> - Returns the last 6 rows.</li>
<li><code>View()</code> - look at the entire data set in the form of a table (It is not supported by the Jupyter environment. In RStudio however, it works).</li>
</ul></li>
<li>Names
<ul>
<li><code>names()</code> - Returns the column names (for <code>data.frame</code>-objects it is synonymous to <code>colnames()</code>).</li>
<li><code>rownames()</code> - Returns the row names.</li>
</ul></li>
<li>Summary
<ul>
<li><code>class()</code> - Returns the class of an object.</li>
<li><code>str()</code> - Returns the structure of an object and information about the class, length and content of each column.</li>
<li><code>summary()</code> - Returns generic statistics information, depending on the class of the object.</li>
</ul></li>
</ul>
<p>For example, the data frame <code>df</code> has 4018 rows and 334 columns:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="ch-01.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df)</span></code></pre></div>
<pre><code>## [1] 4018  334</code></pre>
<p>A description of standardized FLUXNET data variables is available <a href="https://fluxnet.org/data/aboutdata/data-variables/">here</a>. A selection of available variables that we will use in subsequent chapters are:</p>
<ul>
<li><code>GPP</code> (gC m<span class="math inline">\(^{−2}\)</span> s<span class="math inline">\(^{-1}\)</span>): Gross primary production</li>
<li><code>WS</code> (m s<span class="math inline">\(^{-1}\)</span>): horizontal wind speed</li>
<li><code>USTAR</code> (m s<span class="math inline">\(^{-1}\)</span>): friction velocity</li>
<li><code>TA</code> (deg C): air temperature</li>
<li><code>RH</code> (%): relative humidity (range 0–100%)</li>
<li><code>PA</code> (kPa): atmospheric pressure</li>
<li><code>G</code> (W m<span class="math inline">\(^{−2}\)</span>): ground heat flux, not mandatory, but needed for the energy balance closure calculations</li>
<li><code>NETRAD</code> (W m<span class="math inline">\(^{−2}\)</span>): net radiation, not mandatory, but needed for the energy balance closure calculations</li>
<li><code>SW_IN</code> (W m<span class="math inline">\(^{−2}\)</span>): incoming shortwave radiation</li>
<li><code>SW_IN_POT</code> (W m<span class="math inline">\(^−2\)</span>): potential incoming shortwave radiation (top of atmosphere theoretical maximum radiation)</li>
<li><code>PPFD_IN</code> (<span class="math inline">\(\mu\)</span>mol photons m<span class="math inline">\(^{−2}\)</span> s<span class="math inline">\(^{-1}\)</span>): incoming photosynthetic photon flux density</li>
<li><code>P</code> (mm): precipitation total of each 30 or 60 minute period</li>
<li><code>LW_IN</code> (W m<span class="math inline">\(^{−2}\)</span>): incoming (down-welling) longwave radiation</li>
<li><code>SWC</code> (%): soil water content (volumetric), range 0–100%</li>
<li><code>TS</code> (deg C): soil temperature</li>
<li><code>CO2</code> (<span class="math inline">\(\mu\)</span>molCO<sub>2</sub> mol<span class="math inline">\(^{-1}\)</span>): Carbon Dioxide (CO<span class="math inline">\(_2\)</span>) mole fraction in moist air</li>
</ul>
</div>
<div id="selecting-data-and-entering-the-tidyverse" class="section level4" number="1.2.9.3">
<h4><span class="header-section-number">1.2.9.3</span> Selecting data and entering the tidyverse</h4>
<p><code>df</code> is a data frame. This is similar to a matrix and has two dimensions (rows and columns). If we want to extract specific data from it, we specify the indices, i.e. the “coordinates”, of the data. For two-dimensional objects (data frames, matrices), the first index refers to rows and the second to columns. For example, to refer to the element on the third row in the first column, we write:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="ch-01.html#cb22-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">3</span>,<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   TIMESTAMP
##       &lt;dbl&gt;
## 1  20040103</code></pre>
<p>Reducing a data frame (tibble) to only the first columns can be done by:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="ch-01.html#cb24-1" aria-hidden="true" tabindex="-1"></a>df[, <span class="dv">1</span>]</span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 1
##    TIMESTAMP
##        &lt;dbl&gt;
##  1  20040101
##  2  20040102
##  3  20040103
##  4  20040104
##  5  20040105
##  6  20040106
##  7  20040107
##  8  20040108
##  9  20040109
## 10  20040110
## # … with 4,008 more rows</code></pre>
<p>The method of selecting parts of a data frame by index is quite flexible. For example, we may require the information in the third column for the first three rows. Putting a colon between two numbers, e.g. <code>[1:3,]</code>, indicates we want to select the rows numbers starting at the first and ending with the second number. So here <code>[1:3,]</code> will give us rows one, two and three.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="ch-01.html#cb26-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">3</span>] <span class="co"># reduces the data frame (tibble) to its first three rows and the 3rd column</span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 1
##   TA_F_MDS_QC
##         &lt;dbl&gt;
## 1       -9999
## 2       -9999
## 3       -9999</code></pre>
<p>To reduce the data frame (tibble) to several columns, the function <code>c()</code> is used. <code>c()</code> stands for concatenate, which means to link together in a series or chain. This outputs the data frame (tibble) reduced to the selected row or column numbers inside <code>c()</code>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="ch-01.html#cb28-1" aria-hidden="true" tabindex="-1"></a>df[, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">7</span>)]</span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 3
##    TIMESTAMP TA_F_MDS_NIGHT TA_F_MDS_DAY
##        &lt;dbl&gt;          &lt;dbl&gt;        &lt;dbl&gt;
##  1  20040101          -9999        -9999
##  2  20040102          -9999        -9999
##  3  20040103          -9999        -9999
##  4  20040104          -9999        -9999
##  5  20040105          -9999        -9999
##  6  20040106          -9999        -9999
##  7  20040107          -9999        -9999
##  8  20040108          -9999        -9999
##  9  20040109          -9999        -9999
## 10  20040110          -9999        -9999
## # … with 4,008 more rows</code></pre>
<p>Another method is to select the columns by column names, i.e. giving as input a string vector with the name of each column we want to select (again, this is Base R notation). This is especially useful if the columns we want to select are not contiguous. For example:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="ch-01.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecting data by name in base R  ================================</span></span>
<span id="cb30-2"><a href="ch-01.html#cb30-2" aria-hidden="true" tabindex="-1"></a>df[,<span class="fu">c</span>(<span class="st">&quot;TIMESTAMP&quot;</span>, <span class="st">&quot;TA_F_MDS&quot;</span>, <span class="st">&quot;TA_F_MDS_QC&quot;</span>)]</span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 3
##    TIMESTAMP TA_F_MDS TA_F_MDS_QC
##        &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
##  1  20040101    -9999       -9999
##  2  20040102    -9999       -9999
##  3  20040103    -9999       -9999
##  4  20040104    -9999       -9999
##  5  20040105    -9999       -9999
##  6  20040106    -9999       -9999
##  7  20040107    -9999       -9999
##  8  20040108    -9999       -9999
##  9  20040109    -9999       -9999
## 10  20040110    -9999       -9999
## # … with 4,008 more rows</code></pre>
<p>In Chapter <a href="ch-02.html#ch-02">2</a> of this tutorial tutorial, we will use the <a href="https://www.tidyverse.org/">tidyverse</a>, which is a set of R packages designed for working with tidy data and writing code in such a way as to emphasize and better understand the “workflow aspect” of it. A code chunk which does the same as above, but is written for the tidyverse can read as follows.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="ch-01.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df, <span class="dv">1</span>) <span class="co"># reduces the data frame (tibble) to its first column</span></span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 1
##    TIMESTAMP
##        &lt;dbl&gt;
##  1  20040101
##  2  20040102
##  3  20040103
##  4  20040104
##  5  20040105
##  6  20040106
##  7  20040107
##  8  20040108
##  9  20040109
## 10  20040110
## # … with 4,008 more rows</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="ch-01.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df, TIMESTAMP, TA_F_MDS, TA_F_MDS_QC)  <span class="co"># reduces the data frame to columns specified by names</span></span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 3
##    TIMESTAMP TA_F_MDS TA_F_MDS_QC
##        &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
##  1  20040101    -9999       -9999
##  2  20040102    -9999       -9999
##  3  20040103    -9999       -9999
##  4  20040104    -9999       -9999
##  5  20040105    -9999       -9999
##  6  20040106    -9999       -9999
##  7  20040107    -9999       -9999
##  8  20040108    -9999       -9999
##  9  20040109    -9999       -9999
## 10  20040110    -9999       -9999
## # … with 4,008 more rows</code></pre>
<p>As a further shortcut in tidyverse, we can use the pipe <code>%&gt;%</code> operator. The data frame is still reduced to its first column:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="ch-01.html#cb36-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4,018 × 1
##    TIMESTAMP
##        &lt;dbl&gt;
##  1  20040101
##  2  20040102
##  3  20040103
##  4  20040104
##  5  20040105
##  6  20040106
##  7  20040107
##  8  20040108
##  9  20040109
## 10  20040110
## # … with 4,008 more rows</code></pre>
<p>We <em>pipe</em> the object <code>df</code> into the <code>select()</code> function with argument <code>1</code>. Note that the <code>%&gt;%</code> operator can be used on any function. It tells the function to interpret what’s coming from the left of <code>%&gt;%</code> as its <strong>first</strong> argument.</p>
<p>For the remainder of the tutorial several variables will be required. The methods of variable selection demonstrated above will be utilised below to get the desired variables.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="ch-01.html#cb38-1" aria-hidden="true" tabindex="-1"></a>df_small <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb38-2"><a href="ch-01.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TIMESTAMP, TA_F, PPFD_IN)</span></code></pre></div>
<p>Note: In the code above, an indentation was used to highlight which parts go together and make the code easy to understand. Indentations and line breaks take no effect in R per se (unlike in other programming languages, e.g., Matlab, Python), but help to make the code easier to read.</p>
</div>
<div id="renaming" class="section level4" number="1.2.9.4">
<h4><span class="header-section-number">1.2.9.4</span> Renaming</h4>
<p>TIMESTAMP_START, TA_F and PPFD_IN as variable names may be hard to remember and in this section you will have to type them a lot. Therefore we change their names to something more intelligle.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="ch-01.html#cb39-1" aria-hidden="true" tabindex="-1"></a>df_small <span class="ot">&lt;-</span> df_small <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="ch-01.html#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">time =</span> TIMESTAMP, <span class="at">temp =</span> TA_F, <span class="at">ppfd =</span> PPFD_IN)</span></code></pre></div>
</div>
<div id="writing-data" class="section level4" number="1.2.9.5">
<h4><span class="header-section-number">1.2.9.5</span> Writing data</h4>
<p>A data frame can be written to a CSV file by:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="ch-01.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(df_small, <span class="at">path =</span> <span class="st">&quot;data/df_small.csv&quot;</span>)</span></code></pre></div>
<p>The function <code>saveRDS()</code> allows you save individual objects of any form (not just a data frame). <code>saveRDS()</code> creates a binary file that is fast to write and read, but only intelligible to R. Such files are commonly identified by the suffix <code>.rds</code>. It is recommended to name the <code>.rds</code> files according to the single object they contain. For example:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="ch-01.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(temp_sum, <span class="at">file =</span> <span class="st">&quot;data/temp_sum.rds&quot;</span>)</span></code></pre></div>
<p>This file can then be read into the R workspace. Sometimes, it is useful to give it a new name, e.g.:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="ch-01.html#cb42-1" aria-hidden="true" tabindex="-1"></a>temp_sum <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/temp_sum.rds&quot;</span>)</span></code></pre></div>
<p>Note that making a file publicly available as a <code>.rds</code> file violates the FAIR principles. It is not <em>interoperable</em>. Therefore, whenever possible, save your data in a format that is readable across platforms without requiring proprietary software. Hence use <code>write_csv()</code> whenever possible. We will encounter other non-proprietary formats that let you save and share more complex data structures in chapter <a href="ch-02.html#ch-02">2</a>.</p>
</div>
</div>
<div id="r-objects" class="section level3" number="1.2.10">
<h3><span class="header-section-number">1.2.10</span> R objects</h3>
<p>Each object in R is of a certain <em>class</em>, specifying some attributes and how functions act upon it. The most basic classes are:</p>
<ul>
<li><code>numeric</code>. any number (except complex numbers) -&gt; 2.375</li>
<li><code>integer</code> (int) - integer numbers -&gt; 2</li>
<li><code>character</code> (chr) - any string -&gt; “fluxes”</li>
<li><code>logical</code> (logi) - boolean -&gt; TRUE FALSE</li>
<li><code>factor</code> (Factor) - categorical data, the variable can only be one of a defined amount of options -&gt; female/male/other</li>
<li><code>function</code> (function) - a set of statements organized to perform a specific task -&gt; sum()</li>
</ul>
<div id="data-frames" class="section level4" number="1.2.10.1">
<h4><span class="header-section-number">1.2.10.1</span> Data frames</h4>
<p>We have learned that the object <code>df</code> is a data frame. That is, it is of class <code>"data.frame"</code>. You can think of a data frame as a table. Columns need to be of the same length and all values in a column need to be of the same data type.</p>
<p>The most common data types in R are:</p>
<p>However, there are many more data types. For now, we will mainly consider those mentioned above.</p>
</div>
<div id="vectors-and-classes" class="section level4" number="1.2.10.2">
<h4><span class="header-section-number">1.2.10.2</span> Vectors and classes</h4>
<p>The contents of a data frame column is a <em>vector</em>. It can be “extracted” from its data frame by <code>pull</code>. Next, we are going to extract the values of the column <code>temp</code> and return the class of the entries in this vector. This type of sequence of commands (actually, a small workflow) can be implemented as a sequence of pipes:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="ch-01.html#cb43-1" aria-hidden="true" tabindex="-1"></a>df_small <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="ch-01.html#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(temp) <span class="sc">%&gt;%</span> </span>
<span id="cb43-3"><a href="ch-01.html#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class</span>()</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>Sometimes you need to convert a numeric number into a <em>character</em>. The following takes only the first row of the data frame <code>fluxes_subset</code> using the <code>slice()</code> function with argument <code>1</code> (for the first row), extracts the single temperature value, converts it to an integer, and then to a character:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="ch-01.html#cb45-1" aria-hidden="true" tabindex="-1"></a>df_small <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="ch-01.html#cb45-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="ch-01.html#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(temp) <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="ch-01.html#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.integer</span>() <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="ch-01.html#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.character</span>()</span></code></pre></div>
<pre><code>## [1] &quot;-2&quot;</code></pre>
<p>You notice that now the values are in quotes ““. R interprets them as a text and you will not be able to do any numeric calculations with them anymore.</p>
<p>Writing each function command on a separate line, connected with the pipe operator <code>%&gt;%</code>, allows for good readability of the entire workflow. Note that in R, a line break has no effect. Compare the above sequence of pipes to the following equivalent part of the code to understand the advantage of the tidyverse syntax:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="ch-01.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.character</span>(<span class="fu">as.integer</span>(df_small[<span class="dv">1</span>,<span class="st">&quot;temp&quot;</span>]))</span></code></pre></div>
<pre><code>## [1] &quot;-2&quot;</code></pre>
<p>Arguably, a sequence of pipes is more easily legible than a complex nesting of brackets.</p>
<p>An object of class <strong>logical</strong> can only be <code>TRUE</code> or <code>FALSE</code>. If I ask which <code>temperatures &lt; 0</code> for example, R will return a vector of class logical.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="ch-01.html#cb49-1" aria-hidden="true" tabindex="-1"></a>temperatures <span class="ot">&lt;-</span> df_small <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="ch-01.html#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="ch-01.html#cb49-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(temp)</span>
<span id="cb49-4"><a href="ch-01.html#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="ch-01.html#cb49-5" aria-hidden="true" tabindex="-1"></a>temperatures <span class="sc">&lt;</span> <span class="dv">0</span></span></code></pre></div>
<pre><code>##  [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Indeed, the first 10 temperature values are all below freezing.</p>
</div>
<div id="lists" class="section level4" number="1.2.10.3">
<h4><span class="header-section-number">1.2.10.3</span> Lists</h4>
<p>Lists are extremely flexible. They allow us to store different types of data, even if they are of different lengths. Here is an example where each element of the list is named.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="ch-01.html#cb51-1" aria-hidden="true" tabindex="-1"></a>mylist <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb51-2"><a href="ch-01.html#cb51-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">temperatures =</span> <span class="fu">c</span>(<span class="fl">2.234</span>, <span class="fl">1.987</span>, <span class="fl">4.345</span>), </span>
<span id="cb51-3"><a href="ch-01.html#cb51-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">my_favourite_function =</span> mean, </span>
<span id="cb51-4"><a href="ch-01.html#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">best_course =</span> <span class="st">&quot;Environmental Systems Data Science&quot;</span></span>
<span id="cb51-5"><a href="ch-01.html#cb51-5" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<p>Similar to data frames, we can extract elements from lists, either by index <code>[[1]]</code> or by the name <code>[["temperatures"]]</code>. Note the double <code>[[]]</code> here, indicating an element of a list as opposed to <code>[]</code> indicating an element of a vector. To get the entire vector of temperatures, do either of the two:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="ch-01.html#cb52-1" aria-hidden="true" tabindex="-1"></a>mylist[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 2.234 1.987 4.345</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="ch-01.html#cb54-1" aria-hidden="true" tabindex="-1"></a>mylist[[<span class="st">&quot;temperatures&quot;</span>]]</span></code></pre></div>
<pre><code>## [1] 2.234 1.987 4.345</code></pre>
<p>And to get the first temperature value:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="ch-01.html#cb56-1" aria-hidden="true" tabindex="-1"></a>mylist[[<span class="st">&quot;temperatures&quot;</span>]][<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 2.234</code></pre>
<p>You can also append elements to the list (either way is possible):</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="ch-01.html#cb58-1" aria-hidden="true" tabindex="-1"></a>mylist[[<span class="st">&quot;my_second_favourite_function&quot;</span>]] <span class="ot">&lt;-</span> median</span>
<span id="cb58-2"><a href="ch-01.html#cb58-2" aria-hidden="true" tabindex="-1"></a>mylist<span class="sc">$</span>my_second_favourite_function <span class="ot">&lt;-</span> median</span></code></pre></div>
<p><strong>Checkpoint</strong></p>
<p>In <em>mylist</em>, we have saved a function called <code>my_favourite_function</code> and a numeric vector called <code>temperatures</code>. Use the function stored in the list and apply it on the vector temperatures, stored in the same list. Add the result in the list as a new variable and call it <code>mean_temperature</code>. The mean temperature should be equal to 2.85533333333333.</p>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="ch-01.html#cb59-1" aria-hidden="true" tabindex="-1"></a>mylist<span class="sc">$</span>mean_temperature <span class="ot">&lt;-</span> mylist[[<span class="st">&quot;my_favourite_function&quot;</span>]](mylist[[<span class="st">&quot;temperatures&quot;</span>]])</span>
<span id="cb59-2"><a href="ch-01.html#cb59-2" aria-hidden="true" tabindex="-1"></a>mylist<span class="sc">$</span>mean_temperature</span></code></pre></div>
<pre><code>## [1] 2.855333</code></pre>
<p>This was a very condensed introduction to vectors and lists. A more complete introduction is given <a href="https://r4ds.had.co.nz/vectors.html">here</a>.</p>
</div>
</div>
<div id="data-visualisation" class="section level3" number="1.2.11">
<h3><span class="header-section-number">1.2.11</span> Data visualisation</h3>
<p>Visualising data is an integral part of any data science workflow. In this chapter, we introduce just the very basics. In later chapters, you will get introduced to additional methods for visualising data. Our data frame <code>fluxes_subset</code> contains three variables, one of which is <code>time</code>. In other words, we are dealing with a time series. Let’s look at the temporal course of temperature in the first 1440 time steps (corresponding to 30 days) as a line plot (<code>type = "l"</code>).</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="ch-01.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">1440</span>, df_small<span class="sc">$</span>temp[<span class="dv">1</span><span class="sc">:</span><span class="dv">1440</span>], <span class="at">type =</span> <span class="st">&quot;l&quot;</span>) </span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-40-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Another useful way of looking, not at a temporal course, but rather at the distribution of your data, is to display a histogram.
A histogram visualises the frequency or proportion of data that has a metric value that falls within a certain interval known as a ‘bin’. Below you will see the temperature on the x-axis split into these ‘bins’ ranging across 2°. The number of times a data point falls between say 2° to 4° is then tallied and displayed as the frequency on the y-axis. Here there are around 1500 temperature values between 2° and 4°.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="ch-01.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df_small<span class="sc">$</span>temp, <span class="at">xlab =</span> <span class="st">&quot;Temperature (°C)&quot;</span>)</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-41-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Plots can be saved as files, as long as the file size does not get too large.It will write vector graphics as outputs, i.e. PDF. In base-R, this can be done by:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="ch-01.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pdf</span>(<span class="st">&quot;./figures/filename.pdf&quot;</span>)</span>
<span id="cb63-2"><a href="ch-01.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df_small<span class="sc">$</span>temp)</span></code></pre></div>
<p><strong>Checkpoint</strong></p>
<p>Create a scatter-plot (points) of temperature versus the incoming photosynthetic photon flux density using all data points in <code>df_small</code>. Can this plot intuitively be interpreted?</p>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="ch-01.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_small<span class="sc">$</span>temp, df_small<span class="sc">$</span>ppfd)</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-43-1.png" width="50%" style="display: block; margin: auto;" /></p>
</div>
<div id="conditionals" class="section level3" number="1.2.12">
<h3><span class="header-section-number">1.2.12</span> Conditionals</h3>
<p>In cases where certain statements are executed or not, depending on a criterion, we can use conditional statements <code>if</code>, <code>else if</code>, and <code>else</code>. Conditionals are an essential feature of programming and available in all languages. The R syntax for conditionals looks like this:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="ch-01.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (temp <span class="sc">&lt;</span> <span class="fl">0.0</span>){</span>
<span id="cb65-2"><a href="ch-01.html#cb65-2" aria-hidden="true" tabindex="-1"></a>  is_frozen <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb65-3"><a href="ch-01.html#cb65-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb65-4"><a href="ch-01.html#cb65-4" aria-hidden="true" tabindex="-1"></a>  is_frozen <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb65-5"><a href="ch-01.html#cb65-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The evaluation of the criterion (here <code>(temp &lt; 0.0)</code>) has to return either <code>TRUE</code> or <code>FALSE</code>.</p>
</div>
<div id="loops" class="section level3" number="1.2.13">
<h3><span class="header-section-number">1.2.13</span> Loops</h3>
<p>Loops are another essential essential feature of programming. <code>for</code> and <code>while</code> loops exist in probably all programming languages. We introduce them here because they provide an essential and powerful functionality for solving many common tasks. You will encounter them later again (see Chapter <a href="ch-05.html#ch-05">5</a>.</p>
<p><code>for</code> and <code>while</code> loops let us repeatedly execute the same set of commands, while changing an index, or counter variable to take a sequence of different values. The following example calculates a temperature sum of the first ten values, by iteratively adding them together. Of course, this is equivalent to just using the <code>sum()</code> function.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="ch-01.html#cb66-1" aria-hidden="true" tabindex="-1"></a>temp_sum <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb66-2"><a href="ch-01.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>){</span>
<span id="cb66-3"><a href="ch-01.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  temp_sum <span class="ot">&lt;-</span> temp_sum <span class="sc">+</span> df_small<span class="sc">$</span>temp[i]</span>
<span id="cb66-4"><a href="ch-01.html#cb66-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb66-5"><a href="ch-01.html#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(temp_sum)</span></code></pre></div>
<pre><code>## [1] -12.97</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="ch-01.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">sum</span>(df_small<span class="sc">$</span>temp[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]))</span></code></pre></div>
<pre><code>## [1] -12.97</code></pre>
<p>Instead of directly telling R how many iterations it should do we can also define a condition. As long as the condition is TRUE, R will continue iterating. As soon as it is FALSE, R stops the loop. The following lines of code do the same operation as the for loop we just wrote. What’s different? What is the same?</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="ch-01.html#cb70-1" aria-hidden="true" tabindex="-1"></a>i <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb70-2"><a href="ch-01.html#cb70-2" aria-hidden="true" tabindex="-1"></a>temp_sum <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb70-3"><a href="ch-01.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> (i <span class="sc">&lt;=</span> <span class="dv">10</span>){</span>
<span id="cb70-4"><a href="ch-01.html#cb70-4" aria-hidden="true" tabindex="-1"></a>  temp_sum <span class="ot">&lt;-</span> temp_sum <span class="sc">+</span> df_small<span class="sc">$</span>temp[i]</span>
<span id="cb70-5"><a href="ch-01.html#cb70-5" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">=</span> i<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb70-6"><a href="ch-01.html#cb70-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb70-7"><a href="ch-01.html#cb70-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(temp_sum)</span></code></pre></div>
<pre><code>## [1] -12.97</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="ch-01.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">sum</span>(df_small<span class="sc">$</span>temp[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]))</span></code></pre></div>
<pre><code>## [1] -12.97</code></pre>
</div>
<div id="where-to-find-help" class="section level3" number="1.2.14">
<h3><span class="header-section-number">1.2.14</span> Where to find help</h3>
<p>The material covered in this course will give you a solid basis for your future projects. Even more so, it provides you with code examples that you can adapt to your own purposes. Naturally, you will face problems we did not cover in the course and you will need to learn more as you go. The good news is, you do not have to. Many people make their code available online and often others have faced similar problems. Modifying existing code might make it easier for you to get started.</p>
<div id="within-r" class="section level4" number="1.2.14.1">
<h4><span class="header-section-number">1.2.14.1</span> Within R</h4>
<p>“<em>I know the name of a function that might help solve the problem but I do not know how to use it.</em>” Typing a <code>?</code> in front of the function will open the documentation of the function, giving lots of information on the uses and options a function has. You have learned a few things about plots but you may not know how to make a boxplot:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="ch-01.html#cb74-1" aria-hidden="true" tabindex="-1"></a>?boxplot</span></code></pre></div>
<p>Running the above code will open the information on making boxplots in R.</p>
<p>If you do know how a function works but need to be reminded of the arguments it takes, simply type:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="ch-01.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">args</span>(boxplot)</span></code></pre></div>
<p>“<em>There must be a function that does task X but I do not know which one.</em>” Typing <code>??</code> will call the function <code>help.search()</code>. Maybe you want to save a plot as a JPEG but you do not know how:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="ch-01.html#cb76-1" aria-hidden="true" tabindex="-1"></a>??jpeg</span></code></pre></div>
<p>Note that it only looks through your <em>installed</em> packages.</p>
</div>
<div id="online" class="section level4" number="1.2.14.2">
<h4><span class="header-section-number">1.2.14.2</span> Online</h4>
<p>To search in the entire library of R go to the website <a href="https://www.rdocumentation.org/">rdocumentation.org</a> or turn to a search engine of your choice. It will send you to the appropriate function documentation or a helpful forum where someone has already asked a similar question. Most of the time you will end up on <a href="https://stackoverflow.com/">stackoverflow.com</a>, a forum where most questions have already been answered.</p>
</div>
<div id="error-messages" class="section level4" number="1.2.14.3">
<h4><span class="header-section-number">1.2.14.3</span> Error messages</h4>
<p>If you do not understand the error message, start by searching the web. Be aware, that this is not always useful as developers rely on the error catching provided by R. To be more specific add the name of the function and package you are using, to get a more detailed answer.</p>
</div>
<div id="asking-for-help" class="section level4" number="1.2.14.4">
<h4><span class="header-section-number">1.2.14.4</span> Asking for help</h4>
<p>If you cannot find a solution online, start by asking your friends and colleagues. Someone with more experience than you might be able and willing to help you. When asking for help it is important to think about how you state the problem. The key to receiving help is to make it as easy as possible to understand the issue your facing. Try to reduce what does not work to a simple example. Reproduce a problem with a simple data frame instead of one with thousands of rows. Generalize it in a way that people who do not do research in your field can understand the problem. If you are asking a question online in a forum include the output of <code>sessionInfo()</code> (it provides information about the R version, packages your using,…) and other information that can be helpful to understand the problem. stackoverflow.com has its own guidelines on how to ask a good question, which you should follow. If your question is well crafted and has not been answered before you can sometimes get an answer within 5 minutes. <a href="https://stackoverflow.com/help/how-to-ask">https://stackoverflow.com/help/how-to-ask</a></p>
<p>Finally, many packages have a mailing list or allow you to open a query on the code repository, where you can ask specific questions. The same is true for R itself. The R-Help mailing list <a href="https://stat.ethz.ch/mailman/listinfo/r-help">https://stat.ethz.ch/mailman/listinfo/r-help</a> is read by many people. However, the tone of such mailing lists can be pretty dry and unwelcoming to new users. Be sure to use the right terminology or else you might get an answer pointing out your misuse of language instead of your problem. Also, be sure your question is valid. Or else you won’t get an answer.</p>
</div>
</div>
<div id="key-points-from-the-tutorial" class="section level3" number="1.2.15">
<h3><span class="header-section-number">1.2.15</span> Key points from the tutorial</h3>
<p><em>RStudio on Renku and Git commands</em>:
- Regularly commit any changes you make to your work. To do this tick the <em>Stage</em> box, add a commit message and press commit.
- Then upload the changes to the remote repository by <em>pushing</em> it.
- Remember to close any active environments when you have finished your work on Renku.</p>
<p><em>R scripts</em>:</p>
<ul>
<li>Comments are any code prefixed by at least one hastag (<code>#</code>) will not be interpreted by R.</li>
<li>Comments should help you understand your script.</li>
<li>Add spaces around operators and breaks to make code easier to read.</li>
<li>Use <code>&lt;-</code>, not <code>=</code>, for allocating a value to a variable.</li>
<li>Begin files with a header to describe what the code contains and does.</li>
<li>Load all the libraries needed in the script at the beginning.</li>
</ul>
<p><em>Functions</em>:
- Use functions to simplify a script with many steps or for duplicated code sections.
- Functions (particularly long ones) can be written to separate source file (text files containing executable code).</p>
<p><em>Tidy data</em> is a concept that follows these rules:
1. Each column is a variable.
2. Each row is an observation.
3. Each value has its own cell.</p>
<p><em>Working with data frames</em>:
- To get an idea of the structure of a data frame use functions such as:
1. Size: <code>dim()</code>, <code>nrow()</code>, <code>ncol()</code>
2. Content: <code>head()</code>, <code>tail()</code>, <code>view()</code>
3. Names: <code>names()</code>, <code>rownames()</code>
4. Summary: <code>class()</code>, <code>str()</code>, <code>summary()</code></p>
<ul>
<li><p><em>Selecting data and entering the tidyverse</em>: Data frames consist of rows and columns. To extract information either use <code>df[row(s), column(s)]</code> or with tidyverse <code>df %&gt;% select(column)</code>.</p></li>
<li><p><em>Vectors and classes</em>: The simplest data structure in R is a vector and can be numeric or character vectors.</p></li>
<li><p><em>Lists</em>: Lists allow data of different types to be stored. To extract elements use double brackets <code>[[]]</code>.</p></li>
<li><p><em>Data visualisation</em>: Visualising data can provide a unique way to see and understand the data.</p></li>
<li><p><em>Loops</em>: Loops (such as <code>for</code> and <code>while</code>) are another essential essential feature of programming and lets us repeatedly execute the same set of commands.</p></li>
</ul>
<p><em>Where to find help</em>: First, look within R (e.g. <code>?pch</code>), then use the internet or ask colleagues. Remember to include <code>sessionInfo()</code> to help others to understand the version of R and packages you are using.</p>
</div>
<div id="further-reading" class="section level3" number="1.2.16">
<h3><span class="header-section-number">1.2.16</span> Further reading</h3>
<p>A complete tutorial on using R for Data Science in general is the freely available online-book by <a href="https://r4ds.had.co.nz/">Grolemund &amp; Wickham</a>. The material covered in this chapter should serve as a “primer”. That is, its purpose is to get you started with R and Git and make sure you know the basics. If you feel that you are still missing some basic concepts of R, a good starting point to fill up your gaps is the <a href="https://r4ds.had.co.nz/workflow-basics.html">Chapter <em>Workflow: basics</em> in Grolemund &amp; Wickham</a>.</p>
</div>
</div>
<div id="exercise" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Exercise</h2>
<p>This exercise will have you working on an Excel file and then in Renku’s Rstudio. You will need to download the provided datafile from moodle. Your task will be to tidy the data and then read it into Renku’s Rstudio.</p>
<p>Download data from Groenigen et al., 2014, containing soil organic matter content data from a meta analysis of CO2 experiments, and available on Moodle. Open the file in Excel and navigate to the tab ‘Database S1’. You will find a short description in the top-left cell: “Database S1. Overview of CO2 enrichment studies reporting soil C contents that were used in our analysis.”. There is an issue with this dataset. Of course, .xls files are not easily readable into R without an extra package. In addition, even after saving the tab ‘Database S1’ as a CSV file, the table you get is not <strong>machine-readable</strong> into a data frame that we can work with in R. The way the data is organised into cells does not follow the structure of a dataframe and is not tidy. Recall the <strong>tidy data</strong> rules from the 01_primers.ipynb tutorial.</p>
<p>Your task is to:</p>
<ol style="list-style-type: decimal">
<li>Manually manipulate the .xls file to make it tidy.</li>
<li>Save the data as a .csv file (comma-separated-values).</li>
<li>Read the .csv file into RStudio.</li>
<li>Calculate the logarithmic response ratio as the logarithm of the ratio of soil C contents at elevated CO2 divided by soil C contents at ambient CO2, for each data point (experiment and sample date).</li>
<li>Visualise the distribution of the response ratio and save the plot as a .pdf file.</li>
</ol>
<p>Implement steps 3.-5. in an RMarkdown (.Rmd), applying some of the points for good coding practices. For the peer review round, share your code and the figure file (as html file via the <code>knit</code> button at the top, left of the Git menu, see Figure below) with your partner.</p>
<!-- Follow the steps outlined below to get a more detailed instruction on your task: 

For the final exercise, you will move to RStudio on Renku. Since you are doing this for the first time, we will quickly remind you how to get there:
- Save all your changes to this file using Git (git status, git add, git commit, git push)
- Close this tab and go back to the [Renku](https://renkulab.io/) website.
- Navigate to your environments and stop the environment.
- Create a new environment, select `/rstudio` instead of `/lab`
- Connect to the environment, navigate to the folder `/exercise/scripts/` and open the R file called 'exercise_01.R'

Before you go: Git looks a little different in Rstudio but essentially works the same way. Instead of typing the commands, you use a graphical user interface. Click on Git (highlighted red in the following image), there you will find the three options you are familiar with. `git status` and `git add` are not needed.

![](./figures/gitrstudio.png)
-->

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Pastorello2020" class="csl-entry">
Pastorello, Gilberto, Carlo Trotta, Eleonora Canfora, Housen Chu, Danielle Christianson, You Wei Cheah, Cristina Poindexter, et al. 2020. <span>“<span class="nocase">The FLUXNET2015 dataset and the ONEFlux processing pipeline for eddy covariance data</span>.”</span> <em>Scientific Data</em> 7 (1): 225. <a href="https://doi.org/10.1038/s41597-020-0534-3">https://doi.org/10.1038/s41597-020-0534-3</a>.
</div>
<div id="ref-Wickham2014" class="csl-entry">
Wickham, Hadley. 2014. <span>“<span>Tiday Data</span>.”</span> <em>Journal of Statistical Software</em> 59 (10): 1–23. <a href="http://www.jstatsoft.org/">http://www.jstatsoft.org/</a>.
</div>
<div id="ref-wickham_welcome_nodate" class="csl-entry">
———. n.d. <em>Welcome <span></span> <span>The</span> Tidyverse Style Guide</em>. <a href="https://style.tidyverse.org/">https://style.tidyverse.org/</a>.
</div>
<div id="ref-Wickham2017R" class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2017. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. 1st ed. Paperback; O’Reilly Media. <a href="http://r4ds.had.co.nz/">http://r4ds.had.co.nz/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch-02.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
