<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Data wrangling | Environmental Systems Data Science</title>
  <meta name="description" content="Text book and exercises. ETH Zürich" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Data wrangling | Environmental Systems Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Text book and exercises. ETH Zürich" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data wrangling | Environmental Systems Data Science" />
  
  <meta name="twitter:description" content="Text book and exercises. ETH Zürich" />
  

<meta name="author" content="Loïc Pellissier, Joshua Payne, Benjamin Stocker" />


<meta name="date" content="2021-02-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="primers.html"/>
<link rel="next" href="data-variety.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Environmental Systems Data Science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="primers.html"><a href="primers.html"><i class="fa fa-check"></i><b>2</b> Primers</a></li>
<li class="chapter" data-level="3" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>3</b> Data wrangling</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="data-wrangling.html"><a href="data-wrangling.html#data-transformation-with-dplyr"><i class="fa fa-check"></i><b>3.0.1</b> Data transformation with dplyr</a></li>
<li class="chapter" data-level="3.0.2" data-path="data-wrangling.html"><a href="data-wrangling.html#data-visualisation-with-ggplot2"><i class="fa fa-check"></i><b>3.0.2</b> Data visualisation with ggplot2</a></li>
<li class="chapter" data-level="3.1" data-path="data-wrangling.html"><a href="data-wrangling.html#hands-on"><i class="fa fa-check"></i><b>3.1</b> Hands-on</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-wrangling.html"><a href="data-wrangling.html#dataset-1-half-hourly-flux-data"><i class="fa fa-check"></i><b>3.1.1</b> Dataset 1 (half-hourly flux data)</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-wrangling.html"><a href="data-wrangling.html#dataset-2-daily-flux-data"><i class="fa fa-check"></i><b>3.1.2</b> Dataset 2 (daily flux data)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-variety.html"><a href="data-variety.html"><i class="fa fa-check"></i><b>4</b> Data variety</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-variety.html"><a href="data-variety.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-variety.html"><a href="data-variety.html#overview"><i class="fa fa-check"></i><b>4.1.1</b> Overview</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-variety.html"><a href="data-variety.html#learning-objectives"><i class="fa fa-check"></i><b>4.1.2</b> Learning objectives</a></li>
<li class="chapter" data-level="4.1.3" data-path="data-variety.html"><a href="data-variety.html#key-points-of-the-lecture"><i class="fa fa-check"></i><b>4.1.3</b> Key points of the lecture</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-variety.html"><a href="data-variety.html#tutorial"><i class="fa fa-check"></i><b>4.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="data-variety.html"><a href="data-variety.html#overview-1"><i class="fa fa-check"></i><b>4.2.1</b> Overview</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-variety.html"><a href="data-variety.html#modis-remote-download"><i class="fa fa-check"></i><b>4.2.2</b> MODIS remote download</a></li>
<li class="chapter" data-level="4.2.3" data-path="data-variety.html"><a href="data-variety.html#points-on-the-globe"><i class="fa fa-check"></i><b>4.2.3</b> Points on the globe</a></li>
<li class="chapter" data-level="4.2.4" data-path="data-variety.html"><a href="data-variety.html#shapefiles"><i class="fa fa-check"></i><b>4.2.4</b> Shapefiles</a></li>
<li class="chapter" data-level="4.2.5" data-path="data-variety.html"><a href="data-variety.html#rasters"><i class="fa fa-check"></i><b>4.2.5</b> Rasters</a></li>
<li class="chapter" data-level="4.2.6" data-path="data-variety.html"><a href="data-variety.html#key-points-of-the-tutorial"><i class="fa fa-check"></i><b>4.2.6</b> Key points of the tutorial</a></li>
<li class="chapter" data-level="4.2.7" data-path="data-variety.html"><a href="data-variety.html#bonus-species-occurrence-trait-data-and-pcas"><i class="fa fa-check"></i><b>4.2.7</b> Bonus: Species Occurrence, Trait Data and PCAs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-scraping.html"><a href="data-scraping.html"><i class="fa fa-check"></i><b>5</b> Data Scraping</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-scraping.html"><a href="data-scraping.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="data-scraping.html"><a href="data-scraping.html#theory"><i class="fa fa-check"></i><b>5.2</b> Theory</a></li>
<li class="chapter" data-level="5.3" data-path="data-scraping.html"><a href="data-scraping.html#web-scraping-applied"><i class="fa fa-check"></i><b>5.3</b> Web Scraping Applied</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data-scraping.html"><a href="data-scraping.html#r-packages-and-functions"><i class="fa fa-check"></i><b>5.3.1</b> R-Packages and Functions</a></li>
<li class="chapter" data-level="5.3.2" data-path="data-scraping.html"><a href="data-scraping.html#the-fishbase-website"><i class="fa fa-check"></i><b>5.3.2</b> The FishBase website</a></li>
<li class="chapter" data-level="5.3.3" data-path="data-scraping.html"><a href="data-scraping.html#accessing-fishbase"><i class="fa fa-check"></i><b>5.3.3</b> Accessing FishBase</a></li>
<li class="chapter" data-level="5.3.4" data-path="data-scraping.html"><a href="data-scraping.html#scraping-numbers"><i class="fa fa-check"></i><b>5.3.4</b> Scraping Numbers</a></li>
<li class="chapter" data-level="5.3.5" data-path="data-scraping.html"><a href="data-scraping.html#scraping-text-snippetrs"><i class="fa fa-check"></i><b>5.3.5</b> Scraping Text Snippetrs</a></li>
<li class="chapter" data-level="5.3.6" data-path="data-scraping.html"><a href="data-scraping.html#scraping-tables"><i class="fa fa-check"></i><b>5.3.6</b> Scraping Tables</a></li>
<li class="chapter" data-level="5.3.7" data-path="data-scraping.html"><a href="data-scraping.html#the-fishbase-package"><i class="fa fa-check"></i><b>5.3.7</b> The Fishbase Package</a></li>
<li class="chapter" data-level="5.3.8" data-path="data-scraping.html"><a href="data-scraping.html#summary"><i class="fa fa-check"></i><b>5.3.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="data-scraping.html"><a href="data-scraping.html#case-study-species-richness-and-red-list-species-proportions"><i class="fa fa-check"></i><b>5.4</b> Case Study: Species Richness and Red List species proportions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="data-scraping.html"><a href="data-scraping.html#creating-list-of-species"><i class="fa fa-check"></i><b>5.4.1</b> Creating List of Species</a></li>
<li class="chapter" data-level="5.4.2" data-path="data-scraping.html"><a href="data-scraping.html#extracting-iucn-status-for-all-species"><i class="fa fa-check"></i><b>5.4.2</b> Extracting IUCN Status for all species</a></li>
<li class="chapter" data-level="5.4.3" data-path="data-scraping.html"><a href="data-scraping.html#proportion-of-species-in-netherlands"><i class="fa fa-check"></i><b>5.4.3</b> Proportion of species in Netherlands</a></li>
<li class="chapter" data-level="5.4.4" data-path="data-scraping.html"><a href="data-scraping.html#cleaning-data-with-iucn-status"><i class="fa fa-check"></i><b>5.4.4</b> Cleaning data with IUCN Status</a></li>
<li class="chapter" data-level="5.4.5" data-path="data-scraping.html"><a href="data-scraping.html#maps-of-species-richness-and-red-list-species-proportions"><i class="fa fa-check"></i><b>5.4.5</b> Maps of species richness and Red List species proportions</a></li>
<li class="chapter" data-level="5.4.6" data-path="data-scraping.html"><a href="data-scraping.html#relation-of-basin-size-and-species-richness"><i class="fa fa-check"></i><b>5.4.6</b> Relation of basin size and species richness</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="data-scraping.html"><a href="data-scraping.html#references"><i class="fa fa-check"></i><b>5.5</b> References</a></li>
<li class="chapter" data-level="5.6" data-path="data-scraping.html"><a href="data-scraping.html#exercise-1"><i class="fa fa-check"></i><b>5.6</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="catch-up.html"><a href="catch-up.html"><i class="fa fa-check"></i><b>6</b> Catch-up</a></li>
<li class="chapter" data-level="7" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html"><i class="fa fa-check"></i><b>7</b> Supervised machine learning basics I</a>
<ul>
<li class="chapter" data-level="7.1" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#introduction-2"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#learning-objectives-1"><i class="fa fa-check"></i><b>7.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="7.1.2" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#important-points-from-the-lecture"><i class="fa fa-check"></i><b>7.1.2</b> Important points from the lecture</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#tutorial-1"><i class="fa fa-check"></i><b>7.2</b> Tutorial</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#linear-regression"><i class="fa fa-check"></i><b>7.2.1</b> Linear regression</a></li>
<li class="chapter" data-level="7.2.2" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#k-nearest-neighbours"><i class="fa fa-check"></i><b>7.2.2</b> K-nearest neighbours</a></li>
<li class="chapter" data-level="7.2.3" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#essential-methods-for-the-modelling-process"><i class="fa fa-check"></i><b>7.2.3</b> Essential methods for the modelling process</a></li>
<li class="chapter" data-level="7.2.4" data-path="supervised-machine-learning-basics-i.html"><a href="supervised-machine-learning-basics-i.html#bonus"><i class="fa fa-check"></i><b>7.2.4</b> Bonus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="supervised-machine-learning-methods-ii.html"><a href="supervised-machine-learning-methods-ii.html"><i class="fa fa-check"></i><b>8</b> Supervised machine learning methods II</a></li>
<li class="chapter" data-level="9" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html"><i class="fa fa-check"></i><b>9</b> Application 1: Variable selection</a>
<ul>
<li class="chapter" data-level="9.1" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#warm-up-1-nested-for-loop"><i class="fa fa-check"></i><b>9.2</b> Warm-up 1: Nested for-loop</a></li>
<li class="chapter" data-level="9.3" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#warm-up-2-find-the-best-single-predictor"><i class="fa fa-check"></i><b>9.3</b> Warm-up 2: Find the best single predictor</a></li>
<li class="chapter" data-level="9.4" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#full-stepwise-regression"><i class="fa fa-check"></i><b>9.4</b> Full stepwise regression</a></li>
<li class="chapter" data-level="9.5" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#bonus-stepwise-regression-out-of-the-box"><i class="fa fa-check"></i><b>9.5</b> Bonus: Stepwise regression out-of-the-box</a></li>
<li class="chapter" data-level="9.6" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#warm-up-2-find-the-best-single-predictor-1"><i class="fa fa-check"></i><b>9.6</b> Warm-up 2: Find the best single predictor</a></li>
<li class="chapter" data-level="9.7" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#full-stepwise-regression-1"><i class="fa fa-check"></i><b>9.7</b> Full stepwise regression</a></li>
<li class="chapter" data-level="9.8" data-path="application-1-variable-selection.html"><a href="application-1-variable-selection.html#bonus-stepwise-regression-out-of-the-box-1"><i class="fa fa-check"></i><b>9.8</b> <span>BONUS</span> Stepwise regression out-of-the-box</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="xxx.html"><a href="xxx.html"><i class="fa fa-check"></i><b>10</b> XXX</a></li>
<li class="chapter" data-level="11" data-path="xxx-1.html"><a href="xxx-1.html"><i class="fa fa-check"></i><b>11</b> XXX</a></li>
<li class="chapter" data-level="12" data-path="xxx-2.html"><a href="xxx-2.html"><i class="fa fa-check"></i><b>12</b> XXX</a></li>
<li class="chapter" data-level="13" data-path="xxx-3.html"><a href="xxx-3.html"><i class="fa fa-check"></i><b>13</b> XXX</a></li>
<li class="chapter" data-level="14" data-path="xxx-4.html"><a href="xxx-4.html"><i class="fa fa-check"></i><b>14</b> XXX</a></li>
<li class="chapter" data-level="15" data-path="xxx-5.html"><a href="xxx-5.html"><i class="fa fa-check"></i><b>15</b> XXX</a></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Environmental Systems Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-wrangling" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Data wrangling</h1>
<p>In this chapter, you’ll learn to efficiently explore your data. This includes understanding how the data is structured, what “dimensions” are in a dataset, how to manipulate the data and visualise it. Efficient data exploration and wrangling are the basis for generating hypotheses, testing them, and repeating the wrangling-visualisation-hypothesis circle over and over. That’s science.</p>
<p>R offers great functionalities for achieving efficient data wrangling and visualisation, particularly using functions from the <a href="https://www.tidyverse.org/">tidyverse</a>. (Formulating the hypotheses is still up to humans). You’ve already got in touch with some of the functions of the tidyverse. This chapter will introduce some more of the basic and most important tidyverse functions, including <a href="https://ggplot2.tidyverse.org/">ggplot</a>.
The contents of this tutorial are inspired by the (freely available online-) book <a href="https://r4ds.had.co.nz/"><em>R for Data Science</em> by Grolemund &amp; Wickham</a>.</p>
<p>After you’ve gone through the lecture and solved the exercises you should be able to:
- Define data, understand the structure of data and list examples of environmental data.
- List the various possible data types and formats.
- Explain the possible sources of data in environmental data science.
- Define metadata.
- List the various possible data pre-processing methods.
- Understandtidy data and data dimensions.
- Learn how to plot data.
- Apply data aggregation.
- Apply data cleaning and gapfilling.</p>
<hr />
<div id="data-transformation-with-dplyr" class="section level3" number="3.0.1">
<h3><span class="header-section-number">3.0.1</span> Data transformation with dplyr</h3>
<p>In video 2c, you’ve been introduced to the “dimensions” of data and some of the essential functions of the tidyverse package <code>dplyr</code>:</p>
<ul>
<li>Picking observations by their values: <code>filter()</code></li>
<li>Picking variables by their names: <code>select()</code></li>
<li>Creating new variables: <code>mutate()</code></li>
<li>Aggregating multiple values down to a single summary: <code>summarise()</code></li>
</ul>
<p>Remember also that <code>dplyr</code> functions (sometimes, they are called “verbs”) all work similarly:</p>
<ul>
<li>The first argument is the data frame. When using pipes (<code>%&gt;%</code>, see Chapter 1), the first argument specifying the data frame is omitted and the function takes its place. What’s being piped into it, “coming” from the left side of <code>%&gt;%</code>.</li>
<li>The remaining arguments specify what to do with the data frame (without quotes (<code>""</code>) on variable names).</li>
<li>The output of the function is again a data frame.</li>
</ul>
</div>
<div id="data-visualisation-with-ggplot2" class="section level3" number="3.0.2">
<h3><span class="header-section-number">3.0.2</span> Data visualisation with ggplot2</h3>
<p>In the same video (2c), we learned about data visualisation with the tidyverse package ggplot2. Remember the steps for creating a figure with ggplot2:</p>
<p>Start by calling the function <code>ggplot()</code>:
- As a first argument, it takes the data frame, that contains the values that are to be displayed in a figure.
- The second argument is the “mapping” argument and always comes in the form of <code>aes(...)</code>. Inside the brackets, we usually indicate the column (variable) that specifies the coordinate of a visualisation element (e.g., a point) along the x-axis with <code>x = ...</code>, and along the y-axis with <code>y = ...</code>.</p>
<p>Then, add an additional function call to the initial <code>ggplot()</code>, with a <code>+</code> to specify the type of visualisation element (e.g., points, or lines, etc.) that maps the variable values to the plot coordinate space (for example x-y). The ggplot-<code>+</code> works a bit like the pipe operator <code>%&gt;%</code>. This function call now specifies the type of plot to create. The name of this function starts with <code>geom_</code>. For example, to plot points of temperature at a given time from a data frame <code>df</code> into x-y space (a scatterplot), we would write something like:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="data-wrangling.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> temperature)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="data-wrangling.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<hr />
</div>
<div id="hands-on" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Hands-on</h2>
<div id="dataset-1-half-hourly-flux-data" class="section level3" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Dataset 1 (half-hourly flux data)</h3>
<p>After learning about some basic concepts and functions for data wrangling and visualisation, let’s get our hands on the data. As in previous exercises, we’ll be using the time series data from eddy covariance flux measurements and meteorological variables measured in parallel. In this sub-section, we start with half-hourly data from a flux tower near Zürich (<a href="https://gl.ethz.ch/research/bage/fluxnet-ch.html">CH-Lae</a>, located on the Lägern mountain between Regensberg and Baden and run by our colleagues here at ETH). The data covers years 2004-2014 at a half-hourly time step. That’s a lot of data and will most likely drive Excel to desperation. That’s ok. In this course, you’ll learn to do your data wrangling fully outside of Excel and you’ll see how it improves your life as a (data) scientist considerably.</p>
<p>Every research project starts with a broad overall question. In this course, we are guided by the question about the variations and controls of ecosystem-level gross primary production (GPP). GPP is the gross carbon assimilation by photosynthesis of all plants in the “footprint” of an eddy covariance tower and can be derived from the measurement of the vertical turbulent net flux of CO<sub>2</sub> (on the basis of vertical air movement and parallel CO<sub>2</sub> concentration measurements). “Gross” because plants simultaneously respire CO<sub>2</sub> as they assimilate it and this also during the night. Several assumptions have to be made to get to the final GPP time series. In our dataset, different GPP time series are available and are derived using different assumptions. Below, we’ll work with the one called <code>GPP_NT_VUT_REF</code>.</p>
<p>Now that we roughly know what to expect from the contents of our dataset and we have a research question in mind (controls and variations of GPP), we can start searching for answers by reading, transforming, visualising, and modelling our data. Based on what we learn from this initial exploratory data analysis, we will refine our research question, focus it, and follow it up with the next level of data analysis and modelling in later chapters.</p>
<div id="variables-in-a-data-frame" class="section level4" number="3.1.1.1">
<h4><span class="header-section-number">3.1.1.1</span> Variables in a data frame</h4>
<p>Let’s read in the half-hourly data from the eddy-covariance site CH-Lae again (as we did already in Chapter 1) and have a quick look at it. We use the function <code>read_csv()</code> from the <code>readr</code> package here for reading the CSV since it’s faster than the base-R <code>read.csv()</code> and generates a nicely readable output when printing the object. You can find more information about reading data with <code>read_csv()</code> <a href="https://r4ds.had.co.nz/data-import.html">here</a>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="data-wrangling.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="data-wrangling.html#cb4-2" aria-hidden="true" tabindex="-1"></a>hhdf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;./data/FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2014_1-3.csv&quot;</span>)</span>
<span id="cb4-3"><a href="data-wrangling.html#cb4-3" aria-hidden="true" tabindex="-1"></a>hhdf</span></code></pre></div>
<pre><code>## # A tibble: 192,864 x 235
##    TIMESTAMP_START TIMESTAMP_END TA_F_MDS TA_F_MDS_QC TA_ERA  TA_F TA_F_QC
##              &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1    200401010000  200401010030    -9999       -9999  -2.22 -2.22       2
##  2    200401010030  200401010100    -9999       -9999  -2.25 -2.25       2
##  3    200401010100  200401010130    -9999       -9999  -2.28 -2.28       2
##  4    200401010130  200401010200    -9999       -9999  -2.50 -2.50       2
##  5    200401010200  200401010230    -9999       -9999  -2.72 -2.72       2
##  6    200401010230  200401010300    -9999       -9999  -2.94 -2.94       2
##  7    200401010300  200401010330    -9999       -9999  -3.17 -3.17       2
##  8    200401010330  200401010400    -9999       -9999  -3.39 -3.39       2
##  9    200401010400  200401010430    -9999       -9999  -3.61 -3.61       2
## 10    200401010430  200401010500    -9999       -9999  -3.59 -3.59       2
## # … with 192,854 more rows, and 228 more variables: SW_IN_POT &lt;dbl&gt;,
## #   SW_IN_F_MDS &lt;dbl&gt;, SW_IN_F_MDS_QC &lt;dbl&gt;, SW_IN_ERA &lt;dbl&gt;, SW_IN_F &lt;dbl&gt;,
## #   SW_IN_F_QC &lt;dbl&gt;, LW_IN_F_MDS &lt;dbl&gt;, LW_IN_F_MDS_QC &lt;dbl&gt;, LW_IN_ERA &lt;dbl&gt;,
## #   LW_IN_F &lt;dbl&gt;, LW_IN_F_QC &lt;dbl&gt;, LW_IN_JSB &lt;dbl&gt;, LW_IN_JSB_QC &lt;dbl&gt;,
## #   LW_IN_JSB_ERA &lt;dbl&gt;, LW_IN_JSB_F &lt;dbl&gt;, LW_IN_JSB_F_QC &lt;dbl&gt;,
## #   VPD_F_MDS &lt;dbl&gt;, VPD_F_MDS_QC &lt;dbl&gt;, VPD_ERA &lt;dbl&gt;, VPD_F &lt;dbl&gt;,
## #   VPD_F_QC &lt;dbl&gt;, PA &lt;dbl&gt;, PA_ERA &lt;dbl&gt;, PA_F &lt;dbl&gt;, PA_F_QC &lt;dbl&gt;, P &lt;dbl&gt;,
## #   P_ERA &lt;dbl&gt;, P_F &lt;dbl&gt;, P_F_QC &lt;dbl&gt;, WS &lt;dbl&gt;, WS_ERA &lt;dbl&gt;, WS_F &lt;dbl&gt;,
## #   WS_F_QC &lt;dbl&gt;, WD &lt;dbl&gt;, USTAR &lt;dbl&gt;, RH &lt;dbl&gt;, PPFD_IN &lt;dbl&gt;,
## #   CO2_F_MDS &lt;dbl&gt;, CO2_F_MDS_QC &lt;dbl&gt;, TS_F_MDS_1 &lt;dbl&gt;, TS_F_MDS_2 &lt;dbl&gt;,
## #   TS_F_MDS_3 &lt;dbl&gt;, TS_F_MDS_4 &lt;dbl&gt;, TS_F_MDS_5 &lt;dbl&gt;, TS_F_MDS_1_QC &lt;dbl&gt;,
## #   TS_F_MDS_2_QC &lt;dbl&gt;, TS_F_MDS_3_QC &lt;dbl&gt;, TS_F_MDS_4_QC &lt;dbl&gt;,
## #   TS_F_MDS_5_QC &lt;dbl&gt;, SWC_F_MDS_1 &lt;dbl&gt;, SWC_F_MDS_2 &lt;dbl&gt;,
## #   SWC_F_MDS_3 &lt;dbl&gt;, SWC_F_MDS_4 &lt;dbl&gt;, SWC_F_MDS_1_QC &lt;dbl&gt;,
## #   SWC_F_MDS_2_QC &lt;dbl&gt;, SWC_F_MDS_3_QC &lt;dbl&gt;, SWC_F_MDS_4_QC &lt;dbl&gt;,
## #   G_F_MDS &lt;dbl&gt;, G_F_MDS_QC &lt;dbl&gt;, LE_F_MDS &lt;dbl&gt;, LE_F_MDS_QC &lt;dbl&gt;,
## #   LE_CORR &lt;dbl&gt;, LE_CORR_25 &lt;dbl&gt;, LE_CORR_75 &lt;dbl&gt;, LE_RANDUNC &lt;dbl&gt;,
## #   LE_RANDUNC_METHOD &lt;dbl&gt;, LE_RANDUNC_N &lt;dbl&gt;, LE_CORR_JOINTUNC &lt;dbl&gt;,
## #   H_F_MDS &lt;dbl&gt;, H_F_MDS_QC &lt;dbl&gt;, H_CORR &lt;dbl&gt;, H_CORR_25 &lt;dbl&gt;,
## #   H_CORR_75 &lt;dbl&gt;, H_RANDUNC &lt;dbl&gt;, H_RANDUNC_METHOD &lt;dbl&gt;,
## #   H_RANDUNC_N &lt;dbl&gt;, H_CORR_JOINTUNC &lt;dbl&gt;, EBC_CF_N &lt;dbl&gt;,
## #   EBC_CF_METHOD &lt;dbl&gt;, NIGHT &lt;dbl&gt;, NEE_CUT_REF &lt;dbl&gt;, NEE_VUT_REF &lt;dbl&gt;,
## #   NEE_CUT_REF_QC &lt;dbl&gt;, NEE_VUT_REF_QC &lt;dbl&gt;, NEE_CUT_REF_RANDUNC &lt;dbl&gt;,
## #   NEE_VUT_REF_RANDUNC &lt;dbl&gt;, NEE_CUT_REF_RANDUNC_METHOD &lt;dbl&gt;,
## #   NEE_VUT_REF_RANDUNC_METHOD &lt;dbl&gt;, NEE_CUT_REF_RANDUNC_N &lt;dbl&gt;,
## #   NEE_VUT_REF_RANDUNC_N &lt;dbl&gt;, NEE_CUT_REF_JOINTUNC &lt;dbl&gt;,
## #   NEE_VUT_REF_JOINTUNC &lt;dbl&gt;, NEE_CUT_USTAR50 &lt;dbl&gt;, NEE_VUT_USTAR50 &lt;dbl&gt;,
## #   NEE_CUT_USTAR50_QC &lt;dbl&gt;, NEE_VUT_USTAR50_QC &lt;dbl&gt;,
## #   NEE_CUT_USTAR50_RANDUNC &lt;dbl&gt;, NEE_VUT_USTAR50_RANDUNC &lt;dbl&gt;,
## #   NEE_CUT_USTAR50_RANDUNC_METHOD &lt;dbl&gt;, NEE_VUT_USTAR50_RANDUNC_METHOD &lt;dbl&gt;,
## #   …</code></pre>
<p>You have already inspected the size and dimensions of this data frame in Chapter 1 with functions, such as <code>dim()</code>, <code>nrow()</code>, <code>ncol()</code>, <code>head()</code>, <code>names()</code> etc.</p>
<p>For our further data exploration, let’s make a selection of variables to reduce the data frame we are working with. Such a selection should be guided by our understanding of the data and our own judgments. Of course, such a selection has to be documented for publications. Many of the variables in the original file record the same information but are derived with slightly different assumptions and gap-filling techniques. This is indicated by the suffices of the variable names. See <a href="https://www.nature.com/articles/s41597-020-0534-3">Pastorello et al. (2020)</a> for a comprehensive description of this. Let’s make the following choices and subset our original data for the further steps in this chapter. We select the following variables:</p>
<ul>
<li>The time information (<code>TIMESTAMP</code>)</li>
<li>All meteorological variables following the final gap-filled method (suffix <code>_F</code>)</li>
<li>A gap-filled version of the CO2 concentration (<code>CO2_F_MDS</code>)</li>
<li>The incoming photosynthetic photon flux density (<code>PPFD_IN</code>). This variable strongly covaries, but is not equal, to the shortwave incoming radiation (<code>SW_IN</code>)</li>
<li>GPP estimates are based on the nighttime decomposition method, using the “most representative” of different gap-filling versions, after having applied the variable u-star filtering method (<code>GPP_NT_VUT_REF</code>)</li>
<li>Soil water measured at different depths (variables starting with <code>SWC_F_MDS</code>)</li>
<li>Quality flag of the CO2 flux measurement (<code>NEE_VUT_REF_QC</code>, for half-hourly data: 0 = measured, 1 = good quality gap-fill, 2 = medium, 3 = poor; for daily data: the fraction of good quality gap-filled half-hourly data is used for aggregation to daily data.)</li>
<li>Other variables: Wind speed (<code>WS</code>), wind direction (<code>WD</code>), friction velocity (<code>USTAR</code>), relative humidity (<code>RH</code>)</li>
<li>All quality flags (suffix <code>QC</code>)</li>
<li>Do not use any radiation variables derived with the “JSBACH” algorithm (suffix <code>JSB</code>)</li>
<li>Flag indicating whether a time step is at night (<code>NIGHT</code>)</li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="data-wrangling.html#cb6-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="ot">&lt;-</span> hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="data-wrangling.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb6-3"><a href="data-wrangling.html#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">starts_with</span>(<span class="st">&quot;TIMESTAMP&quot;</span>),</span>
<span id="cb6-4"><a href="data-wrangling.html#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ends_with</span>(<span class="st">&quot;_F&quot;</span>),</span>
<span id="cb6-5"><a href="data-wrangling.html#cb6-5" aria-hidden="true" tabindex="-1"></a>    CO2_F_MDS,</span>
<span id="cb6-6"><a href="data-wrangling.html#cb6-6" aria-hidden="true" tabindex="-1"></a>    PPFD_IN, </span>
<span id="cb6-7"><a href="data-wrangling.html#cb6-7" aria-hidden="true" tabindex="-1"></a>    GPP_NT_VUT_REF,</span>
<span id="cb6-8"><a href="data-wrangling.html#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">starts_with</span>(<span class="st">&quot;SWC_F_MDS&quot;</span>),</span>
<span id="cb6-9"><a href="data-wrangling.html#cb6-9" aria-hidden="true" tabindex="-1"></a>    NEE_VUT_REF_QC,</span>
<span id="cb6-10"><a href="data-wrangling.html#cb6-10" aria-hidden="true" tabindex="-1"></a>    WS, WD, USTAR, RH,</span>
<span id="cb6-11"><a href="data-wrangling.html#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ends_with</span>(<span class="st">&quot;QC&quot;</span>),</span>
<span id="cb6-12"><a href="data-wrangling.html#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span><span class="fu">contains</span>(<span class="st">&quot;JSB&quot;</span>),</span>
<span id="cb6-13"><a href="data-wrangling.html#cb6-13" aria-hidden="true" tabindex="-1"></a>    NIGHT</span>
<span id="cb6-14"><a href="data-wrangling.html#cb6-14" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<p>This reduces our dataset from 235 to 68 variables. As you can see, <code>select()</code> is a powerful tool to apply multiple selection criteria on your data frame at the same time and formulate criteria based on the variable names (e.g., <code>starts_with()</code> ). Note that the selection criteria are evaluated in the order we write them in the <code>select()</code> function call. You can find the complete reference for selecting variables <a href="https://dplyr.tidyverse.org/reference/select.html">here</a>.</p>
<hr />
</div>
<div id="time-objects" class="section level4" number="3.1.1.2">
<h4><span class="header-section-number">3.1.1.2</span> Time objects</h4>
<p>The automatic interpretation of the variables <code>TIMESTAMP_START</code> and <code>TIMESTAMP_END</code> by the function <code>read_csv()</code> is not optimal:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="data-wrangling.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(hhdf<span class="sc">$</span>TIMESTAMP_START[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="data-wrangling.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.character</span>(hhdf<span class="sc">$</span>TIMESTAMP_START[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>## [1] &quot;200401010000&quot;</code></pre>
<p>As we can see, it is considered by R as a numeric variable with 12 digits (“double-precision,” occupying 64 bits in computer memory). After printing the variable as a string, we can infer that the format is: YYYYMMDDhhmm.</p>
<p><strong>Lubridate</strong> is a package designed to help processing date and time data. Knowing the format of the timestamp variables in our dataset, we can use <code>ymd_hm()</code> to convert them to actual date-time objects.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="data-wrangling.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb11-2"><a href="data-wrangling.html#cb11-2" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">ymd_hm</span>(hhdf<span class="sc">$</span>TIMESTAMP_START)</span>
<span id="cb11-3"><a href="data-wrangling.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dates)</span></code></pre></div>
<pre><code>## [1] &quot;2004-01-01 00:00:00 UTC&quot; &quot;2004-01-01 00:30:00 UTC&quot;
## [3] &quot;2004-01-01 01:00:00 UTC&quot; &quot;2004-01-01 01:30:00 UTC&quot;
## [5] &quot;2004-01-01 02:00:00 UTC&quot; &quot;2004-01-01 02:30:00 UTC&quot;</code></pre>
<p>Working with such date-time objects greatly facilitates typical operations on time series. For example, adding one day can be done by:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="data-wrangling.html#cb13-1" aria-hidden="true" tabindex="-1"></a>nextday <span class="ot">&lt;-</span> dates <span class="sc">+</span> <span class="fu">days</span>(<span class="dv">1</span>)</span>
<span id="cb13-2"><a href="data-wrangling.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nextday)</span></code></pre></div>
<pre><code>## [1] &quot;2004-01-02 00:00:00 UTC&quot; &quot;2004-01-02 00:30:00 UTC&quot;
## [3] &quot;2004-01-02 01:00:00 UTC&quot; &quot;2004-01-02 01:30:00 UTC&quot;
## [5] &quot;2004-01-02 02:00:00 UTC&quot; &quot;2004-01-02 02:30:00 UTC&quot;</code></pre>
<p>The following returns the month of each date object:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="data-wrangling.html#cb15-1" aria-hidden="true" tabindex="-1"></a>month_of_year <span class="ot">&lt;-</span> <span class="fu">month</span>(dates)</span>
<span id="cb15-2"><a href="data-wrangling.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(month_of_year)</span></code></pre></div>
<pre><code>## [1] 1 1 1 1 1 1</code></pre>
<p>The number 1 stands for the month of the year, i.e. January.</p>
<p>You can find more information on formatting dates and time within the <strong>tidyverse</strong> <a href="https://r4ds.had.co.nz/dates-and-times.html">here</a>, and a complete reference of the <strong>lubridate</strong> package is available <a href="https://lubridate.tidyverse.org/">here</a>.</p>
<p><strong>Checkpoint</strong></p>
<p>What is the month of the 10’000th value in the column ‘dates?’</p>
<p>What is the date of the 14’000th value?</p>
<p>What is the date 100 days after that? Are we still in the same year?</p>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="data-wrangling.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">month</span>(dates[<span class="dv">10000</span>])</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="data-wrangling.html#cb19-1" aria-hidden="true" tabindex="-1"></a>myday <span class="ot">&lt;-</span> dates[<span class="dv">14000</span>]</span>
<span id="cb19-2"><a href="data-wrangling.html#cb19-2" aria-hidden="true" tabindex="-1"></a>myday</span></code></pre></div>
<pre><code>## [1] &quot;2004-10-18 15:30:00 UTC&quot;</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="data-wrangling.html#cb21-1" aria-hidden="true" tabindex="-1"></a>new_day <span class="ot">&lt;-</span> myday <span class="sc">+</span> <span class="fu">days</span>(<span class="dv">100</span>)</span>
<span id="cb21-2"><a href="data-wrangling.html#cb21-2" aria-hidden="true" tabindex="-1"></a>new_day</span></code></pre></div>
<pre><code>## [1] &quot;2005-01-26 15:30:00 UTC&quot;</code></pre>
<p>No, it is not the same year!</p>
<hr />
</div>
<div id="variable-re--definition" class="section level4" number="3.1.1.3">
<h4><span class="header-section-number">3.1.1.3</span> Variable (re-) definition</h4>
<p>We haven’t applied the conversion of the timestamp columns to date-time objects in our data frame <code>hhdf</code> yet. In base-R, with the package <code>lubridate</code> loaded, we would do this by:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="data-wrangling.html#cb23-1" aria-hidden="true" tabindex="-1"></a>hhdf<span class="sc">$</span>TIMESTAMP_START <span class="ot">&lt;-</span> <span class="fu">ymd_hm</span>(hhdf<span class="sc">$</span>TIMESTAMP_START)</span></code></pre></div>
<p>Modifying existing or creating new variables (columns) in a data frame is done in the tidyverse using the function <code>mutate()</code>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="data-wrangling.html#cb24-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="data-wrangling.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TIMESTAMP_START =</span> <span class="fu">ymd_hm</span>(TIMESTAMP_START))</span></code></pre></div>
<p>Of course, mutating both our timestamp variables could be written as <code>mutate(TIMESTAMP_START = ymd_hm(TIMESTAMP_START), TIMESTAMP_END = ymd_hm(TIMESTAMP_END))</code>. Sometimes, such multiple-variable mutate statements can get quite long. A nice short version of this can be implemented using <code>mutate_at()</code> which applies a condition to the variable name on which the mutating is to be done:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="data-wrangling.html#cb25-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="data-wrangling.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(<span class="fu">starts_with</span>(<span class="st">&quot;TIMESTAMP_&quot;</span>)), ymd_hm)</span></code></pre></div>
<pre><code>## # A tibble: 192,864 x 65
##    TIMESTAMP_START     TIMESTAMP_END        TA_F SW_IN_F LW_IN_F VPD_F  PA_F
##    &lt;dttm&gt;              &lt;dttm&gt;              &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 2004-01-01 00:00:00 2004-01-01 00:30:00 -2.22       0    304. 0.562  93.3
##  2 2004-01-01 00:30:00 2004-01-01 01:00:00 -2.25       0    304. 0.56   93.3
##  3 2004-01-01 01:00:00 2004-01-01 01:30:00 -2.28       0    281. 0.558  93.3
##  4 2004-01-01 01:30:00 2004-01-01 02:00:00 -2.50       0    281. 0.565  93.3
##  5 2004-01-01 02:00:00 2004-01-01 02:30:00 -2.72       0    281. 0.571  93.3
##  6 2004-01-01 02:30:00 2004-01-01 03:00:00 -2.94       0    281. 0.577  93.3
##  7 2004-01-01 03:00:00 2004-01-01 03:30:00 -3.17       0    281. 0.584  93.2
##  8 2004-01-01 03:30:00 2004-01-01 04:00:00 -3.39       0    281. 0.59   93.2
##  9 2004-01-01 04:00:00 2004-01-01 04:30:00 -3.61       0    264. 0.596  93.2
## 10 2004-01-01 04:30:00 2004-01-01 05:00:00 -3.59       0    264. 0.606  93.2
## # … with 192,854 more rows, and 58 more variables: P_F &lt;dbl&gt;, WS_F &lt;dbl&gt;,
## #   CO2_F_MDS &lt;dbl&gt;, PPFD_IN &lt;dbl&gt;, GPP_NT_VUT_REF &lt;dbl&gt;, SWC_F_MDS_1 &lt;dbl&gt;,
## #   SWC_F_MDS_2 &lt;dbl&gt;, SWC_F_MDS_3 &lt;dbl&gt;, SWC_F_MDS_4 &lt;dbl&gt;,
## #   SWC_F_MDS_1_QC &lt;dbl&gt;, SWC_F_MDS_2_QC &lt;dbl&gt;, SWC_F_MDS_3_QC &lt;dbl&gt;,
## #   SWC_F_MDS_4_QC &lt;dbl&gt;, NEE_VUT_REF_QC &lt;dbl&gt;, WS &lt;dbl&gt;, WD &lt;dbl&gt;,
## #   USTAR &lt;dbl&gt;, RH &lt;dbl&gt;, TA_F_MDS_QC &lt;dbl&gt;, TA_F_QC &lt;dbl&gt;,
## #   SW_IN_F_MDS_QC &lt;dbl&gt;, SW_IN_F_QC &lt;dbl&gt;, LW_IN_F_MDS_QC &lt;dbl&gt;,
## #   LW_IN_F_QC &lt;dbl&gt;, VPD_F_MDS_QC &lt;dbl&gt;, VPD_F_QC &lt;dbl&gt;, PA_F_QC &lt;dbl&gt;,
## #   P_F_QC &lt;dbl&gt;, WS_F_QC &lt;dbl&gt;, CO2_F_MDS_QC &lt;dbl&gt;, TS_F_MDS_1_QC &lt;dbl&gt;,
## #   TS_F_MDS_2_QC &lt;dbl&gt;, TS_F_MDS_3_QC &lt;dbl&gt;, TS_F_MDS_4_QC &lt;dbl&gt;,
## #   TS_F_MDS_5_QC &lt;dbl&gt;, G_F_MDS_QC &lt;dbl&gt;, LE_F_MDS_QC &lt;dbl&gt;, H_F_MDS_QC &lt;dbl&gt;,
## #   NEE_CUT_REF_QC &lt;dbl&gt;, NEE_CUT_USTAR50_QC &lt;dbl&gt;, NEE_VUT_USTAR50_QC &lt;dbl&gt;,
## #   NEE_CUT_MEAN_QC &lt;dbl&gt;, NEE_VUT_MEAN_QC &lt;dbl&gt;, NEE_CUT_05_QC &lt;dbl&gt;,
## #   NEE_CUT_16_QC &lt;dbl&gt;, NEE_CUT_25_QC &lt;dbl&gt;, NEE_CUT_50_QC &lt;dbl&gt;,
## #   NEE_CUT_75_QC &lt;dbl&gt;, NEE_CUT_84_QC &lt;dbl&gt;, NEE_CUT_95_QC &lt;dbl&gt;,
## #   NEE_VUT_05_QC &lt;dbl&gt;, NEE_VUT_16_QC &lt;dbl&gt;, NEE_VUT_25_QC &lt;dbl&gt;,
## #   NEE_VUT_50_QC &lt;dbl&gt;, NEE_VUT_75_QC &lt;dbl&gt;, NEE_VUT_84_QC &lt;dbl&gt;,
## #   NEE_VUT_95_QC &lt;dbl&gt;, NIGHT &lt;dbl&gt;</code></pre>
<p>A complete reference to <code>mutate()</code> is available <a href="https://r4ds.had.co.nz/transform.html#add-new-variables-with-mutate">here</a>.</p>
<hr />
</div>
<div id="cleaning-and-gap-filling" class="section level4" number="3.1.1.4">
<h4><span class="header-section-number">3.1.1.4</span> Cleaning and gap-filling</h4>
<p>For many applications, we want to filter the data so that the values of particular variables satisfy certain conditions. For example, if we have a good reason for excluding certain data points, we should do so. The <code>dplyr</code> function which should be used for such tasks is <code>filter()</code>.
As a first argument, it takes the data frame to which the filtering is applied. Remember that when using pipes (<code>%&gt;%</code>), the first argument is not spelled out, but is taken from what’s coming from the left of <code>%&gt;%</code>.
The second and subsequent arguments are the expressions that specify the criterion for filtering. R provides the standard suite:</p>
<ul>
<li><code>&gt;</code> greater than</li>
<li><code>&gt;=</code> greater or equal than</li>
<li><code>&lt;</code> smaller than</li>
<li><code>&lt;=</code> smaller or equal than</li>
<li><code>!=</code>: not equal</li>
<li><code>==</code>: equal</li>
</ul>
<p>Multiple filtering criteria can be combined with logical (Boolean) operators:</p>
<ul>
<li><code>&amp;</code>: logical and</li>
<li><code>|</code>: logical or</li>
<li><code>!</code> logical not</li>
</ul>
<p>Sometimes, we want to check whether a variable takes any of a larger set of values. For example, if we wanted to check whether a date, given by the month of the year, is in meteorological spring, we could write something like <code>filter(df, month == 3 | month == 4 | month == 5)</code>. However, this is a bit cumbersome. A shorter and much more powerful syntax is <code>filter(df, month %in% c(3,4,5))</code>. The <code>%in%</code> operator takes each element of what’s on its left-hand-side and evaluates whether it is equal to any element of what’s on its right-hand-side.</p>
<p>Enough theory! Let’s turn to our dataset and filter some GPP data based on its corresponding data quality information. This type of information is crucial as it allows us, e.g., to avoid using “bad” data for training a machine learning algorithm. In our dataset, the quality control flag for <code>GPP_NT_VUT_REF</code> is provided by <code>NEE_VUT_REF_QC</code>. Its corresponding codes are:</p>
<p>0 = measured<br />
1 = good quality gap-filled<br />
2 = medium<br />
3 = poor</p>
<p>To take only actually measured or good quality gap-filled GPP data (0 and 1), we can do:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="data-wrangling.html#cb27-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="data-wrangling.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NEE_VUT_REF_QC <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> NEE_VUT_REF_QC <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div>
<p>As you know now, we can also write:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="data-wrangling.html#cb28-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="data-wrangling.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NEE_VUT_REF_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span></code></pre></div>
<p><code>filter()</code> completely removes rows (note the information about number of rows printed above). In some cases this is undesired and it is preferred to replace bad-quality values with <code>NA</code> (“not available”). <code>NA</code> is a “code” that lets R understand that the value is missing. Almost all operations on values where at least one value is <code>NA</code> also return <code>NA</code>. For example:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="data-wrangling.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="cn">NA</span>))</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>To remove all missing values before evaluating the function, the common argument to set in the respective function call is <code>na.rm</code>. By default, it’s usually set to <code>FALSE</code>, but we can do:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="data-wrangling.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="cn">NA</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 1.5</code></pre>
<p>For cases where we don’t want to drop entire rows, but just replace certain values with <code>NA</code>, we can use <code>mutate()</code> instead and apply the function <code>ifelse()</code> which takes a logical expression that evaluates to either <code>TRUE</code> or <code>FALSE</code> as the first argument, and returns the second argument if the expression evaluates to <code>TRUE</code> or the third argument if it evaluates to <code>FALSE</code>. In our case, we can do:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="data-wrangling.html#cb33-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="data-wrangling.html#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GPP_NT_VUT_REF =</span> <span class="fu">ifelse</span>(NEE_VUT_REF_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), GPP_NT_VUT_REF, <span class="cn">NA</span>))</span></code></pre></div>
<p>Some values in our data frame are -9999. When reading the documentation of the dataset, we learn that this is the code for missing data. We can replace such values in any column (except the columns starting with <code>"TIMESTAMP_"</code>) with <code>NA</code> using the handy function <code>na_if()</code>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="data-wrangling.html#cb34-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="data-wrangling.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="sc">-</span><span class="dv">9999</span>)</span></code></pre></div>
<pre><code>## # A tibble: 192,864 x 65
##    TIMESTAMP_START TIMESTAMP_END  TA_F SW_IN_F LW_IN_F VPD_F  PA_F   P_F  WS_F
##              &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1    200401010000  200401010030 -2.22       0    304. 0.562  93.3 0.014  2.2 
##  2    200401010030  200401010100 -2.25       0    304. 0.56   93.3 0.014  2.13
##  3    200401010100  200401010130 -2.28       0    281. 0.558  93.3 0      2.06
##  4    200401010130  200401010200 -2.50       0    281. 0.565  93.3 0      1.96
##  5    200401010200  200401010230 -2.72       0    281. 0.571  93.3 0      1.85
##  6    200401010230  200401010300 -2.94       0    281. 0.577  93.3 0      1.75
##  7    200401010300  200401010330 -3.17       0    281. 0.584  93.2 0      1.64
##  8    200401010330  200401010400 -3.39       0    281. 0.59   93.2 0      1.54
##  9    200401010400  200401010430 -3.61       0    264. 0.596  93.2 0      1.43
## 10    200401010430  200401010500 -3.59       0    264. 0.606  93.2 0      1.41
## # … with 192,854 more rows, and 56 more variables: CO2_F_MDS &lt;dbl&gt;,
## #   PPFD_IN &lt;dbl&gt;, GPP_NT_VUT_REF &lt;dbl&gt;, SWC_F_MDS_1 &lt;dbl&gt;, SWC_F_MDS_2 &lt;dbl&gt;,
## #   SWC_F_MDS_3 &lt;dbl&gt;, SWC_F_MDS_4 &lt;dbl&gt;, SWC_F_MDS_1_QC &lt;dbl&gt;,
## #   SWC_F_MDS_2_QC &lt;dbl&gt;, SWC_F_MDS_3_QC &lt;dbl&gt;, SWC_F_MDS_4_QC &lt;dbl&gt;,
## #   NEE_VUT_REF_QC &lt;dbl&gt;, WS &lt;dbl&gt;, WD &lt;dbl&gt;, USTAR &lt;dbl&gt;, RH &lt;dbl&gt;,
## #   TA_F_MDS_QC &lt;dbl&gt;, TA_F_QC &lt;dbl&gt;, SW_IN_F_MDS_QC &lt;dbl&gt;, SW_IN_F_QC &lt;dbl&gt;,
## #   LW_IN_F_MDS_QC &lt;dbl&gt;, LW_IN_F_QC &lt;dbl&gt;, VPD_F_MDS_QC &lt;dbl&gt;, VPD_F_QC &lt;dbl&gt;,
## #   PA_F_QC &lt;dbl&gt;, P_F_QC &lt;dbl&gt;, WS_F_QC &lt;dbl&gt;, CO2_F_MDS_QC &lt;dbl&gt;,
## #   TS_F_MDS_1_QC &lt;dbl&gt;, TS_F_MDS_2_QC &lt;dbl&gt;, TS_F_MDS_3_QC &lt;dbl&gt;,
## #   TS_F_MDS_4_QC &lt;dbl&gt;, TS_F_MDS_5_QC &lt;dbl&gt;, G_F_MDS_QC &lt;dbl&gt;,
## #   LE_F_MDS_QC &lt;dbl&gt;, H_F_MDS_QC &lt;dbl&gt;, NEE_CUT_REF_QC &lt;dbl&gt;,
## #   NEE_CUT_USTAR50_QC &lt;dbl&gt;, NEE_VUT_USTAR50_QC &lt;dbl&gt;, NEE_CUT_MEAN_QC &lt;dbl&gt;,
## #   NEE_VUT_MEAN_QC &lt;dbl&gt;, NEE_CUT_05_QC &lt;dbl&gt;, NEE_CUT_16_QC &lt;dbl&gt;,
## #   NEE_CUT_25_QC &lt;dbl&gt;, NEE_CUT_50_QC &lt;dbl&gt;, NEE_CUT_75_QC &lt;dbl&gt;,
## #   NEE_CUT_84_QC &lt;dbl&gt;, NEE_CUT_95_QC &lt;dbl&gt;, NEE_VUT_05_QC &lt;dbl&gt;,
## #   NEE_VUT_16_QC &lt;dbl&gt;, NEE_VUT_25_QC &lt;dbl&gt;, NEE_VUT_50_QC &lt;dbl&gt;,
## #   NEE_VUT_75_QC &lt;dbl&gt;, NEE_VUT_84_QC &lt;dbl&gt;, NEE_VUT_95_QC &lt;dbl&gt;, NIGHT &lt;dbl&gt;</code></pre>
<p>If your data has <code>NA</code> values and you chose to drop entire rows if they contain <code>NA</code>, you can use another handy function <code>drop_na()</code>:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="data-wrangling.html#cb36-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="data-wrangling.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="sc">-</span><span class="dv">9999</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="data-wrangling.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span></code></pre></div>
<pre><code>## # A tibble: 0 x 65
## # … with 65 variables: TIMESTAMP_START &lt;dbl&gt;, TIMESTAMP_END &lt;dbl&gt;, TA_F &lt;dbl&gt;,
## #   SW_IN_F &lt;dbl&gt;, LW_IN_F &lt;dbl&gt;, VPD_F &lt;dbl&gt;, PA_F &lt;dbl&gt;, P_F &lt;dbl&gt;,
## #   WS_F &lt;dbl&gt;, CO2_F_MDS &lt;dbl&gt;, PPFD_IN &lt;dbl&gt;, GPP_NT_VUT_REF &lt;dbl&gt;,
## #   SWC_F_MDS_1 &lt;dbl&gt;, SWC_F_MDS_2 &lt;dbl&gt;, SWC_F_MDS_3 &lt;dbl&gt;, SWC_F_MDS_4 &lt;dbl&gt;,
## #   SWC_F_MDS_1_QC &lt;dbl&gt;, SWC_F_MDS_2_QC &lt;dbl&gt;, SWC_F_MDS_3_QC &lt;dbl&gt;,
## #   SWC_F_MDS_4_QC &lt;dbl&gt;, NEE_VUT_REF_QC &lt;dbl&gt;, WS &lt;dbl&gt;, WD &lt;dbl&gt;,
## #   USTAR &lt;dbl&gt;, RH &lt;dbl&gt;, TA_F_MDS_QC &lt;dbl&gt;, TA_F_QC &lt;dbl&gt;,
## #   SW_IN_F_MDS_QC &lt;dbl&gt;, SW_IN_F_QC &lt;dbl&gt;, LW_IN_F_MDS_QC &lt;dbl&gt;,
## #   LW_IN_F_QC &lt;dbl&gt;, VPD_F_MDS_QC &lt;dbl&gt;, VPD_F_QC &lt;dbl&gt;, PA_F_QC &lt;dbl&gt;,
## #   P_F_QC &lt;dbl&gt;, WS_F_QC &lt;dbl&gt;, CO2_F_MDS_QC &lt;dbl&gt;, TS_F_MDS_1_QC &lt;dbl&gt;,
## #   TS_F_MDS_2_QC &lt;dbl&gt;, TS_F_MDS_3_QC &lt;dbl&gt;, TS_F_MDS_4_QC &lt;dbl&gt;,
## #   TS_F_MDS_5_QC &lt;dbl&gt;, G_F_MDS_QC &lt;dbl&gt;, LE_F_MDS_QC &lt;dbl&gt;, H_F_MDS_QC &lt;dbl&gt;,
## #   NEE_CUT_REF_QC &lt;dbl&gt;, NEE_CUT_USTAR50_QC &lt;dbl&gt;, NEE_VUT_USTAR50_QC &lt;dbl&gt;,
## #   NEE_CUT_MEAN_QC &lt;dbl&gt;, NEE_VUT_MEAN_QC &lt;dbl&gt;, NEE_CUT_05_QC &lt;dbl&gt;,
## #   NEE_CUT_16_QC &lt;dbl&gt;, NEE_CUT_25_QC &lt;dbl&gt;, NEE_CUT_50_QC &lt;dbl&gt;,
## #   NEE_CUT_75_QC &lt;dbl&gt;, NEE_CUT_84_QC &lt;dbl&gt;, NEE_CUT_95_QC &lt;dbl&gt;,
## #   NEE_VUT_05_QC &lt;dbl&gt;, NEE_VUT_16_QC &lt;dbl&gt;, NEE_VUT_25_QC &lt;dbl&gt;,
## #   NEE_VUT_50_QC &lt;dbl&gt;, NEE_VUT_75_QC &lt;dbl&gt;, NEE_VUT_84_QC &lt;dbl&gt;,
## #   NEE_VUT_95_QC &lt;dbl&gt;, NIGHT &lt;dbl&gt;</code></pre>
<p><strong>Checkpoint</strong></p>
<p>If your data has <code>NA</code> values and you chose to drop entire rows if they contain <code>NA</code>, you can use another handy function <code>drop_na()</code>.</p>
<p>Convert the matrix below to a dataframe and use <code>drop_na()</code>. See what happens and compare it to
the results of other functions such as <code>is.na()</code>, <code>complete.cases()</code>, <code>na.omit()</code>.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="data-wrangling.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Run this code</span></span>
<span id="cb38-2"><a href="data-wrangling.html#cb38-2" aria-hidden="true" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">20</span>,<span class="cn">NA</span>,<span class="dv">2000</span>)</span>
<span id="cb38-3"><a href="data-wrangling.html#cb38-3" aria-hidden="true" tabindex="-1"></a>a2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="cn">NA</span>)</span>
<span id="cb38-4"><a href="data-wrangling.html#cb38-4" aria-hidden="true" tabindex="-1"></a>a3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">22</span>,<span class="dv">33</span>,<span class="dv">44</span>,<span class="dv">55</span>)</span>
<span id="cb38-5"><a href="data-wrangling.html#cb38-5" aria-hidden="true" tabindex="-1"></a>NA_matrix <span class="ot">&lt;-</span> <span class="fu">rbind</span>(a1,a2,a3)</span></code></pre></div>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="data-wrangling.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can ignore paste0(), we just added it to help you keep track of the solution to each function.</span></span>
<span id="cb39-2"><a href="data-wrangling.html#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;drop_na():&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;drop_na():&quot;</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="data-wrangling.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(NA_matrix) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span></code></pre></div>
<pre><code>##    X1 X2 X3 X4
## a3 22 33 44 55</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="data-wrangling.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;complete.cases():&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;complete.cases():&quot;</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="data-wrangling.html#cb45-1" aria-hidden="true" tabindex="-1"></a>NA_matrix <span class="sc">%&gt;%</span> <span class="fu">complete.cases</span>()</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="data-wrangling.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;is.na():&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;is.na():&quot;</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="data-wrangling.html#cb49-1" aria-hidden="true" tabindex="-1"></a>NA_matrix <span class="sc">%&gt;%</span> <span class="fu">is.na</span>()</span></code></pre></div>
<pre><code>##     [,1]  [,2]  [,3]  [,4]
## a1 FALSE FALSE  TRUE FALSE
## a2 FALSE FALSE FALSE  TRUE
## a3 FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="data-wrangling.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;na.omit():&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;na.omit():&quot;</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="data-wrangling.html#cb53-1" aria-hidden="true" tabindex="-1"></a>NA_matrix <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span></code></pre></div>
<pre><code>##    [,1] [,2] [,3] [,4]
## a3   22   33   44   55
## attr(,&quot;na.action&quot;)
## a1 a2 
##  1  2 
## attr(,&quot;class&quot;)
## [1] &quot;omit&quot;</code></pre>
<hr />
</div>
<div id="functions" class="section level4" number="3.1.1.5">
<h4><span class="header-section-number">3.1.1.5</span> Functions</h4>
<p>Whenever possible, we should combine multiple processing steps that naturally belong together. That is, the same sequence of steps may be applied to multiple datasets that have the same structure (variable names, etc.). It makes sense to combine steps into a single function and we can re-use the same function, without having to repeatedly write the same code. Let’s write our first function and implement the data cleaning steps we described above. It may look a little intimidating but don’t worry it is just every step above added sequentially.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="data-wrangling.html#cb55-1" aria-hidden="true" tabindex="-1"></a>clean_fluxnet_hh <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb55-2"><a href="data-wrangling.html#cb55-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb55-3"><a href="data-wrangling.html#cb55-3" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb55-4"><a href="data-wrangling.html#cb55-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb55-5"><a href="data-wrangling.html#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="do">## select only the variables we&#39;re interested in</span></span>
<span id="cb55-6"><a href="data-wrangling.html#cb55-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(</span>
<span id="cb55-7"><a href="data-wrangling.html#cb55-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">starts_with</span>(<span class="st">&quot;TIMESTAMP&quot;</span>),</span>
<span id="cb55-8"><a href="data-wrangling.html#cb55-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ends_with</span>(<span class="st">&quot;_F&quot;</span>),</span>
<span id="cb55-9"><a href="data-wrangling.html#cb55-9" aria-hidden="true" tabindex="-1"></a>      CO2_F_MDS,</span>
<span id="cb55-10"><a href="data-wrangling.html#cb55-10" aria-hidden="true" tabindex="-1"></a>      PPFD_IN, </span>
<span id="cb55-11"><a href="data-wrangling.html#cb55-11" aria-hidden="true" tabindex="-1"></a>      GPP_NT_VUT_REF,</span>
<span id="cb55-12"><a href="data-wrangling.html#cb55-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">starts_with</span>(<span class="st">&quot;SWC_F_MDS&quot;</span>),</span>
<span id="cb55-13"><a href="data-wrangling.html#cb55-13" aria-hidden="true" tabindex="-1"></a>      NEE_VUT_REF_QC,</span>
<span id="cb55-14"><a href="data-wrangling.html#cb55-14" aria-hidden="true" tabindex="-1"></a>      WS, WD, USTAR, RH,</span>
<span id="cb55-15"><a href="data-wrangling.html#cb55-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ends_with</span>(<span class="st">&quot;QC&quot;</span>),</span>
<span id="cb55-16"><a href="data-wrangling.html#cb55-16" aria-hidden="true" tabindex="-1"></a>      <span class="sc">-</span><span class="fu">contains</span>(<span class="st">&quot;JSB&quot;</span>),</span>
<span id="cb55-17"><a href="data-wrangling.html#cb55-17" aria-hidden="true" tabindex="-1"></a>      NIGHT</span>
<span id="cb55-18"><a href="data-wrangling.html#cb55-18" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">%&gt;%</span> </span>
<span id="cb55-19"><a href="data-wrangling.html#cb55-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb55-20"><a href="data-wrangling.html#cb55-20" aria-hidden="true" tabindex="-1"></a>    <span class="do">## convert to nice time object</span></span>
<span id="cb55-21"><a href="data-wrangling.html#cb55-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_at</span>(<span class="fu">vars</span>(<span class="fu">starts_with</span>(<span class="st">&quot;TIMESTAMP_&quot;</span>)), ymd_hm) <span class="sc">%&gt;%</span> </span>
<span id="cb55-22"><a href="data-wrangling.html#cb55-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb55-23"><a href="data-wrangling.html#cb55-23" aria-hidden="true" tabindex="-1"></a>    <span class="do">## set bad data to NA for multiple variables</span></span>
<span id="cb55-24"><a href="data-wrangling.html#cb55-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb55-25"><a href="data-wrangling.html#cb55-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">GPP_NT_VUT_REF =</span> <span class="fu">ifelse</span>(NEE_VUT_REF_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), GPP_NT_VUT_REF, <span class="cn">NA</span>),</span>
<span id="cb55-26"><a href="data-wrangling.html#cb55-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">TA_F =</span> <span class="fu">ifelse</span>(TA_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), TA_F, <span class="cn">NA</span>),</span>
<span id="cb55-27"><a href="data-wrangling.html#cb55-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">SW_IN_F =</span> <span class="fu">ifelse</span>(SW_IN_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), SW_IN_F, <span class="cn">NA</span>),</span>
<span id="cb55-28"><a href="data-wrangling.html#cb55-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">LW_IN_F =</span> <span class="fu">ifelse</span>(LW_IN_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), LW_IN_F, <span class="cn">NA</span>),   <span class="co"># relaxing filter criterion</span></span>
<span id="cb55-29"><a href="data-wrangling.html#cb55-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">VPD_F =</span> <span class="fu">ifelse</span>(VPD_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), VPD_F, <span class="cn">NA</span>),</span>
<span id="cb55-30"><a href="data-wrangling.html#cb55-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">PA_F =</span> <span class="fu">ifelse</span>(PA_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), PA_F, <span class="cn">NA</span>),   <span class="co"># relaxing filter criterion</span></span>
<span id="cb55-31"><a href="data-wrangling.html#cb55-31" aria-hidden="true" tabindex="-1"></a>      <span class="at">P_F =</span> <span class="fu">ifelse</span>(P_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), P_F, <span class="cn">NA</span>),   <span class="co"># relaxing filter criterion</span></span>
<span id="cb55-32"><a href="data-wrangling.html#cb55-32" aria-hidden="true" tabindex="-1"></a>      <span class="at">WS_F =</span> <span class="fu">ifelse</span>(WS_F_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), WS_F, <span class="cn">NA</span>),</span>
<span id="cb55-33"><a href="data-wrangling.html#cb55-33" aria-hidden="true" tabindex="-1"></a>      <span class="at">CO2_F_MDS =</span> <span class="fu">ifelse</span>(CO2_F_MDS_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), CO2_F_MDS, <span class="cn">NA</span>),</span>
<span id="cb55-34"><a href="data-wrangling.html#cb55-34" aria-hidden="true" tabindex="-1"></a>      <span class="at">SWC_F_MDS_1 =</span> <span class="fu">ifelse</span>(SWC_F_MDS_1_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), SWC_F_MDS_1, <span class="cn">NA</span>),</span>
<span id="cb55-35"><a href="data-wrangling.html#cb55-35" aria-hidden="true" tabindex="-1"></a>      <span class="at">SWC_F_MDS_2 =</span> <span class="fu">ifelse</span>(SWC_F_MDS_2_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), SWC_F_MDS_2, <span class="cn">NA</span>),</span>
<span id="cb55-36"><a href="data-wrangling.html#cb55-36" aria-hidden="true" tabindex="-1"></a>      <span class="at">SWC_F_MDS_3 =</span> <span class="fu">ifelse</span>(SWC_F_MDS_3_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), SWC_F_MDS_3, <span class="cn">NA</span>),</span>
<span id="cb55-37"><a href="data-wrangling.html#cb55-37" aria-hidden="true" tabindex="-1"></a>      <span class="at">SWC_F_MDS_4 =</span> <span class="fu">ifelse</span>(SWC_F_MDS_4_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), SWC_F_MDS_4, <span class="cn">NA</span>)</span>
<span id="cb55-38"><a href="data-wrangling.html#cb55-38" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">%&gt;%</span></span>
<span id="cb55-39"><a href="data-wrangling.html#cb55-39" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb55-40"><a href="data-wrangling.html#cb55-40" aria-hidden="true" tabindex="-1"></a>    <span class="do">## set all -9999 to NA</span></span>
<span id="cb55-41"><a href="data-wrangling.html#cb55-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">na_if</span>(<span class="sc">-</span><span class="dv">9999</span>) <span class="sc">%&gt;%</span></span>
<span id="cb55-42"><a href="data-wrangling.html#cb55-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb55-43"><a href="data-wrangling.html#cb55-43" aria-hidden="true" tabindex="-1"></a>    <span class="do">## drop QC variables (no longer needed), except NEE_VUT_REF_QC</span></span>
<span id="cb55-44"><a href="data-wrangling.html#cb55-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">&quot;_QC&quot;</span>), NEE_VUT_REF_QC)</span>
<span id="cb55-45"><a href="data-wrangling.html#cb55-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb55-46"><a href="data-wrangling.html#cb55-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb55-47"><a href="data-wrangling.html#cb55-47" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The cell above contained only the function definition. That is, it defines what the function does when applied. Next, we can apply it to our object, the data frame <code>hhdf</code>:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="data-wrangling.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="do">## apply our cleaning function</span></span>
<span id="cb56-2"><a href="data-wrangling.html#cb56-2" aria-hidden="true" tabindex="-1"></a>hhdf <span class="ot">&lt;-</span> hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="data-wrangling.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_fluxnet_hh</span>()</span></code></pre></div>
<p>Now that we created a function that lives comfortably in the tidyverse. That is: it takes a data frame as its first (and here only) argument, and it returns a data frame as its output. That’s why we can write it in combination with the pipe operator as we did above. This was a very condensed introduction to functions. You’ll find more information <a href="https://r4ds.had.co.nz/functions.html">here</a>.</p>
<p>After we’ve done the data cleaning by imputing <code>NA</code> for bad quality data, we should check again, how much data we are now left with and how big the data gaps for different variables are. Knowing this is particularly important when using the data later in combination with machine learning algorithms that cannot deal with missing data. In such cases, rows where at least one value is missing (<code>NA</code>), have to be discarded entirely. This may not be desirable if it reduces the number of rows too drastically.</p>
<p>We can calculate the number of missing data in each row with the following code (Don’t worry, this is just a demonstration and we’ll explain this type of aggregation later in this chapter):</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="data-wrangling.html#cb57-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="data-wrangling.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">funs</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.))<span class="sc">/</span><span class="fu">length</span>(.))) <span class="sc">%&gt;%</span> </span>
<span id="cb57-3"><a href="data-wrangling.html#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>()</span></code></pre></div>
<pre><code>##                      [,1]
## TIMESTAMP_START  0.000000
## TIMESTAMP_END    0.000000
## TA_F             6.973308
## SW_IN_F          7.069749
## LW_IN_F          0.000000
## VPD_F            6.973308
## PA_F             0.000000
## P_F              0.000000
## WS_F             5.004563
## CO2_F_MDS        3.122926
## PPFD_IN          7.143894
## GPP_NT_VUT_REF   8.675543
## SWC_F_MDS_1     16.616372
## SWC_F_MDS_2     10.997905
## SWC_F_MDS_3     11.025386
## SWC_F_MDS_4     27.193255
## WS               5.004563
## WD               4.434213
## USTAR           21.273021
## RH               7.565435
## NIGHT            0.000000
## NEE_VUT_REF_QC   0.000000</code></pre>
<p>We can see, that &gt;20% of all values for <code>SWC_F_MDS_4</code> and <code>USTAR</code> are missing. Let’s no longer include these variables in the subsequent steps.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="data-wrangling.html#cb59-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="ot">&lt;-</span> hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="data-wrangling.html#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>USTAR, <span class="sc">-</span>SWC_F_MDS_4)</span></code></pre></div>
<p>We can also visualise the fraction of missing data after applying our data cleaning step, using the <code>vis_miss</code> from the <strong>visdat</strong> package.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="data-wrangling.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(visdat)</span>
<span id="cb60-2"><a href="data-wrangling.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(</span>
<span id="cb60-3"><a href="data-wrangling.html#cb60-3" aria-hidden="true" tabindex="-1"></a>  hhdf,</span>
<span id="cb60-4"><a href="data-wrangling.html#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="cn">FALSE</span>, </span>
<span id="cb60-5"><a href="data-wrangling.html#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">warn_large_data =</span> <span class="cn">FALSE</span></span>
<span id="cb60-6"><a href="data-wrangling.html#cb60-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>This looks reasonable now. Let’s save this as a RData file for later use.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="data-wrangling.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(hhdf, <span class="at">file =</span> <span class="st">&quot;./data/FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2014_1-3_CLEAN.RData&quot;</span>)</span></code></pre></div>
<p><strong>Checkpoint</strong></p>
<p>Try writing a simple function that will calculate the sum, maximum and minimum of the vector <em>some_numbers</em>.
(As a bonus have the result print out a sentence saying: “The sum is: x , the maximum is: y and the minimum is: z.”)</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="data-wrangling.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run this code:</span></span>
<span id="cb62-2"><a href="data-wrangling.html#cb62-2" aria-hidden="true" tabindex="-1"></a>some_numbers <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">15</span>, <span class="dv">436</span>, <span class="dv">728</span>, <span class="dv">1111</span>)</span></code></pre></div>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="data-wrangling.html#cb63-1" aria-hidden="true" tabindex="-1"></a>function_exercise <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb63-2"><a href="data-wrangling.html#cb63-2" aria-hidden="true" tabindex="-1"></a>    sum <span class="ot">&lt;-</span> <span class="fu">sum</span>(x)</span>
<span id="cb63-3"><a href="data-wrangling.html#cb63-3" aria-hidden="true" tabindex="-1"></a>    max <span class="ot">&lt;-</span> <span class="fu">max</span>(x)</span>
<span id="cb63-4"><a href="data-wrangling.html#cb63-4" aria-hidden="true" tabindex="-1"></a>    min <span class="ot">&lt;-</span> <span class="fu">min</span>(x)</span>
<span id="cb63-5"><a href="data-wrangling.html#cb63-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb63-6"><a href="data-wrangling.html#cb63-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">&quot;The sum is:&quot;</span>, sum, <span class="st">&quot;, the maximum is:&quot;</span>, max, <span class="st">&quot; and the minimum is:&quot;</span>, min, <span class="st">&quot;.</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb63-7"><a href="data-wrangling.html#cb63-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb63-8"><a href="data-wrangling.html#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-9"><a href="data-wrangling.html#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="fu">function_exercise</span>(some_numbers)</span></code></pre></div>
<pre><code>## The sum is: 2300 , the maximum is: 1111  and the minimum is: 10 .</code></pre>
<hr />
</div>
<div id="data-visualisation-i" class="section level4" number="3.1.1.6">
<h4><span class="header-section-number">3.1.1.6</span> Data visualisation I</h4>
<p>Looking at data is an integral part of data processing. You have already encountered a simple x-y line plot, created with base-R, in Chapter 1. We’re working with time series data. A natural first visualisation step is therefore to plot our variables against time, for example, <code>GPP_NT_VUT_REF</code> versus <code>TIMESTAMP_START</code>:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="data-wrangling.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hhdf<span class="sc">$</span>TIMESTAMP_START, hhdf<span class="sc">$</span>GPP_NT_VUT_REF, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>As introduced in Video 2c, <strong>ggplot2</strong> offers a powerful and (at least after an initial brain-effort) intuitive syntax for building data visualisations in a versatile, elegant, and efficient way. It defines a complete <a href="https://ggplot2.tidyverse.org/reference/">“grammar of graphics”</a> (thus the name ggplot), which allows you to consistently apply the same syntax for different purposes.</p>
<p>We create the same line plot as done above with <code>geom_line()</code>:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="data-wrangling.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb66-2"><a href="data-wrangling.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> hhdf, <span class="fu">aes</span>(<span class="at">x =</span> TIMESTAMP_START, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb66-3"><a href="data-wrangling.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 4342 row(s) containing missing values (geom_path).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>This is a dense plot and we cannot distinguish patterns because variations in GPP happen at time scales that are too narrow for displaying 14 years in one plot. Of course, GPP varies throughout a day just as much as it varies throughout a season. To see this, we can zoom into a narrower time span (and apply some plot customization at the same time for illustration):</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="data-wrangling.html#cb68-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="data-wrangling.html#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">24000</span><span class="sc">:</span><span class="dv">25000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb68-3"><a href="data-wrangling.html#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TIMESTAMP_START, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb68-4"><a href="data-wrangling.html#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;tomato&quot;</span>) <span class="sc">+</span></span>
<span id="cb68-5"><a href="data-wrangling.html#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gross primary productivity&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Site: CH-Lae&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>))) <span class="sc">+</span></span>
<span id="cb68-6"><a href="data-wrangling.html#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>The ups and downs are happening within one day. Remember the introduction of “variations” in our data. This is an example: We have GPP variations at the sub-daily (diurnal) time scale, as well as at the seasonal time scale. This is very typical for environmental time series data. Sometimes, we even have a long-term trend on top of that. Dealing with such multiple scales of variations and “hidden dimensions” something you’ll have to deal with a lot as an “Environmental Systems Data Scientist.”</p>
<p>Note that above, we have first selected rows of the data frame with the dplyr function <code>slice()</code> and then piped its output (which is again a data frame) into <code>ggplot()</code> (which takes as a first argument the data frame).</p>
<p>The second type of visualisation that lets you quickly understand your data better and that often comes early in the exploratory data analysis phase is a histogram. It shows the count of how many points of a certain variable (here, <code>GPP_NT_VUT_REF</code>) fall into a discrete set of bins. When normalising (scaling) the “bars” of the histogram to unity, we get a density histogram. Histograms can be created with ggplot2 using the <code>geom_histogram()</code> function. In the example below, values of the variable of interest (<code>GPP_NT_VUT_REF</code>) are plotted along the x-axis (as is common for histograms). To specify the y-axis position of the upper end of the histogram bar as the density, use <code>y = ..density..</code> in the <code>aes()</code> call. To show counts, use <code>y = ..count..</code></p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="data-wrangling.html#cb69-1" aria-hidden="true" tabindex="-1"></a>hhdf <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="data-wrangling.html#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> GPP_NT_VUT_REF, <span class="at">y =</span> ..density..)) <span class="sc">+</span></span>
<span id="cb69-3"><a href="data-wrangling.html#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;grey70&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 16732 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="data-wrangling.html#cb72-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<pre><code>## geom_density: na.rm = FALSE, orientation = NA, outline.type = upper
## stat_density: na.rm = FALSE, orientation = NA
## position_identity</code></pre>
<p>Note that we added two visualisation layers above. First just the histogram (the dark grey bars), and second the continuous density plot as a red line. Both share the same aesthetics specification with <code>aes()</code>. We’ll encounter such multiple visualisation layers again below.</p>
<p>You can find a complete reference to ggplot <a href="https://ggplot2.tidyverse.org/">here</a>. More complete tutorials data visualization are available <a href="https://r4ds.had.co.nz/data-visualisation.html">there</a> or even more complete <a href="https://clauswilke.com/dataviz/">here</a>. Below, we’ll introduce some more content on data visualisation with R and ggplot2.</p>
<hr />
</div>
<div id="aggregating" class="section level4" number="3.1.1.7">
<h4><span class="header-section-number">3.1.1.7</span> Aggregating</h4>
<p>All data frames have two dimensions, rows and columns. As you learned in Video 2a and 2c, there may be more structure to our data. Our data frame is organised along half-hourly time steps in rows. These time steps belong to different days, months, and years, although these “dimensions” are not reflected by the structure of the data frame and we don’t have columns that indicate the day, month or year of each half-hourly time step. This would actually be redundant information since the date-time objects of columns <code>TIMESTAMP_*</code> contain this information. The tidyverse makes it very easy to work with such “hidden dimensions” of a data frame. Let’s say we want to calculate the mean of half-hourly GPP across each data. That is, to aggregate our half-hourly data to daily data by taking a sum. You see, there are two pieces of information needed for an aggregation step: The factor (or “hidden dimension”) that groups a vector of values for collapsing it into a single value, and the function used for collapsing values. This function should take a vector as an argument and return a single value as an output. These two steps are implemented by the dplyr functions <code>group_by()</code> and <code>summarise()</code> and the nice and intuitive code that solves our problem of aggregating to daily values by summing looks like this:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="data-wrangling.html#cb74-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="ot">&lt;-</span> hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb74-2"><a href="data-wrangling.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as_date</span>(TIMESTAMP_START)) <span class="sc">%&gt;%</span>  <span class="co"># converts the ymd_hm-formatted date-time object to a date-only object (ymd)</span></span>
<span id="cb74-3"><a href="data-wrangling.html#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb74-4"><a href="data-wrangling.html#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">GPP_NT_VUT_REF =</span> <span class="fu">mean</span>(GPP_NT_VUT_REF, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<p>More info on <a href="https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise">grouped summaries</a>, <a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a> and <a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a>.</p>
<p>Using <code>filter()</code>, we can now easily plot daily total GPP for all days in the year 2007.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="data-wrangling.html#cb75-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="data-wrangling.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(date)<span class="sc">==</span><span class="dv">2007</span>) <span class="sc">%&gt;%</span>  <span class="co"># same functions as above can be applied to &#39;date&#39;</span></span>
<span id="cb75-3"><a href="data-wrangling.html#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(date, GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb75-4"><a href="data-wrangling.html#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb75-5"><a href="data-wrangling.html#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>  <span class="co"># we can overlay multiple plot layers!</span></span>
<span id="cb75-6"><a href="data-wrangling.html#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gross primary productivity&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Site: CH-Lae&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)))</span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>You see awkwardly high values sometime in May. What do you think could be the reason for these? Maybe they are based on poorly gap-filled data? To learn more, it is interesting to know how many of the half-hourly data points in each (aggregated) day are based on “bad” data and how many are missing (<code>NA</code>). To get this information, we can use again two aggregation functions <code>group_by()</code> and <code>summarise()</code>, now with multiple functions for summarising different variables.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="data-wrangling.html#cb77-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="ot">&lt;-</span> hhdf <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="data-wrangling.html#cb77-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as_date</span>(TIMESTAMP_START)) <span class="sc">%&gt;%</span>   <span class="co"># converts time object to a date object</span></span>
<span id="cb77-3"><a href="data-wrangling.html#cb77-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span> </span>
<span id="cb77-4"><a href="data-wrangling.html#cb77-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">GPP_NT_VUT_REF =</span> <span class="fu">mean</span>(GPP_NT_VUT_REF, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb77-5"><a href="data-wrangling.html#cb77-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">n_datapoints =</span> <span class="fu">n</span>(), <span class="co"># count the number of observations per day</span></span>
<span id="cb77-6"><a href="data-wrangling.html#cb77-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">n_measured =</span> <span class="fu">sum</span>(NEE_VUT_REF_QC <span class="sc">==</span> <span class="dv">0</span>), <span class="co"># count the number of actually measured data (excluding gap-filled and poor quality data)</span></span>
<span id="cb77-7"><a href="data-wrangling.html#cb77-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">PPFD_IN =</span> <span class="fu">mean</span>(PPFD_IN, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),  <span class="co"># we&#39;ll use this later</span></span>
<span id="cb77-8"><a href="data-wrangling.html#cb77-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span></span>
<span id="cb77-9"><a href="data-wrangling.html#cb77-9" aria-hidden="true" tabindex="-1"></a>              ) <span class="sc">%&gt;%</span> </span>
<span id="cb77-10"><a href="data-wrangling.html#cb77-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">f_measured =</span> n_measured <span class="sc">/</span> n_datapoints) <span class="co"># calculate the fraction of measured values over total observations</span></span></code></pre></div>
<hr />
</div>
<div id="data-visualisation-ii" class="section level4" number="3.1.1.8">
<h4><span class="header-section-number">3.1.1.8</span> Data visualisation II</h4>
<p>After completing the aggregation above, we now have a new “hidden dimension” in our data frame: Each GPP measurement is located not only along a time axis, but also along a “data quality axis,” measured by the fraction of actually measured (not gap-filled) half-hourly data points per day (<code>f_measured</code>). We can use this additional axis and visualise it by using colors of our points according to <code>f_measured</code>. In other words, we “map” <code>f_measured</code> to the color axis, similar to how we “mapped” time and GPP to the x and y axes before. When adding such an additional mapping to visualisation dimensions (“aesthetics”), we have to specify it using <code>aes()</code>. Now, this only affects the points and color of points, while the lines and points and their position in x-y space is shared. Hence, we write <code>aes(x = date, y = GPP_NT_VUT_REF)</code> in the <code>ggplot()</code> function call (indicating that all subsequent additions of <code>geom_</code> layers share this x-y mapping); while <code>aes(color = f_measured)</code> is specified only in the <code>geom_point()</code> layer.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="data-wrangling.html#cb78-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span> </span>
<span id="cb78-2"><a href="data-wrangling.html#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(date)<span class="sc">==</span><span class="dv">2007</span>) <span class="sc">%&gt;%</span>  <span class="co"># same functions as above can be applied to &#39;date&#39;</span></span>
<span id="cb78-3"><a href="data-wrangling.html#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb78-4"><a href="data-wrangling.html#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb78-5"><a href="data-wrangling.html#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> f_measured)) <span class="sc">+</span>  <span class="co"># we can overlay multiple plot layers!</span></span>
<span id="cb78-6"><a href="data-wrangling.html#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gross primary productivity&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Site: CH-Lae&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>))) <span class="sc">+</span></span>
<span id="cb78-7"><a href="data-wrangling.html#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>)  <span class="co"># &quot;viridis&quot; continuous color scale in inverse direction</span></span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>This is interesting. Apparently, the points with particularly low GPP during summer months are predominantly based on gap-filled half-hourly data. This is an insight we would never have gotten by just looking at the naked values in our data frames. Data visualisations are essential for guiding analyses and processing throughout all steps. It’s an iterative process. Having learned this, we now have a justification for applying further data filtering criteria.</p>
<p>Let’s recall our research question that motivates our exploratory data analysis here. We want to know not only about variations in GPP, but also its controls. That is, what are the environmental factors that determine the variations in GPP. In other words, what are the covariates of GPP? In a machine learning context, you may also call them “predictors” or “features.” To answer this question, we’ll have to turn to modelling. Here, we refer to modelling in the wider sense of predicting observed variations in a target variable based on empirical relationships with a set of predictors. We leave the real modelling and machine learning for later chapters. But not fully. Most often, you’ll start delving into your research question with some <em>a priori</em> understanding of the system from which you have observational data. Such an understanding may be informed by previous observations and their interpretations, or by theory.</p>
<p>Here, we want to understand what controls GPP. We’re not the first ones to ask this question and powerful theory is available to understand and predict variations of GPP. You have probably learned that photosynthesis requires sunlight in middle school already and it shouldn’t come as a surprise that the more sunlight there is, say in a day, the higher the GPP. After all, such a presumed positive (maybe even monotonically increasing) relationship is also consistent with the apparent agreement between the scales of variation in GPP and the scales of variation in incoming solar radiation (dark night, bright day; dark winter, bright summer). In our dataset, <code>PPFD_IN</code> is the incoming photosynthetic photon flux density, measured in mol photons (that come in the right wavelength to be used for photosynthesis). So how does its relationship with GPP look like (using daily data)?</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="data-wrangling.html#cb80-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="data-wrangling.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb80-3"><a href="data-wrangling.html#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-4"><a href="data-wrangling.html#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;PPFD (&quot;</span>, mu, <span class="st">&quot;mol m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)) ) <span class="sc">+</span></span>
<span id="cb80-5"><a href="data-wrangling.html#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">25</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 287 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Indeed, there is a clear trend of increasing GPP with increasing PPFD, and it looks largely linear. As in all data collected in the field, there is a substantial amount of scatter. Does the data quality “dimension” explain some of this scatter? To inspect our data for answering this question, let’s “map” the data quality dimension onto the color aesthetic as before.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="data-wrangling.html#cb82-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="data-wrangling.html#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF, <span class="at">color =</span> f_measured)) <span class="sc">+</span></span>
<span id="cb82-3"><a href="data-wrangling.html#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb82-4"><a href="data-wrangling.html#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb82-5"><a href="data-wrangling.html#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;PPFD (&quot;</span>, mu, <span class="st">&quot;mol m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)) ) <span class="sc">+</span></span>
<span id="cb82-6"><a href="data-wrangling.html#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">25</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 287 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>The high values of GPP we already found to be associated with low fractions of underlying measured data in the time series plot is not explained by simultaneously high PPFD. There are a bunch of yellow points that appear like outliers of the linear relationship.</p>
<p>Talking about linear relationships: What is the straight line that “best fits” through our points here? Now, we’re getting into modelling using a univariate linear regression. But we’re not getting too far into it now since it will be revisited in more detail in later chapters.</p>
<p>Anyway, it’s quite intuitive and you probably have encountered how to fit a linear regression model in R before. Here, we would do:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="data-wrangling.html#cb84-1" aria-hidden="true" tabindex="-1"></a>linmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> PPFD_IN, <span class="at">data =</span> ddf)</span></code></pre></div>
<p>We can also directly plot the fitted linear regression line over the scatter plot using <code>geom_smooth(method = "lm")</code>.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="data-wrangling.html#cb85-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="data-wrangling.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb85-3"><a href="data-wrangling.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb85-4"><a href="data-wrangling.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-5"><a href="data-wrangling.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb85-6"><a href="data-wrangling.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;PPFD (&quot;</span>, mu, <span class="st">&quot;mol m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)) ) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 287 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 287 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>Based on our finding that the data quality appears to affect GPP values and their relationship with PPFD, we can fit separate linear regression models for data where <code>f_measured</code> is greater than 0.5 or not. For this, we can create a new variable with <code>mutate(more_measured = as.factor(f_measured &gt; 0.5))</code>). This binary information is yet another “hidden dimension” in our data. And because it’s a categorical variable and not a continuous one, it is treated in R as a <em>factor</em>. We can map this new variable <code>more_measured</code> onto the color aesthetic as we did before. Since we specify this aesthetic below in the <code>ggplot()</code> function call, all subsequent visualisation layers will respect it, also <code>geom_smooth()</code>.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="data-wrangling.html#cb89-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span></span>
<span id="cb89-2"><a href="data-wrangling.html#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">more_measured =</span> <span class="fu">as.factor</span>(f_measured <span class="sc">&gt;</span> <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb89-3"><a href="data-wrangling.html#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF, <span class="at">color =</span> more_measured)) <span class="sc">+</span></span>
<span id="cb89-4"><a href="data-wrangling.html#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span>   <span class="co"># set opacity to 20% to avoid underscernible overplotting</span></span>
<span id="cb89-5"><a href="data-wrangling.html#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)  <span class="sc">+</span></span>
<span id="cb89-6"><a href="data-wrangling.html#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;PPFD (&quot;</span>, mu, <span class="st">&quot;mol m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)) )  <span class="sc">+</span></span>
<span id="cb89-7"><a href="data-wrangling.html#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">25</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 287 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 287 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>There is indeed a slight difference in the slope. Note also that in the above <code>ggplot()</code> call, we specified the aesthetics <code>aes(x = PPFD_IN, y = GPP_NT_VUT_REF, color = more_measured)</code>. This triggers all subsequen additions of visualisation layers (here: <code>geom_piont()</code> and <code>geom_smooth</code>) to use the same aesthetics mapping. That is, the distinction by the same colors is applied both to the points and to the smoothing lines.</p>
<p>The point plots suffer from the fact that many points, particularly in the low PPFD range, are plotted on top of each other. This may hide some information. To unravel it, we may want to visualise the <em>density</em> of points. In other words, we want to plot how many points fall within bins of GPP and PPFD, or grid cells in the GPP-PPFD-space. We can create such a raster plot that measures the density using <code>stat_density_2d()</code>:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="data-wrangling.html#cb93-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="data-wrangling.html#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb93-3"><a href="data-wrangling.html#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_2d</span>(</span>
<span id="cb93-4"><a href="data-wrangling.html#cb93-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">&quot;raster&quot;</span>, <span class="co">#the geometric object to display the data (in this case: rectangles)</span></span>
<span id="cb93-5"><a href="data-wrangling.html#cb93-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">after_stat</span>(density)), <span class="co">#using `density`, a variable calculated by the stat</span></span>
<span id="cb93-6"><a href="data-wrangling.html#cb93-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">contour =</span> <span class="cn">FALSE</span> </span>
<span id="cb93-7"><a href="data-wrangling.html#cb93-7" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb93-8"><a href="data-wrangling.html#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb93-9"><a href="data-wrangling.html#cb93-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb93-10"><a href="data-wrangling.html#cb93-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;PPFD (&quot;</span>, mu, <span class="st">&quot;mol m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)) ) </span></code></pre></div>
<pre><code>## Warning: Removed 324 rows containing non-finite values (stat_density2d).</code></pre>
<pre><code>## Warning: Removed 200 rows containing missing values (geom_raster).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>There seems to be an interesting “separation” of points. In some cases, the increase in GPP with increasing PPFD is steeper than in others. But what determines these “cases?” Again, we can use our <em>a priori</em> understanding of the system to formulate hypotheses and test them by finding the appropriate visualisation type. Here, one hypothesis could be that the slope is steeper in some months than in others. This is actually more than just a vague guess. Can you imagine why?</p>
<p>Let’s visually test this hypothesis and fit separate linear regression models for each month. Note that each month encompasses data from multiple years. Hence, this works only if there is a commonality between the same months of different years. Let’s see…</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="data-wrangling.html#cb96-1" aria-hidden="true" tabindex="-1"></a>ddf <span class="sc">%&gt;%</span></span>
<span id="cb96-2"><a href="data-wrangling.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">as.factor</span>(<span class="fu">month</span>(date))) <span class="sc">%&gt;%</span></span>
<span id="cb96-3"><a href="data-wrangling.html#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF, <span class="at">color =</span> month)) <span class="sc">+</span></span>
<span id="cb96-4"><a href="data-wrangling.html#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb96-5"><a href="data-wrangling.html#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb96-6"><a href="data-wrangling.html#cb96-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb96-7"><a href="data-wrangling.html#cb96-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;PPFD (&quot;</span>, mu, <span class="st">&quot;mol m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;GPP (gC m&quot;</span><span class="sc">^-</span><span class="dv">2</span>, <span class="st">&quot;s&quot;</span><span class="sc">^-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>)) ) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 324 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 324 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>Eureka! The relationships, indeed, separate quite a bit between months. In spring months (3 = March, 4 = April), light levels can be already quite high, but GPP remains much lower than in summer months. Why is this?</p>
</div>
</div>
<div id="dataset-2-daily-flux-data" class="section level3" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Dataset 2 (daily flux data)</h3>
<p>The daily data is given for a set of eddy covariance measurement sites. Data for each site is given in a separate file. When dealing with such a setup, we will likely encounter situations where we have to apply the same sequence of data wrangling steps (or functions) to multiple instances of the same object class. For example, we will have to apply the same data cleaning steps or fitting a regression model to each site’s data. In this example, the object class is a data frame, and the “multiple instances” are the data frames for each site. This is the territory of functional programming…</p>
<p>Of course, we can also combine each site’s data frame into a single large one, e.g., by “stacking” them along the time dimension (rows). In this case, we create a new “hidden dimension” - the site identity. In this subsection, you will learn how to keep an overview and code efficiently while dealing with such large data frames - always using the tidyverse in R.</p>
<div id="functional-programming-i" class="section level4" number="3.1.2.1">
<h4><span class="header-section-number">3.1.2.1</span> Functional programming I</h4>
<p>The <strong>purrr</strong> package of tidyverse offers the functionalities for functional programming. It makes use of lists and applies (or “maps”) a function to each element of the list. Let’s start by creating a list of paths that point to the files with daily data. They are all located in the directory <code>"./data_DD"</code> and share a certain string of characters in their file names <code>"_FLUXNET2015_FULLSET_DD_"</code>.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="data-wrangling.html#cb100-1" aria-hidden="true" tabindex="-1"></a>vec_files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="st">&quot;./data&quot;</span>, <span class="at">pattern =</span> <span class="st">&quot;_FLUXNET2015_FULLSET_DD_&quot;</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb100-2"><a href="data-wrangling.html#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vec_files[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<pre><code>## [1] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;
## [2] &quot;./data/FLX_BE-Lon_FLUXNET2015_FULLSET_DD_2004-2014_1-3.csv&quot;
## [3] &quot;./data/FLX_BE-Vie_FLUXNET2015_FULLSET_DD_1996-2014_1-3.csv&quot;
## [4] &quot;./data/FLX_CH-Cha_FLUXNET2015_FULLSET_DD_2005-2014_2-3.csv&quot;
## [5] &quot;./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv&quot;</code></pre>
<p><code>vec_files</code> is now a vector of 35 files for 35 sites. In simple base-R, we could read them in at once using a simple <code>for</code> loop. The following creates a list of data frames that are generated by <code>read_csv()</code> with the argument <code>ifil</code> iteratively changing, taking values of elements in <code>vec_files</code>.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="data-wrangling.html#cb102-1" aria-hidden="true" tabindex="-1"></a>list_df <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb102-2"><a href="data-wrangling.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (ifil <span class="cf">in</span> vec_files){</span>
<span id="cb102-3"><a href="data-wrangling.html#cb102-3" aria-hidden="true" tabindex="-1"></a>    list_df[[ifil]] <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(ifil)</span>
<span id="cb102-4"><a href="data-wrangling.html#cb102-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>In the tidyverse, the above loop can be written on one line, using the function <code>map()</code> from the purrr package, as:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="data-wrangling.html#cb103-1" aria-hidden="true" tabindex="-1"></a>list_df <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(<span class="fu">as.list</span>(vec_files), <span class="sc">~</span><span class="fu">read_csv</span>(.))</span></code></pre></div>
<p>Note that <code>map()</code> maps the function <code>read_csv()</code> to elements of a <em>list</em>. That’s why we have to convert the vector <code>vec_files</code> to a list, first. The list is always the first argument. You further note two new symbols (<code>~</code> and <code>.</code>). The <code>~</code> always goes before the function that is mapped to elements of the list. The <code>.</code> indicates where the elements of the list would go if spelled out explicitly (e.g., <code>read_csv(.)</code> will be <code>read_csv("./data_DD/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv")</code> for the first iteration). The output of <code>map()</code> is again a list. <code>map()</code> comes in multiple flavours. A complete reference for all purrr functions is available <a href="https://purrr.tidyverse.org/reference/index.html">here</a>. A useful and more extensive tutorial on purrr is available <a href="https://www.r-bloggers.com/one-stop-tutorial-on-purrr-package-in-r/">here</a>.</p>
<p>To be fair, the above <code>map()</code> call doesn’t return a named list as our <code>for</code> loop created. But we can give each element of the returned list of data frames different names by:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="data-wrangling.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(list_df) <span class="ot">&lt;-</span> vec_files  <span class="co"># this makes it a named list</span></span></code></pre></div>
<p>Let’s apply a similar cleaning function as we did before for half-hourly data. Unfortunately, we cannot reuse the same code because not all variables that are given in the half-hourly data are available also in the daily data and because the quality control flag is defined differently. We can define the daily data cleaning function:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="data-wrangling.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="do">## function definition</span></span>
<span id="cb105-2"><a href="data-wrangling.html#cb105-2" aria-hidden="true" tabindex="-1"></a>clean_fluxnet_dd <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb105-3"><a href="data-wrangling.html#cb105-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-4"><a href="data-wrangling.html#cb105-4" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb105-5"><a href="data-wrangling.html#cb105-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-6"><a href="data-wrangling.html#cb105-6" aria-hidden="true" tabindex="-1"></a>    <span class="do">## select only the variables we&#39;re interested in</span></span>
<span id="cb105-7"><a href="data-wrangling.html#cb105-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;TIMESTAMP&quot;</span>),</span>
<span id="cb105-8"><a href="data-wrangling.html#cb105-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">ends_with</span>(<span class="st">&quot;_F&quot;</span>),</span>
<span id="cb105-9"><a href="data-wrangling.html#cb105-9" aria-hidden="true" tabindex="-1"></a>           CO2_F_MDS,</span>
<span id="cb105-10"><a href="data-wrangling.html#cb105-10" aria-hidden="true" tabindex="-1"></a>           PPFD_IN,</span>
<span id="cb105-11"><a href="data-wrangling.html#cb105-11" aria-hidden="true" tabindex="-1"></a>           GPP_NT_VUT_REF,</span>
<span id="cb105-12"><a href="data-wrangling.html#cb105-12" aria-hidden="true" tabindex="-1"></a>           NEE_VUT_REF_QC,</span>
<span id="cb105-13"><a href="data-wrangling.html#cb105-13" aria-hidden="true" tabindex="-1"></a>           USTAR,</span>
<span id="cb105-14"><a href="data-wrangling.html#cb105-14" aria-hidden="true" tabindex="-1"></a>           <span class="fu">ends_with</span>(<span class="st">&quot;QC&quot;</span>),</span>
<span id="cb105-15"><a href="data-wrangling.html#cb105-15" aria-hidden="true" tabindex="-1"></a>           <span class="sc">-</span><span class="fu">contains</span>(<span class="st">&quot;JSB&quot;</span>)</span>
<span id="cb105-16"><a href="data-wrangling.html#cb105-16" aria-hidden="true" tabindex="-1"></a>           ) <span class="sc">%&gt;%</span></span>
<span id="cb105-17"><a href="data-wrangling.html#cb105-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-18"><a href="data-wrangling.html#cb105-18" aria-hidden="true" tabindex="-1"></a>    <span class="do">## convert to a nice date object</span></span>
<span id="cb105-19"><a href="data-wrangling.html#cb105-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">TIMESTAMP =</span> lubridate<span class="sc">::</span><span class="fu">ymd</span>(TIMESTAMP)) <span class="sc">%&gt;%</span></span>
<span id="cb105-20"><a href="data-wrangling.html#cb105-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-21"><a href="data-wrangling.html#cb105-21" aria-hidden="true" tabindex="-1"></a>    <span class="do">## not setting heavily gapfilled data to zero</span></span>
<span id="cb105-22"><a href="data-wrangling.html#cb105-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-23"><a href="data-wrangling.html#cb105-23" aria-hidden="true" tabindex="-1"></a>    <span class="do">## set all -9999 to NA</span></span>
<span id="cb105-24"><a href="data-wrangling.html#cb105-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">na_if</span>(<span class="sc">-</span><span class="dv">9999</span>) <span class="sc">%&gt;%</span></span>
<span id="cb105-25"><a href="data-wrangling.html#cb105-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-26"><a href="data-wrangling.html#cb105-26" aria-hidden="true" tabindex="-1"></a>    <span class="do">## drop QC variables (no longer needed), except NEE_VUT_REF_QC</span></span>
<span id="cb105-27"><a href="data-wrangling.html#cb105-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">&quot;_QC&quot;</span>), NEE_VUT_REF_QC)</span>
<span id="cb105-28"><a href="data-wrangling.html#cb105-28" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>… and apply it to each site’s data frame as follows:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="data-wrangling.html#cb106-1" aria-hidden="true" tabindex="-1"></a>list_df <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(list_df, <span class="sc">~</span><span class="fu">clean_fluxnet_dd</span>(.))</span></code></pre></div>
<p>Sometimes, it may be impractical to have different data frames as elements of a list. In fact, the data frames read in here all have similar shapes. I.e., they share the same columns (but differ by their number of rows, and of course, by their data values). This suggests that we can “stack” each data frame along its rows. This can be done using <code>bind_rows()</code> and we can automatically create a new column <code>"siteid"</code> in the stacked data frame that takes the name of the corresponding list element.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="data-wrangling.html#cb107-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(list_df, <span class="at">.id =</span> <span class="st">&quot;siteid&quot;</span>)</span>
<span id="cb107-2"><a href="data-wrangling.html#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ddf_allsites)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 14
##   siteid TIMESTAMP   TA_F SW_IN_F LW_IN_F VPD_F  PA_F   P_F  WS_F CO2_F_MDS
##   &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 ./dat… 1996-01-01 2.85     11.9    327. 0.262 100.  0.882  1.64        NA
## 2 ./dat… 1996-01-02 0.716    29.6    290. 0.273 101.  0.093  1.28        NA
## 3 ./dat… 1996-01-03 1.01     15.0    318. 0.272 102.  0.41   1.23        NA
## 4 ./dat… 1996-01-04 1.59     22.4    299. 0.624 102.  0.113  3.47        NA
## 5 ./dat… 1996-01-05 2.02     31.5    276. 1.90  100.  0.359  3.25        NA
## 6 ./dat… 1996-01-06 1.61     10.5    308. 1.36   99.7 0.478  3.38        NA
## # … with 4 more variables: PPFD_IN &lt;dbl&gt;, GPP_NT_VUT_REF &lt;dbl&gt;, USTAR &lt;dbl&gt;,
## #   NEE_VUT_REF_QC &lt;dbl&gt;</code></pre>
<p>This creates one single large data frame containing all sites’ data (&gt;167’000 rows) and adds a column named <code>"siteid"</code> that is automatically created by using the names of the list elements of <code>list_df</code>.</p>
<p>As above for the half-hourly data, let’s check the fraction of missing data for each variable.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="data-wrangling.html#cb109-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites <span class="sc">%&gt;%</span></span>
<span id="cb109-2"><a href="data-wrangling.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">funs</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.))<span class="sc">/</span><span class="fu">length</span>(.))) <span class="sc">%&gt;%</span></span>
<span id="cb109-3"><a href="data-wrangling.html#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>()</span></code></pre></div>
<pre><code>##                     [,1]
## siteid          0.000000
## TIMESTAMP       0.000000
## TA_F            0.000000
## SW_IN_F         0.000000
## LW_IN_F         0.000000
## VPD_F           0.000000
## PA_F            0.000000
## P_F             0.000000
## WS_F            0.000000
## CO2_F_MDS       2.710296
## PPFD_IN        22.947253
## GPP_NT_VUT_REF  2.400650
## USTAR          21.993209
## NEE_VUT_REF_QC  1.527306</code></pre>
<p>… and visualise data gaps for one site to check whether our filtering criteria are not too strong.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="data-wrangling.html#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(</span>
<span id="cb111-2"><a href="data-wrangling.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  ddf_allsites,</span>
<span id="cb111-3"><a href="data-wrangling.html#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="cn">FALSE</span>,</span>
<span id="cb111-4"><a href="data-wrangling.html#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">warn_large_data =</span> <span class="cn">FALSE</span></span>
<span id="cb111-5"><a href="data-wrangling.html#cb111-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>We see that, unfortunately, <code>PPFD_IN</code> is often missing.</p>
<hr />
</div>
<div id="strings" class="section level4" number="3.1.2.2">
<h4><span class="header-section-number">3.1.2.2</span> Strings</h4>
<p>Unfortunately, the column <code>siteid</code> now contains strings specifying the full paths of the files that were read. We would like to extract the site name from these strings. But fortunately, the file names follow a clear pattern (Side remark: naming your files wisely can often make your life simpler.).</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="data-wrangling.html#cb112-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites<span class="sc">$</span>siteid <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## [1] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;
## [2] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;
## [3] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;
## [4] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;
## [5] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;
## [6] &quot;./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv&quot;</code></pre>
<p>The paths each start with the subdirectory where they are located (<code>"./data_DD/"</code>), then <code>"FLX_"</code>, and then the site name (the first three entries of the table containing data from all sites are for the site <code>"BE-Bra"</code>), and then some more specifications, including the years that respective files’ data cover. What’s the most effective way to extract the site name from all these strings? The <code>stringr</code> package offers a set of very handy tools to work with strings, see this <a href="https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf">cheat sheet</a> for a summary of them. Here, we would like to extract the six characters, starting at position 15.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="data-wrangling.html#cb114-1" aria-hidden="true" tabindex="-1"></a>vec_sites <span class="ot">&lt;-</span> <span class="fu">str_sub</span>(vec_files, <span class="at">start =</span> <span class="dv">34</span>, <span class="at">end =</span> <span class="dv">39</span>)</span>
<span id="cb114-2"><a href="data-wrangling.html#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vec_sites)</span></code></pre></div>
<pre><code>## [1] &quot;LSET_D&quot; &quot;LSET_D&quot; &quot;LSET_D&quot; &quot;LSET_D&quot; &quot;LSET_D&quot; &quot;LSET_D&quot;</code></pre>
<p>… and overwrite the values of column <code>"siteid"</code> with just these six characters.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="data-wrangling.html#cb116-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites <span class="ot">&lt;-</span> ddf_allsites <span class="sc">%&gt;%</span></span>
<span id="cb116-2"><a href="data-wrangling.html#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">siteid =</span> <span class="fu">str_sub</span>(siteid, <span class="at">start =</span> <span class="dv">34</span>, <span class="at">end =</span> <span class="dv">39</span>))</span>
<span id="cb116-3"><a href="data-wrangling.html#cb116-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-4"><a href="data-wrangling.html#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ddf_allsites)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 14
##   siteid TIMESTAMP   TA_F SW_IN_F LW_IN_F VPD_F  PA_F   P_F  WS_F CO2_F_MDS
##   &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 LSET_D 1996-01-01 2.85     11.9    327. 0.262 100.  0.882  1.64        NA
## 2 LSET_D 1996-01-02 0.716    29.6    290. 0.273 101.  0.093  1.28        NA
## 3 LSET_D 1996-01-03 1.01     15.0    318. 0.272 102.  0.41   1.23        NA
## 4 LSET_D 1996-01-04 1.59     22.4    299. 0.624 102.  0.113  3.47        NA
## 5 LSET_D 1996-01-05 2.02     31.5    276. 1.90  100.  0.359  3.25        NA
## 6 LSET_D 1996-01-06 1.61     10.5    308. 1.36   99.7 0.478  3.38        NA
## # … with 4 more variables: PPFD_IN &lt;dbl&gt;, GPP_NT_VUT_REF &lt;dbl&gt;, USTAR &lt;dbl&gt;,
## #   NEE_VUT_REF_QC &lt;dbl&gt;</code></pre>
<p><strong>Checkpoint</strong></p>
<p>Create a string with your home address. Replace “Umlaute -äöu” and remove the house number. Tip: use the stringr package function str_replace().</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="data-wrangling.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Solution</span></span>
<span id="cb118-2"><a href="data-wrangling.html#cb118-2" aria-hidden="true" tabindex="-1"></a>address <span class="ot">&lt;-</span> <span class="st">&quot;Mr. Miyagi, Universitätsstrasse 16, 8006 Zürich&quot;</span></span>
<span id="cb118-3"><a href="data-wrangling.html#cb118-3" aria-hidden="true" tabindex="-1"></a>address <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(address,<span class="st">&#39;ü&#39;</span>, <span class="st">&#39;ue&#39;</span>)</span>
<span id="cb118-4"><a href="data-wrangling.html#cb118-4" aria-hidden="true" tabindex="-1"></a>address <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(address,<span class="st">&#39;ä&#39;</span>, <span class="st">&#39;ae&#39;</span>)</span>
<span id="cb118-5"><a href="data-wrangling.html#cb118-5" aria-hidden="true" tabindex="-1"></a>address <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(address, <span class="st">&quot;16&quot;</span>, <span class="st">&quot;&quot;</span>)</span>
<span id="cb118-6"><a href="data-wrangling.html#cb118-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(address)</span></code></pre></div>
<pre><code>## [1] &quot;Mr. Miyagi, Universitaetsstrasse , 8006 Zuerich&quot;</code></pre>
</div>
<div id="combining-relational-data" class="section level4" number="3.1.2.3">
<h4><span class="header-section-number">3.1.2.3</span> Combining relational data</h4>
<p>It’s common that we want to combine information from multiple data frames into a single one. In our case, we are interested in knowing more about the sites for which we have time series data. We are interested in <em>meta-information</em> about the sites, for example, the vegetation type, geographical location, elevation, etc. In such cases, where information about common set of units (here sites) is distributed across multiple data objects, we’re speaking of <em>relational data</em>. Of course, there has to be a link between them. In our case, this is the site identity or site name. Specifically, this means that the same labeling of site identities has to be available from all relational data objects.</p>
<p>You may ask yourself what’s the purpose of keeping data in separate relational data objects. Of course, we’d have to duplicate each value of site elevation, for example, when adding this info as a new column to a time series data frame of the respective site. This would inflate the memory of the object considerably without actually adding information. Therefore it can make sense to keep such differently structured data objects separate and combine them only during the analysis step.</p>
<p>A comprehensive collection of FLUXNET site meta information is freely available from <a href="https://daac.ornl.gov/FLUXNET/guides/Fluxnet_site_DB.html">Falge et al.</a>. Let’s read this file (<code>"fluxnet_site_info_all.csv"</code>) from the sub-directory <code>"data_DD/"</code>.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="data-wrangling.html#cb120-1" aria-hidden="true" tabindex="-1"></a>df_sites <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;./data/fluxnet_site_info_all.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_character(),
##   siteid = col_double(),
##   latitude = col_double(),
##   longitude = col_double()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="data-wrangling.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_sites)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 21
##   siteid fluxnetid keyid sitename countryid land_unit status latitude longitude
##    &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1      9 AR-Lac    ar.l… La Cigu… Argentina South Am… Active    -29.3     -61.0
## 2     12 AT-Lan    at.l… Langenf… Austria   Europe    Inact…     47.1      11.0
## 3     13 AT-Leu    at.l… Leutasch Austria   Europe    Inact…     47.4      11.2
## 4     14 AT-Neu    at.n… Neustif… Austria   Europe    Active     47.1      11.3
## 5     15 AT-Sch    at.s… Schlitt… Austria   Europe    Inact…     47.4      11.2
## 6     17 AU-Cas    au.c… Burdeki… Australia Australi… Active    -19.6     147. 
## # … with 12 more variables: year_began &lt;chr&gt;, network1 &lt;chr&gt;, network2 &lt;chr&gt;,
## #   network3 &lt;chr&gt;, koeppen_climate &lt;chr&gt;, gtopo30_elevation &lt;chr&gt;,
## #   igbp_land_use &lt;chr&gt;, umd_land_cover &lt;chr&gt;, lai_fpar &lt;chr&gt;,
## #   npp_land_cover &lt;chr&gt;, plant_functional_type &lt;chr&gt;, network1_id &lt;chr&gt;</code></pre>
<p>The file contains info for many more sites (844 rows for 844 sites) than we have data for (35 sites). The key variable that combines the two is the standard site ID name that is commonly used for FLUXNET sites. In the sites table (<code>df_sites</code>), the key is called <code>fluxnetid</code>. In the temporal dataset <code>ddf_allsites</code>, the site key column is called <code>siteid</code>. To combine (“join”) the two data frames, the joining “key” ID has to be named the same way (here <code>"siteid"</code>) and should of course contain the same set of different values (site names in our case). Hence, we have to rename the respective column in one of our data frames. Then, we’re ready to join.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="data-wrangling.html#cb124-1" aria-hidden="true" tabindex="-1"></a>df_sites <span class="ot">&lt;-</span> df_sites <span class="sc">%&gt;%</span></span>
<span id="cb124-2"><a href="data-wrangling.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>siteid)   <span class="co"># remove this variable first because it doesn&#39;t contain the name we want</span></span>
<span id="cb124-3"><a href="data-wrangling.html#cb124-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-4"><a href="data-wrangling.html#cb124-4" aria-hidden="true" tabindex="-1"></a>ddf_allsites_joined <span class="ot">&lt;-</span> df_sites <span class="sc">%&gt;%</span></span>
<span id="cb124-5"><a href="data-wrangling.html#cb124-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">siteid =</span> fluxnetid) <span class="sc">%&gt;%</span></span>
<span id="cb124-6"><a href="data-wrangling.html#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(ddf_allsites,</span>
<span id="cb124-7"><a href="data-wrangling.html#cb124-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">by =</span> <span class="st">&quot;siteid&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb124-8"><a href="data-wrangling.html#cb124-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-9"><a href="data-wrangling.html#cb124-9" aria-hidden="true" tabindex="-1"></a>  <span class="do">## perform some variable renaming for our own taste</span></span>
<span id="cb124-10"><a href="data-wrangling.html#cb124-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lon =</span> longitude,</span>
<span id="cb124-11"><a href="data-wrangling.html#cb124-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">lat =</span> latitude,</span>
<span id="cb124-12"><a href="data-wrangling.html#cb124-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">elv =</span> gtopo30_elevation</span>
<span id="cb124-13"><a href="data-wrangling.html#cb124-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>Let’s check the number of columns in the two data frames provided as arguments and in the resulting data frame.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="data-wrangling.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(df_sites) <span class="sc">+</span> <span class="fu">ncol</span>(ddf_allsites) <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div>
<pre><code>## [1] 33</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="data-wrangling.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(ddf_allsites_joined)</span></code></pre></div>
<pre><code>## [1] 33</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="data-wrangling.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ddf_allsites_joined)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 33
##   siteid keyid sitename countryid land_unit status   lat   lon year_began
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;     
## 1 LSET_D &lt;NA&gt;  &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;      NA    NA &lt;NA&gt;      
## 2 LSET_D &lt;NA&gt;  &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;      NA    NA &lt;NA&gt;      
## 3 LSET_D &lt;NA&gt;  &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;      NA    NA &lt;NA&gt;      
## 4 LSET_D &lt;NA&gt;  &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;      NA    NA &lt;NA&gt;      
## 5 LSET_D &lt;NA&gt;  &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;      NA    NA &lt;NA&gt;      
## 6 LSET_D &lt;NA&gt;  &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;      NA    NA &lt;NA&gt;      
## # … with 24 more variables: network1 &lt;chr&gt;, network2 &lt;chr&gt;, network3 &lt;chr&gt;,
## #   koeppen_climate &lt;chr&gt;, elv &lt;chr&gt;, igbp_land_use &lt;chr&gt;,
## #   umd_land_cover &lt;chr&gt;, lai_fpar &lt;chr&gt;, npp_land_cover &lt;chr&gt;,
## #   plant_functional_type &lt;chr&gt;, network1_id &lt;chr&gt;, TIMESTAMP &lt;date&gt;,
## #   TA_F &lt;dbl&gt;, SW_IN_F &lt;dbl&gt;, LW_IN_F &lt;dbl&gt;, VPD_F &lt;dbl&gt;, PA_F &lt;dbl&gt;,
## #   P_F &lt;dbl&gt;, WS_F &lt;dbl&gt;, CO2_F_MDS &lt;dbl&gt;, PPFD_IN &lt;dbl&gt;,
## #   GPP_NT_VUT_REF &lt;dbl&gt;, USTAR &lt;dbl&gt;, NEE_VUT_REF_QC &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="data-wrangling.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ddf_allsites)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 14
##   siteid TIMESTAMP   TA_F SW_IN_F LW_IN_F VPD_F  PA_F   P_F  WS_F CO2_F_MDS
##   &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 LSET_D 1996-01-01 2.85     11.9    327. 0.262 100.  0.882  1.64        NA
## 2 LSET_D 1996-01-02 0.716    29.6    290. 0.273 101.  0.093  1.28        NA
## 3 LSET_D 1996-01-03 1.01     15.0    318. 0.272 102.  0.41   1.23        NA
## 4 LSET_D 1996-01-04 1.59     22.4    299. 0.624 102.  0.113  3.47        NA
## 5 LSET_D 1996-01-05 2.02     31.5    276. 1.90  100.  0.359  3.25        NA
## 6 LSET_D 1996-01-06 1.61     10.5    308. 1.36   99.7 0.478  3.38        NA
## # … with 4 more variables: PPFD_IN &lt;dbl&gt;, GPP_NT_VUT_REF &lt;dbl&gt;, USTAR &lt;dbl&gt;,
## #   NEE_VUT_REF_QC &lt;dbl&gt;</code></pre>
<p>Here, we’ve done a <code>right_join()</code>. This can be understood as joining the data frame given by the first argument to <code>right_join()</code> (here, what’s being piped from the left side of the pipe) onto the data frame given by the second argument (<code>ddf_allsites</code>). The output of <code>right_join()</code> has the same number or rows as the data frame on the “right” (the second argument) and is, as for all tidyverse functions, a data frame. There is also a <code>left_join()</code> that creates a new data frame with the number of rows corresponding to the data frame on the “left” (the first argument). You can find more on relational data and joining data frames, e.g., <a href="https://r4ds.had.co.nz/relational-data.html">here</a>, or <a href="https://rpubs.com/williamsurles/293454">here</a>.</p>
<hr />
<p><strong>Everything below this box is Bonus Material</strong></p>
</div>
<div id="functional-programming-ii" class="section level4" number="3.1.2.4">
<h4><span class="header-section-number">3.1.2.4</span> Functional programming II</h4>
<p>Functions can be applied to any list. Because lists can consist of any type of objects, <code>map()</code> is a powerful approach to “iterating” over multiple instances of the same object and can be used for all sorts of tasks. In the following, list elements are data frames of daily data and the mapping function <code>lm()</code> fits a linear regression model of GPP versus PPFD to each sites’ data.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="data-wrangling.html#cb133-1" aria-hidden="true" tabindex="-1"></a>list_linmod <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(list_df, <span class="sc">~</span><span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> PPFD_IN, <span class="at">data =</span> .))</span></code></pre></div>
<p>Note how the <code>.</code> now indicates where the elements of <code>list_df</code> go when evaluating the <code>lm()</code> function. This now returns a list of linear model objects (the type of objects returned by the <code>lm()</code> function call).</p>
<p>We can spin the functional programming concept further and apply (or map) the <code>summary()</code> function to the <code>lm</code>-model objects to get a list of useful statistics and metrics, and then further extract the element <code>r.squared"</code> from that list as:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="data-wrangling.html#cb134-1" aria-hidden="true" tabindex="-1"></a>list_linmod <span class="sc">%&gt;%</span></span>
<span id="cb134-2"><a href="data-wrangling.html#cb134-2" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">map</span>(summary) <span class="sc">%&gt;%</span>              <span class="co"># applyting a function</span></span>
<span id="cb134-3"><a href="data-wrangling.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">map_dbl</span>(<span class="st">&quot;r.squared&quot;</span>) <span class="sc">%&gt;%</span>      <span class="co"># extracting from a named list</span></span>
<span id="cb134-4"><a href="data-wrangling.html#cb134-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="co"># for handy output</span></span></code></pre></div>
<pre><code>## ./data/FLX_BE-Bra_FLUXNET2015_FULLSET_DD_1996-2014_2-3.csv 
##                                                  0.7732644 
## ./data/FLX_BE-Lon_FLUXNET2015_FULLSET_DD_2004-2014_1-3.csv 
##                                                  0.3674492 
## ./data/FLX_BE-Vie_FLUXNET2015_FULLSET_DD_1996-2014_1-3.csv 
##                                                  0.7279673 
## ./data/FLX_CH-Cha_FLUXNET2015_FULLSET_DD_2005-2014_2-3.csv 
##                                                  0.5340263 
## ./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv 
##                                                  0.3777200 
## ./data/FLX_CH-Fru_FLUXNET2015_FULLSET_DD_2005-2014_2-3.csv 
##                                                  0.6067123</code></pre>
<p><code>map_dbl()</code> is a variant of the <code>map()</code> function that returns not a list, but a vector of numeric values of class “double” (hence, the name <code>_dbl</code>). Note further, that providing a character (<code>"r.squared"</code>) as an argument instead of an (unquoted) function name, <code>map()</code> extracts the correspondingly named list element, instead of applying a function to a list element.</p>
<p>When writing code for an analysis, it’s useful, if not essential, to understand the objects we’re working with and make sense of the results of simple <code>print &lt;object&gt;</code> statements. Data frames are particularly handy as they provide an organisation of data that is particularly intuitive (variables along columns, observations along rows, values in cells). We’ve encountered such data frames above. Here, we’re dealing with a list of linear model objects. Can such a list fit into the tidy paradigm?</p>
<p>Yes, they can. Think of the linear model objects as ‘values.’ Values don’t necessarily have to be scalars, but they can be of any type (class).</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="data-wrangling.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb136-2"><a href="data-wrangling.html#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteid =</span> vec_sites,</span>
<span id="cb136-3"><a href="data-wrangling.html#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">linmod =</span> list_linmod</span>
<span id="cb136-4"><a href="data-wrangling.html#cb136-4" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 35 x 2
##    siteid linmod      
##    &lt;chr&gt;  &lt;named list&gt;
##  1 LSET_D &lt;lm&gt;        
##  2 LSET_D &lt;lm&gt;        
##  3 LSET_D &lt;lm&gt;        
##  4 LSET_D &lt;lm&gt;        
##  5 LSET_D &lt;lm&gt;        
##  6 LSET_D &lt;lm&gt;        
##  7 LSET_D &lt;lm&gt;        
##  8 LSET_D &lt;lm&gt;        
##  9 LSET_D &lt;lm&gt;        
## 10 LSET_D &lt;lm&gt;        
## # … with 25 more rows</code></pre>
<p>The fact that cells can contain any type of object offers a powerful concept. Instead of a linear model object as in the example above, each cell may also contain another data frame. In such a case, we say that the data frame is no longer flat, but <em>nested</em>.</p>
<p>The following creates a nested data frame, where the column <code>data</code> is defined by the list of data frames read from files above (<code>list_df</code>).</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="data-wrangling.html#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb138-2"><a href="data-wrangling.html#cb138-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteid =</span> vec_sites,</span>
<span id="cb138-3"><a href="data-wrangling.html#cb138-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> list_df</span>
<span id="cb138-4"><a href="data-wrangling.html#cb138-4" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 35 x 2
##    siteid data                 
##    &lt;chr&gt;  &lt;named list&gt;         
##  1 LSET_D &lt;tibble [6,940 × 13]&gt;
##  2 LSET_D &lt;tibble [4,018 × 13]&gt;
##  3 LSET_D &lt;tibble [6,940 × 13]&gt;
##  4 LSET_D &lt;tibble [3,652 × 13]&gt;
##  5 LSET_D &lt;tibble [6,574 × 13]&gt;
##  6 LSET_D &lt;tibble [3,652 × 13]&gt;
##  7 LSET_D &lt;tibble [4,018 × 13]&gt;
##  8 LSET_D &lt;tibble [2,557 × 13]&gt;
##  9 LSET_D &lt;tibble [4,018 × 13]&gt;
## 10 LSET_D &lt;tibble [3,287 × 13]&gt;
## # … with 25 more rows</code></pre>
<p>We can achieve the same result, by directly nesting the flat data frame holding all sites’ data (<code>ddf_allsites</code>). This is done by combining the <code>group_by()</code>, which we have encountered above when aggregating using <code>summarise()</code>, with the function <code>nest()</code> from the tidyr package.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="data-wrangling.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb140-2"><a href="data-wrangling.html#cb140-2" aria-hidden="true" tabindex="-1"></a>ddf_allsites <span class="sc">%&gt;%</span></span>
<span id="cb140-3"><a href="data-wrangling.html#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(siteid) <span class="sc">%&gt;%</span></span>
<span id="cb140-4"><a href="data-wrangling.html#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>()</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
## # Groups:   siteid [1]
##   siteid data                   
##   &lt;chr&gt;  &lt;list&gt;                 
## 1 LSET_D &lt;tibble [167,288 × 13]&gt;</code></pre>
<p>The function <code>nest()</code> names the nested data column automatically <code>"data"</code>.</p>
<p>This structure is very useful. For example for applying functions over sites’ data frames separately (and not over the entire data frame). By combining <code>map()</code> and <code>mutate()</code>, we can fit linear models on each site’s data frame individually in one go.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="data-wrangling.html#cb142-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites <span class="sc">%&gt;%</span></span>
<span id="cb142-2"><a href="data-wrangling.html#cb142-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(siteid) <span class="sc">%&gt;%</span></span>
<span id="cb142-3"><a href="data-wrangling.html#cb142-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb142-4"><a href="data-wrangling.html#cb142-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">linmod =</span> <span class="fu">map</span>(data, <span class="sc">~</span><span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> PPFD_IN, <span class="at">data =</span> .)))</span></code></pre></div>
<p>This is approach is extremely powerful and lets you stick to handy and tidy data frames and use the rows-dimension flexibly. Here, rows are sites and no longer time steps, while the nested data frames in column <code>"data"</code> has time steps along their rows.</p>
<p>And just because it’s fun, this can be spun further, with the same steps as done above, to:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="data-wrangling.html#cb143-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites_nested <span class="ot">&lt;-</span> ddf_allsites <span class="sc">%&gt;%</span></span>
<span id="cb143-2"><a href="data-wrangling.html#cb143-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(siteid) <span class="sc">%&gt;%</span></span>
<span id="cb143-3"><a href="data-wrangling.html#cb143-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb143-4"><a href="data-wrangling.html#cb143-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">linmod =</span> purrr<span class="sc">::</span><span class="fu">map</span>(data, <span class="sc">~</span><span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> PPFD_IN, <span class="at">data =</span> .))) <span class="sc">%&gt;%</span></span>
<span id="cb143-5"><a href="data-wrangling.html#cb143-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">summ =</span> purrr<span class="sc">::</span><span class="fu">map</span>(linmod, <span class="sc">~</span><span class="fu">summary</span>(.))) <span class="sc">%&gt;%</span></span>
<span id="cb143-6"><a href="data-wrangling.html#cb143-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rsq =</span> purrr<span class="sc">::</span><span class="fu">map_dbl</span>(summ, <span class="st">&quot;r.squared&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb143-7"><a href="data-wrangling.html#cb143-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(rsq)) <span class="do">## to arrange output, with highest r-squared on top</span></span></code></pre></div>
<p>Amazing! In these few lines we have separated a huge flat data frame containing all sites’ data, fitted a linear regression model to each site’s data separately, extracted summary statistics (a list), and the R<sup>2</sup> (the coefficient of determination) for each of them, and finally rearranged rows in descending order by R<span class="math inline">\(^2\)</span>. And the output is a handy and nicely looking data frame with nested columns:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="data-wrangling.html#cb144-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites_nested <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
## # Groups:   siteid [1]
##   siteid data                    linmod summ         rsq
##   &lt;chr&gt;  &lt;list&gt;                  &lt;list&gt; &lt;list&gt;     &lt;dbl&gt;
## 1 LSET_D &lt;tibble [167,288 × 13]&gt; &lt;lm&gt;   &lt;smmry.lm&gt; 0.415</code></pre>
<p>Nesting is useful also for avoiding value duplication when joining relational data objects. Above, we nested time series data objects (where time steps and sites are both organised along rows) by sites and got a data frame where only sites are organised along rows, while time steps are nested inside the column <code>"data"</code>. This now fits the structure of a relational data object containing site-specific meta information (also with only sites along rows). (Of course, there is just one elevation value for each site - site elevation doesn’t change over time.). Joining the nested data frame with site meta information results in a substantially smaller and much handier data frame than joining the flat long data frame with site meta information as we did in Section <em>Combining relational data</em>.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="data-wrangling.html#cb146-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites_nested_joined <span class="ot">&lt;-</span> df_sites <span class="sc">%&gt;%</span></span>
<span id="cb146-2"><a href="data-wrangling.html#cb146-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">siteid =</span> fluxnetid) <span class="sc">%&gt;%</span></span>
<span id="cb146-3"><a href="data-wrangling.html#cb146-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(ddf_allsites_nested,</span>
<span id="cb146-4"><a href="data-wrangling.html#cb146-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">by =</span> <span class="st">&quot;siteid&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb146-5"><a href="data-wrangling.html#cb146-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-6"><a href="data-wrangling.html#cb146-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## perform some variable renaming for our own taste</span></span>
<span id="cb146-7"><a href="data-wrangling.html#cb146-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lon =</span> longitude,</span>
<span id="cb146-8"><a href="data-wrangling.html#cb146-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">lat =</span> latitude,</span>
<span id="cb146-9"><a href="data-wrangling.html#cb146-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">elv =</span> gtopo30_elevation</span>
<span id="cb146-10"><a href="data-wrangling.html#cb146-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb146-11"><a href="data-wrangling.html#cb146-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-12"><a href="data-wrangling.html#cb146-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Flat long and joined:&quot;</span>); <span class="fu">object.size</span>(ddf_allsites_joined) <span class="sc">%&gt;%</span> <span class="fu">print</span>(<span class="at">units =</span> <span class="st">&quot;auto&quot;</span>, <span class="at">standard =</span> <span class="st">&quot;SI&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Flat long and joined:&quot;</code></pre>
<pre><code>## 44.2 MB</code></pre>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="data-wrangling.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Nested and joined:&quot;</span>); <span class="fu">object.size</span>(ddf_allsites_nested_joined <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>linmod, <span class="sc">-</span>summ, <span class="sc">-</span>rsq)) <span class="sc">%&gt;%</span> <span class="fu">print</span>(<span class="at">units =</span> <span class="st">&quot;auto&quot;</span>, <span class="at">standard =</span> <span class="st">&quot;SI&quot;</span>)  <span class="co"># removing added columns that are not in the flat long df</span></span></code></pre></div>
<pre><code>## [1] &quot;Nested and joined:&quot;</code></pre>
<pre><code>## 17.4 MB</code></pre>
<hr />
</div>
<div id="advanced-data-visualisation" class="section level4" number="3.1.2.5">
<h4><span class="header-section-number">3.1.2.5</span> Advanced data visualisation</h4>
<p>Let’s dive a bit further into visualisation. We’ve encountered how to map different dimensions of our data not only onto x and y axes in a cartesian coordinate system, but also along other “aesthetics.” We mapped it to color, but there are also other aesthetics available for such mapping in ggplot2, in particular for categorical variables (e.g., line type, point type). Yet another “mapping” is available with <code>facet_wrap()</code>. It separates the visualisation into different sub-plots, each showing a part of the data. It’s not dealt the same way as other aesthetics (not with specifying it with <code>aes()</code>), but with adding the <code>facet_wrap()</code> with a <code>+</code> to the <code>ggplot()</code> object.</p>
<p>Remember that our data frame <code>ddf_allsites</code> has the time series data nested for each site in the column <code>data</code>. ggplot doesn’t like that. Therefore, we can simply <code>unnest()</code> the respective column and get a long flat data frame again. Let’s plot GPP versus PPFD in separate subplots for each site. The factor (column name) by which <code>facet_wrap()</code> separates the plot has to be specified as an argument with a preceeding <code>~</code>. Here, this is <code>~siteid</code>.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="data-wrangling.html#cb152-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites_joined <span class="sc">%&gt;%</span></span>
<span id="cb152-2"><a href="data-wrangling.html#cb152-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> PPFD_IN, <span class="at">y =</span> GPP_NT_VUT_REF)) <span class="sc">+</span></span>
<span id="cb152-3"><a href="data-wrangling.html#cb152-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb152-4"><a href="data-wrangling.html#cb152-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>siteid)</span></code></pre></div>
<pre><code>## Warning: Removed 38583 rows containing missing values (geom_point).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>What do you notice? Does the relationship look similar for all sites?</p>
<p>Again, we get further if we have some <em>a priori</em> knowledge about the system that generated out data. Of course, PPFD just measures the incoming photosynthetically active light. We don’t know whether there are any leaves on the trees to absorb that light. While some trees shed their leaves during winter or during the dry period, others are evergreen and the fraction of PPFD they actually absorb doesn’t vary by far not as much as for deciduous trees. Therefore, whether a site is dominated by deciduous or evergreen vegetation should somehow affect how directly GPP is correlated with GPP. So there’s our hypothesis: Sites with evergreen vegetation should exhibit a higher <em>R</em><sup>2</sup> between GPP and PPFD than sites with deciduous vegetation. Remember that we have evaluated the <em>R</em><sup>2</sup> between GPP and PPFD already above and have it stored as a column <code>rsq</code> of our nested data frame <code>ddf_allsites</code>. We have also collected site meta-information about the vegetation type (it’s in column <code>lai_fpar</code>), and have joined the meta info onto the data. Unfortunately, it’s not quite ready to use. Since we need a <code>TRUE</code>/<code>FALSE</code> type of information of whether the vegetation type is evergreen or not, we have to take another step. Below, we take the strings of column <code>lai_fpar</code> and check whether it contains the sub-string <code>"Evergreen"</code>, using the function <code>str_detect()</code> from the stringr package (part of the tidyverse). This boolean information makes up a new column that we call <code>evergreen</code>. Sounds like a lot of steps, but in the tidyverse, the code is short and clean:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="data-wrangling.html#cb154-1" aria-hidden="true" tabindex="-1"></a>gg <span class="ot">&lt;-</span> ddf_allsites_nested_joined <span class="sc">%&gt;%</span></span>
<span id="cb154-2"><a href="data-wrangling.html#cb154-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">evergreen =</span> <span class="fu">str_detect</span>(lai_fpar, <span class="st">&quot;Evergreen&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb154-3"><a href="data-wrangling.html#cb154-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> rsq, <span class="at">x =</span> evergreen)) <span class="sc">+</span></span>
<span id="cb154-4"><a href="data-wrangling.html#cb154-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb154-5"><a href="data-wrangling.html#cb154-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gg)</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>Eureka II! Indeed, the <em>R</em><sup>2</sup> between GPP and PPFD tend to be higher for sites with evergreen vegetation than for sites with deciduous vegetation. What we see here is a boxplot. It visualises the distribution of <em>R</em><sup>2</sup> by factors (<code>evergreen</code>). The fat horizontal like inside the box indicates the median, the lower and upper margins of the box are the 25% and 75% quantiles, the whiskers (vertical lines) extend 1.5 times the inter-quartile range, starting at the upper and lower margins of the box, or just to the smallest and largest values if they are within a shorter distance. Apparently, in our plot above, they are.</p>
<p>Boxplots are useful because they provide a visualisation of distrubtions that can be based on a very large number of underlying points. This yields “light” and clean figures. However, they also hide a lot of information and sometimes it’s ok to show more information without overloading the plot. For example, individual points can be shown in the plot above by <code>geom_jitter()</code>. Of course, the x-axis represents the level of the factor <code>evergreen</code> and when using a simple <code>geom_points</code>, all points would be located either at the position (given by the tick mark) of <code>TRUE</code> or <code>FALSE</code>. This would result in overplotting and thus hiding a large number of points. <code>geom_jitter()</code> takes care of this by slightly rearranging them in a random fashion along the x-axis. Note that the rearranged position along the x-axis doesn’t actually encode any information. However, as long as points are still separable along the “<code>evergreen</code>-axis,” this is acceptable.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="data-wrangling.html#cb155-1" aria-hidden="true" tabindex="-1"></a>gg <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">color =</span> <span class="st">&quot;grey50&quot;</span>, <span class="at">width =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p><img src="esds_book_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>Note that in the two cells above, we have first stored the output of a <code>ggplot()</code> call as a new object that we named <code>gg</code>. Doing <code>print(gg)</code> just creates the respective plot. The advantage is that we can add visualisation elements or modify the theme or add labels to that object in a separate step.</p>
<p>Maybe you’ve asked yourself whether the magnitude of GPP varies much across vegetation types (column <code>igbp_land_use</code> in our dataset).</p>
<p>Let’s do another boxplot - because we can…</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="data-wrangling.html#cb156-1" aria-hidden="true" tabindex="-1"></a>ddf_allsites_joined <span class="sc">%&gt;%</span></span>
<span id="cb156-2"><a href="data-wrangling.html#cb156-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> GPP_NT_VUT_REF, <span class="at">x =</span> igbp_land_use)) <span class="sc">+</span></span>
<span id="cb156-3"><a href="data-wrangling.html#cb156-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb156-4"><a href="data-wrangling.html#cb156-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 4016 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="esds_book_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>Here, you can see a number of points that are beyond the quartiles plot 1.5 times the inter-quartile range. They are plotted individually and are referred to as “outlying points.” We have also flipped the boxes to extend vertically. <code>coord_flip()</code> overrides what is specified by <code>aes()</code> in that it rotates it by 90<sup>º</sup>.</p>
<p>Before we finish, let’s save our nice daily data frame, after having selected interesting variables, having nested data by sites, and after having complemented it with site meta information. We may use it later in the course …</p>
<p>Since <code>ddf_allsites_nested_joined</code> is no longer a “flat” table (it’s nested), we cannot save it in a plain text-based format like CSV. Instead, we save it as an R object. In can be later loaded into an R session by <code>load()</code>.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="data-wrangling.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(ddf_allsites_nested_joined, <span class="at">file =</span> <span class="st">&quot;data/ddf_allsites_nested_joined.RData&quot;</span>)</span></code></pre></div>
</div>
<div id="exercise" class="section level4" number="3.1.2.6">
<h4><span class="header-section-number">3.1.2.6</span> Exercise</h4>
<p>For this week’s exercise open up the Rstudio environment. Remember to save all your changes to this notebook using <code>git status</code>, <code>git add &lt;filename&gt;</code>, <code>git commit -m "your comment"</code>, <code>git push</code>.</p>
<p>Exercise 02 is about outlier removal and the visualisation of diurnal and seasonal cycles.</p>
<p>Get in touch with your teaching assistant if you have any further questions.</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="primers.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-variety.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["esds_book.pdf", "esds_book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
